-- ═══════════════════════════════════════════════════════════════════
-- AI: matching leads by meaning, not by shared words
-- ═══════════════════════════════════════════════════════════════════
--
-- Word-stem matching reaches a supplier selling "galvanised poles" from a
-- request for "octagonal pole", because the two share a stem. It cannot reach
-- one selling "steel tubing" — no word in common, though any trader can see
-- they are in the same business.
--
-- An embedding is a numeric fingerprint of a phrase, positioned so phrases
-- that mean similar things sit near each other. Comparing fingerprints catches
-- what word matching cannot.
--
-- The fingerprints are generated by a small model running INSIDE the Supabase
-- Edge Function. No third-party API key, no per-call charge.
--
-- Everything here degrades. A product or requirement with no fingerprint yet
-- is matched exactly as it is today, so nothing breaks while the backfill runs
-- and nothing breaks if the Edge Function is never deployed.

create extension if not exists vector;

alter table products     add column if not exists embedding vector(384);
alter table requirements add column if not exists embedding vector(384);

-- What each fingerprint was made from, so a later edit is spotted and the
-- fingerprint regenerated rather than silently going stale.
alter table products     add column if not exists embedded_text text;
alter table requirements add column if not exists embedded_text text;

comment on column products.embedding is
  'Meaning fingerprint of name + brand + description. Written by the bubu-ai Edge Function.';


-- ─────────────────────────────────────────── writing a fingerprint
--
-- Called by the Edge Function once it has the numbers. Security definer so it
-- can write the column, but it checks ownership first: a supplier fingerprints
-- only their own products, a buyer their own requirements, admin anything.

create or replace function public.set_embedding(
  p_kind text,
  p_id uuid,
  p_vector float8[],
  p_text text
) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  v_me uuid := current_account_id();
  v_vec vector(384) := p_vector::vector(384);
begin
  if v_me is null then raise exception 'Sign in first'; end if;

  if p_kind = 'product' then
    update products set embedding = v_vec, embedded_text = p_text
    where id = p_id and (supplier_id = v_me or is_admin());
  elsif p_kind = 'requirement' then
    update requirements set embedding = v_vec, embedded_text = p_text
    where id = p_id and (buyer_id = v_me or is_admin());
  else
    raise exception 'Unknown kind: %', p_kind;
  end if;

  return found;
end $$;

grant execute on function public.set_embedding(text, uuid, float8[], text) to authenticated;


-- ─────────────────────────────────────────── what still needs one
--
-- Drives the backfill: rows with no fingerprint, or whose text has changed
-- since it was made. Capped so one pass cannot run away.

create or replace function public.embedding_backlog(p_limit int default 25)
returns table(kind text, id uuid, content text)
language sql stable security definer set search_path = public as $$
  with me as (select current_account_id() as id)
  select 'product'::text, p.id,
    concat_ws('. ', p.name, nullif(p.brand, ''), nullif(p.description, ''),
      (select c.name from categories c where c.id = p.category_id))
  from products p, me
  where (p.supplier_id = me.id or is_admin())
    and (p.embedding is null
      or p.embedded_text is distinct from concat_ws('. ', p.name, nullif(p.brand, ''),
           nullif(p.description, ''), (select c.name from categories c where c.id = p.category_id)))
  union all
  select 'requirement'::text, r.id,
    concat_ws('. ', r.title, nullif(r.specification, ''))
  from requirements r, me
  where (r.buyer_id = me.id or is_admin())
    and (r.embedding is null
      or r.embedded_text is distinct from concat_ws('. ', r.title, nullif(r.specification, '')))
  limit greatest(1, least(p_limit, 100));
$$;

grant execute on function public.embedding_backlog(int) to authenticated;


-- ─────────────────────────────────────────── the board, now by meaning
--
-- Rewritten so every condition is an EXISTS rather than a join. That removes
-- the DISTINCT the old version needed, which in turn allows ordering by
-- relevance: the closest match to what this supplier actually sells comes
-- first, and anything matched only by word stem falls in behind, newest first.
--
-- 0.62 cosine distance is the cut. Below it the two phrases are about the same
-- trade; above it they drift. Tune that one constant.

-- Keeps "setof requirements" deliberately. Naming the columns instead would
-- change the return type of a function that already exists, which Postgres
-- refuses outright, and would tie this signature to sixteen column types that
-- can drift. The fingerprint does travel on this path, but this is only the
-- fallback: my_lead_board() serves the real board and returns named jsonb keys.
create or replace function my_buy_leads()
returns setof requirements
language sql stable security definer set search_path = public as $$
  with me as (select current_account_id() as id),
  terms as (select term from lead_terms((select id from me))),
  has_terms as (select exists(select 1 from terms) as any)
  select r.*
  from requirements r, me, has_terms
  where r.state = 'open'
    and r.buyer_id <> me.id
    and (
      -- a supplier with nothing listed yet sees the whole open board
      not has_terms.any

      -- MEANING: a product of theirs whose fingerprint sits near this
      -- requirement's. Skipped silently when either side has none yet.
      or (r.embedding is not null and exists (
        select 1 from products p
        where p.supplier_id = me.id
          and p.embedding is not null
          and (p.embedding <=> r.embedding) < 0.62
      ))

      -- WORDS: a shared stem in either direction, as before
      or exists (
        select 1
        from terms t
        cross join unnest(string_to_array(
          regexp_replace(lower(concat_ws(' ', r.title, r.specification)), '[^a-z0-9]+', ' ', 'g'), ' ')) as rw
        where length(rw) >= 3
          and (rw like t.term || '%' or t.term like rw || '%')
      )

      -- or close enough to survive a typo
      or exists (select 1 from terms t where similarity(lower(r.title), t.term) > 0.35)

      -- or the buyer picked a category the supplier holds
      or exists (
        select 1 from account_categories ac
        left join categories rc on rc.id = r.category_id
        where ac.account_id = me.id
          and r.category_id is not null
          and (ac.category_id = r.category_id or ac.category_id = rc.parent_id)
      )
    )
    -- the supplier's own value and district preferences still apply
    and not exists (
      select 1 from lead_preferences pref
      where pref.account_id = me.id
        and (
          (pref.min_value is not null and coalesce(r.estimated_value, 0) < pref.min_value)
          or (not pref.nationwide and cardinality(pref.districts) > 0
              and r.district_id is not null
              and r.district_id <> all(pref.districts)
              and not exists (select 1 from unnest(pref.districts) d
                              where district_km(d, r.district_id) <= pref.radius_km))
        )
    )
  order by
    coalesce((
      select min(p.embedding <=> r.embedding)
      from products p
      where p.supplier_id = me.id and p.embedding is not null and r.embedding is not null
    ), 2),
    r.created_at desc;
$$;


-- ─────────────────────────────────────────── buyer-side suggestions
--
-- The type-ahead under "What do you need". Word matches first, because a buyer
-- half way through typing "cem" wants "Cement" immediately; meaning matches
-- fill in behind once there is enough text to work with.

create or replace function public.suggest_products_semantic(
  p_query text,
  p_vector float8[] default null
)
returns table(name text, category_id text, category_name text, supplier_count bigint, by_meaning boolean)
language sql stable security definer set search_path = public as $$
  with q as (
    select lower(w) as w
    from unnest(string_to_array(regexp_replace(lower(coalesce(p_query,'')), '[^a-z0-9]+', ' ', 'g'), ' ')) as w
    where length(w) >= 2
  ),
  vec as (select case when p_vector is null then null else p_vector::vector(384) end as v),
  words as (
    select p.name, p.category_id, c.name as category_name,
      count(distinct p.supplier_id) as supplier_count, false as by_meaning, 0::float as d
    from products p
    left join categories c on c.id = p.category_id
    where p.status = 'published'
      and exists (
        select 1 from q
        cross join unnest(string_to_array(regexp_replace(lower(p.name), '[^a-z0-9]+', ' ', 'g'), ' ')) as pw
        where pw like q.w || '%' or q.w like pw || '%'
      )
    group by p.name, p.category_id, c.name
  ),
  meaning as (
    select p.name, p.category_id, c.name as category_name,
      count(distinct p.supplier_id) as supplier_count, true as by_meaning,
      min(p.embedding <=> (select v from vec))::float as d
    from products p
    left join categories c on c.id = p.category_id
    where p.status = 'published'
      and (select v from vec) is not null
      and p.embedding is not null
      and (p.embedding <=> (select v from vec)) < 0.62
      and p.name not in (select name from words)
    group by p.name, p.category_id, c.name
  )
  select t.name, t.category_id, t.category_name, t.supplier_count, t.by_meaning
  from (select * from words union all select * from meaning) t
  order by t.by_meaning, t.d, t.supplier_count desc, t.name
  limit 8;
$$;

grant execute on function public.suggest_products_semantic(text, float8[]) to authenticated, anon;
