-- 0065 part 3 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Installation system — Roof vent','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Skylight','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof boot','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — PVC gutter','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Metal gutter','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Box gutter','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Half-round gutter','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Downpipe','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter outlet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter bracket','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter guard','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Drainage hopper','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roofing screw','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Self-drilling screw','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Hook bolt','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — J-bolt','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Rubber washer','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Metal washer','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof clip','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Fastener cap','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — PU foam board','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof blanket','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Thermal membrane','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — PVC ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Mineral fibre tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Acoustic tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Metal ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Wood ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Baffle ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Stretch ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Ceiling grid','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Cross tee','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Hanger wire','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling angle','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof rafter','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof batten','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Timber purlin','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof truss','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Timber fascia','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Timber soffit','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof pole','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof bracing','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Timber ridge board','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Treated roof timber','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Static roof vent','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Vent mesh','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof coating','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Waterproof tape','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof sealant','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Flashing sealant','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof repair compound','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Butyl tape','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — EPDM membrane','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof primer','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof skylight','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Polycarbonate sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Fiberglass roof sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Translucent roof panel','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Dome skylight','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof lantern','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Light pipe','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Skylight curb','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Skylight flashing','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Skylight seal','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof anchor','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof walkway','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof guardrail','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof ladder hook','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof access hatch','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Safety mesh','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof warning sign','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof edge barrier','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof fall-arrest point','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling plaster','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling filler','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Decorative ceiling moulding','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling primer','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling paint','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling adhesive','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling access hatch','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Downpipe shoe','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Downpipe offset','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter union','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter end cap','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter stop end','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter leaf guard','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Gutter strainer','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Downpipe connector','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Copper armoured cable','electrical-lighting','electrical-lighting--power-cables'),
('Copper non-armoured cable','electrical-lighting','electrical-lighting--power-cables'),
('Aluminium armoured cable','electrical-lighting','electrical-lighting--power-cables'),
('Aluminium non-armoured cable','electrical-lighting','electrical-lighting--power-cables'),
('Copper XLPE cable','electrical-lighting','electrical-lighting--power-cables'),
('Aluminium XLPE cable','electrical-lighting','electrical-lighting--power-cables'),
('Copper PVC cable','electrical-lighting','electrical-lighting--power-cables'),
('Aluminium PVC cable','electrical-lighting','electrical-lighting--power-cables'),
('Flexible copper cable','electrical-lighting','electrical-lighting--power-cables'),
('Multicore copper cable','electrical-lighting','electrical-lighting--power-cables'),
('Single-core wire','electrical-lighting','electrical-lighting--wiring'),
('Twin-core cable','electrical-lighting','electrical-lighting--wiring'),
('Twin-and-earth cable','electrical-lighting','electrical-lighting--wiring'),
('Three-core cable','electrical-lighting','electrical-lighting--wiring'),
('Four-core cable','electrical-lighting','electrical-lighting--wiring'),
('Earth cable','electrical-lighting','electrical-lighting--wiring'),
('Control cable','electrical-lighting','electrical-lighting--wiring'),
('Instrumentation cable','electrical-lighting','electrical-lighting--wiring'),
('Fire-resistant cable','electrical-lighting','electrical-lighting--wiring'),
('Fire-alarm cable','electrical-lighting','electrical-lighting--wiring'),
('CAT5e cable','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('CAT6 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('CAT6A cable','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('CAT7 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('Coaxial cable','electrical-lighting','electrical-lighting--data-cables'),
('Telephone cable','electrical-lighting','electrical-lighting--data-cables'),
('Alarm cable','electrical-lighting','electrical-lighting--data-cables'),
('Intercom cable','electrical-lighting','electrical-lighting--data-cables'),
('Speaker cable','electrical-lighting','electrical-lighting--data-cables'),
('Fibre optic cable','electrical-lighting','electrical-lighting--data-cables'),
('PVC conduit','electrical-lighting','electrical-lighting--conduit'),
('Flexible conduit','electrical-lighting','electrical-lighting--conduit'),
('GI conduit','electrical-lighting','electrical-lighting--conduit'),
('Cable tray','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Cable ladder','electrical-lighting','electrical-lighting--conduit'),
('Cable duct','electrical-lighting','electrical-lighting--conduit'),
('Conduit bend','electrical-lighting','electrical-lighting--conduit'),
('Conduit box','electrical-lighting','electrical-lighting--conduit'),
('Cable ducting','electrical-lighting','electrical-lighting--conduit'),
('MCB','electrical-lighting','electrical-lighting--switchgear'),
('MCCB','electrical-lighting','electrical-lighting--switchgear'),
('RCCB','electrical-lighting','electrical-lighting--switchgear'),
('ACB','electrical-lighting','electrical-lighting--switchgear'),
('Changeover switch','electrical-lighting','electrical-lighting--switchgear'),
('Contactor','electrical-lighting','electrical-lighting--switchgear'),
('Overload relay','electrical-lighting','electrical-lighting--switchgear'),
('Distribution board','electrical-lighting','electrical-lighting--distribution'),
('Cable gland','electrical-lighting','electrical-lighting--distribution'),
('Cable lug','electrical-lighting','electrical-lighting--distribution'),
('LED bulb','electrical-lighting','electrical-lighting--lighting'),
('LED downlight','electrical-lighting','electrical-lighting--lighting'),
('LED floodlight','electrical-lighting','electrical-lighting--lighting'),
('Street light','electrical-lighting','electrical-lighting--lighting'),
('High-bay light','electrical-lighting','electrical-lighting--lighting'),
('Emergency light','electrical-lighting','electrical-lighting--lighting'),
('Bulkhead light','electrical-lighting','electrical-lighting--lighting'),
('Industrial light','electrical-lighting','electrical-lighting--lighting'),
('Modular switch','electrical-lighting','electrical-lighting--switches-and-sockets'),
('Socket outlet','electrical-lighting','electrical-lighting--switches-and-sockets'),
('USB socket','electrical-lighting','electrical-lighting--switches-and-sockets'),
('Industrial socket','electrical-lighting','electrical-lighting--switches-and-sockets'),
('Weatherproof socket','electrical-lighting','electrical-lighting--switches-and-sockets'),
('Dimmer switch','electrical-lighting','electrical-lighting--switches-and-sockets'),
('Isolator switch','electrical-lighting','electrical-lighting--switches-and-sockets'),
('Ceiling fan','electrical-lighting','electrical-lighting--fans'),
('Fan controller','electrical-lighting','electrical-lighting--fans'),
('Copper earth cable','electrical-lighting','electrical-lighting--earthing'),
('Bare copper wire','electrical-lighting','electrical-lighting--earthing'),
('Earth clamp','electrical-lighting','electrical-lighting--earthing'),
('Lightning arrester','electrical-lighting','electrical-lighting--earthing'),
('Surge protector','electrical-lighting','electrical-lighting--earthing'),
('Limit switch','electrical-lighting','electrical-lighting--automation'),
('Timer relay','electrical-lighting','electrical-lighting--automation'),
('Counter relay','electrical-lighting','electrical-lighting--automation'),
('Motor controller','other-industrial-supplies','other-industrial-supplies--motors-and-electrical'),
('Safety relay','electrical-lighting','electrical-lighting--automation'),
('Explosion-proof motor','electrical-lighting','electrical-lighting--motors'),
('Pump motor','electrical-lighting','electrical-lighting--motors'),
('Distribution transformer','electrical-lighting','electrical-lighting--transformers'),
('Lighting transformer','electrical-lighting','electrical-lighting--transformers'),
('Cable tie','electrical-lighting','electrical-lighting--electrical-accessories'),
('Cable marker','electrical-lighting','electrical-lighting--electrical-accessories'),
('Cable cleat','electrical-lighting','electrical-lighting--electrical-accessories'),
('Cable ferrule','electrical-lighting','electrical-lighting--electrical-accessories'),
('Wire duct','electrical-lighting','electrical-lighting--electrical-accessories'),
('Installation system — Copper armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Copper non-armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Aluminium armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Aluminium non-armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Copper XLPE cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Aluminium XLPE cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Copper PVC cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Aluminium PVC cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Flexible copper cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Multicore copper cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Single-core wire','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Twin-core cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Twin-and-earth cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Three-core cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Four-core cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Earth cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Control cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Instrumentation cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Fire-resistant cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Fire-alarm cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — CAT5e cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — CAT6 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — CAT6A cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — CAT7 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Coaxial cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Telephone cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Alarm cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Intercom cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Speaker cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Fibre optic cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — PVC conduit','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Flexible conduit','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — GI conduit','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable tray','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Cable ladder','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable duct','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Conduit bend','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Conduit box','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable ducting','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — MCB','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — MCCB','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — RCCB','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — ACB','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Changeover switch','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Contactor','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Overload relay','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Distribution board','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable gland','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable lug','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — LED bulb','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — LED downlight','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — LED floodlight','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Street light','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — High-bay light','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Emergency light','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Bulkhead light','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Industrial light','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Modular switch','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Socket outlet','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — USB socket','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Industrial socket','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Weatherproof socket','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Dimmer switch','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Isolator switch','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Ceiling fan','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Fan controller','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Copper earth cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Bare copper wire','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Earth clamp','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Lightning arrester','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Surge protector','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Limit switch','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Timer relay','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Counter relay','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Motor controller','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Safety relay','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Explosion-proof motor','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Pump motor','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Distribution transformer','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Lighting transformer','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable tie','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable marker','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable cleat','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Cable ferrule','electrical-lighting','electrical-lighting--expanded-product-families'),
('Installation system — Wire duct','electrical-lighting','electrical-lighting--expanded-product-families'),
('Replacement component — Copper armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Replacement component — Copper non-armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Replacement component — Aluminium armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Replacement component — Aluminium non-armoured cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Replacement component — Copper XLPE cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Replacement component — Aluminium XLPE cable','electrical-lighting','electrical-lighting--expanded-product-families'),
('Desktop computer','electronics','electronics--equipment'),
('Laptop','ict-and-telecom-equipment','ict-and-telecom-equipment--vehicles-core'),
('Tablet','ict-and-telecom-equipment','ict-and-telecom-equipment--vehicles-core'),
('Monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--equipment'),
('Keyboard','electronics','electronics--equipment'),
('Mouse','electronics','electronics--equipment'),
('Wi-Fi router','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('4G router','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('5G router','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('Network switch','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('PoE switch','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Wireless access point','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Network adapter','electronics','electronics--consumables'),
('Network rack','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Network cabinet','electronics','electronics--consumables'),
('CCTV monitor','electronics','electronics--components'),
('Microphone','electronics','electronics--installation'),
('Wireless microphone','electronics','electronics--installation'),
('Digital signage display','ict-and-telecom-equipment','ict-and-telecom-equipment--equipment'),
('LED display','electronics','electronics--protection'),
('Interactive display','ict-and-telecom-equipment','ict-and-telecom-equipment--equipment'),
('Digital kiosk','electronics','electronics--maintenance'),
('Queue display','electronics','electronics--maintenance'),
('Display controller','electronics','electronics--maintenance'),
('Installation system — Desktop computer','electronics','electronics--expanded-product-families'),
('Installation system — Laptop','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Tablet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Keyboard','electronics','electronics--expanded-product-families'),
('Installation system — Mouse','electronics','electronics--expanded-product-families'),
('Installation system — Wi-Fi router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — 4G router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — 5G router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Network switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — PoE switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Wireless access point','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Network adapter','electronics','electronics--expanded-product-families'),
('Installation system — Network rack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Network cabinet','electronics','electronics--expanded-product-families'),
('Installation system — CCTV monitor','electronics','electronics--expanded-product-families'),
('Installation system — Microphone','electronics','electronics--expanded-product-families'),
('Installation system — Wireless microphone','electronics','electronics--expanded-product-families'),
('Installation system — Digital signage display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — LED display','electronics','electronics--expanded-product-families'),
('Installation system — Interactive display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Digital kiosk','electronics','electronics--expanded-product-families'),
('Installation system — Queue display','electronics','electronics--expanded-product-families'),
('Installation system — Display controller','electronics','electronics--expanded-product-families'),
('Replacement component — Desktop computer','electronics','electronics--expanded-product-families'),
('Replacement component — Laptop','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Tablet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Keyboard','electronics','electronics--expanded-product-families'),
('Replacement component — Mouse','electronics','electronics--expanded-product-families'),
('Replacement component — Wi-Fi router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — 4G router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — 5G router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Network switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — PoE switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Wireless access point','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Network adapter','electronics','electronics--expanded-product-families'),
('Replacement component — Network rack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Network cabinet','electronics','electronics--expanded-product-families'),
('Replacement component — CCTV monitor','electronics','electronics--expanded-product-families'),
('Replacement component — Microphone','electronics','electronics--expanded-product-families'),
('Replacement component — Wireless microphone','electronics','electronics--expanded-product-families'),
('Replacement component — Digital signage display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — LED display','electronics','electronics--expanded-product-families'),
('Replacement component — Interactive display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Digital kiosk','electronics','electronics--expanded-product-families'),
('Replacement component — Queue display','electronics','electronics--expanded-product-families'),
('Replacement component — Display controller','electronics','electronics--expanded-product-families'),
('Service equipment — Desktop computer','electronics','electronics--expanded-product-families'),
('Service equipment — Laptop','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Tablet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Keyboard','electronics','electronics--expanded-product-families'),
('Service equipment — Mouse','electronics','electronics--expanded-product-families'),
('Service equipment — Wi-Fi router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — 4G router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — 5G router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Network switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — PoE switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Wireless access point','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Network adapter','electronics','electronics--expanded-product-families'),
('Service equipment — Network rack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Network cabinet','electronics','electronics--expanded-product-families'),
('Service equipment — CCTV monitor','electronics','electronics--expanded-product-families'),
('Service equipment — Microphone','electronics','electronics--expanded-product-families'),
('Service equipment — Wireless microphone','electronics','electronics--expanded-product-families'),
('Service equipment — Digital signage display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — LED display','electronics','electronics--expanded-product-families'),
('Service equipment — Interactive display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Digital kiosk','electronics','electronics--expanded-product-families'),
('Service equipment — Queue display','electronics','electronics--expanded-product-families'),
('Service equipment — Display controller','electronics','electronics--expanded-product-families'),
('Testing equipment — Desktop computer','electronics','electronics--expanded-product-families'),
('Testing equipment — Laptop','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Tablet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Keyboard','electronics','electronics--expanded-product-families'),
('Testing equipment — Mouse','electronics','electronics--expanded-product-families'),
('Testing equipment — Wi-Fi router','electronics','electronics--expanded-product-families'),
('Testing equipment — 4G router','electronics','electronics--expanded-product-families'),
('Testing equipment — 5G router','electronics','electronics--expanded-product-families'),
('Testing equipment — Network switch','electronics','electronics--expanded-product-families'),
('Testing equipment — PoE switch','electronics','electronics--expanded-product-families'),
('Testing equipment — Wireless access point','electronics','electronics--expanded-product-families'),
('Testing equipment — Network adapter','electronics','electronics--expanded-product-families'),
('Testing equipment — Network rack','electronics','electronics--expanded-product-families'),
('Monocrystalline solar panel','solar-power','solar-power--core-products'),
('Polycrystalline solar panel','solar-power','solar-power--core-products'),
('Bifacial solar panel','solar-power','solar-power--core-products'),
('Flexible solar panel','solar-power','solar-power--core-products'),
('Portable solar panel','solar-power','solar-power--core-products'),
('Solar mounting rail','solar-power','solar-power--core-products'),
('Solar mounting clamp','solar-power','solar-power--core-products'),
('Solar roof hook','solar-power','solar-power--core-products'),
('Solar grounding clip','solar-power','solar-power--core-products'),
('Solar connector','solar-power','solar-power--core-products'),
('Grid-tied inverter','solar-power','solar-power--components'),
('Off-grid inverter','solar-power','solar-power--components'),
('Hybrid inverter','solar-power','solar-power--components'),
('Microinverter','solar-power','solar-power--components'),
('String inverter','solar-power','solar-power--components'),
('Central inverter','solar-power','solar-power--components'),
('Solar pump inverter','solar-power','solar-power--components'),
('Inverter combiner','solar-power','solar-power--components'),
('Inverter monitoring unit','solar-power','solar-power--components'),
('Inverter gateway','solar-power','solar-power--components'),
('Lead-acid solar battery','solar-power','solar-power--equipment'),
('Tubular battery','solar-power','solar-power--equipment'),
('AGM battery','solar-power','solar-power--equipment'),
('Gel battery','solar-power','solar-power--equipment'),
('Lithium battery','solar-power','solar-power--equipment'),
('LiFePO4 battery','solar-power','solar-power--equipment'),
('Battery rack','solar-power','solar-power--equipment'),
('Battery cabinet','solar-power','solar-power--equipment'),
('Battery monitor','solar-power','solar-power--equipment'),
('Battery balancer','solar-power','solar-power--equipment'),
('DC breaker','solar-power','solar-power--consumables'),
('AC breaker','solar-power','solar-power--consumables'),
('Surge protection device','solar-power','solar-power--consumables'),
('DC combiner box','solar-power','solar-power--consumables'),
('AC combiner box','solar-power','solar-power--consumables'),
('Solar earthing kit','solar-power','solar-power--consumables'),
('Solar lightning protection','solar-power','solar-power--consumables'),
('PV cable','solar-power','solar-power--installation'),
('Solar extension cable','solar-power','solar-power--installation'),
('MC4 connector','solar-power','solar-power--installation'),
('MC4 branch connector','solar-power','solar-power--installation'),
('Solar cable gland','solar-power','solar-power--installation'),
('Solar junction box','solar-power','solar-power--installation'),
('Solar wire clips','solar-power','solar-power--installation'),
('Solar conduit','solar-power','solar-power--installation'),
('Solar cable tray','solar-power','solar-power--installation'),
('Solar cable marker','solar-power','solar-power--installation'),
('Solar street light','solar-power','solar-power--maintenance'),
('Solar floodlight','solar-power','solar-power--maintenance'),
('Solar security light','solar-power','solar-power--maintenance'),
('Solar garden light','solar-power','solar-power--maintenance'),
('Solar wall light','solar-power','solar-power--maintenance'),
('Solar lantern','solar-power','solar-power--maintenance'),
('Solar area light','solar-power','solar-power--maintenance'),
('Solar traffic light','solar-power','solar-power--maintenance'),
('Solar pathway light','solar-power','solar-power--maintenance'),
('Solar billboard light','solar-power','solar-power--maintenance'),
('Solar water pump','solar-power','solar-power--control'),
('Solar borehole pump','solar-power','solar-power--control'),
('Solar surface pump','solar-power','solar-power--control'),
('Solar irrigation pump','solar-power','solar-power--control'),
('Solar water heater','solar-power','solar-power--control'),
('Solar geyser','solar-power','solar-power--control'),
('Solar collector','solar-power','solar-power--control'),
('Solar circulation pump','solar-power','solar-power--control'),
('Solar pump controller','solar-power','solar-power--control'),
('Inverter generator','solar-power','solar-power--protection'),
('Standby generator','solar-power','solar-power--protection'),
('Generator controller','solar-power','solar-power--protection'),
('Automatic transfer switch','solar-power','solar-power--protection'),
('Battery charger','solar-power','solar-power--processing'),
('Power distribution unit','solar-power','solar-power--processing'),
('Installation system — Monocrystalline solar panel','solar-power','solar-power--expanded-product-families'),
('Installation system — Polycrystalline solar panel','solar-power','solar-power--expanded-product-families'),
('Installation system — Bifacial solar panel','solar-power','solar-power--expanded-product-families'),
('Installation system — Flexible solar panel','solar-power','solar-power--expanded-product-families'),
('Installation system — Portable solar panel','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar mounting rail','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar mounting clamp','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar roof hook','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar grounding clip','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar connector','solar-power','solar-power--expanded-product-families'),
('Installation system — Grid-tied inverter','solar-power','solar-power--expanded-product-families'),
('Installation system — Off-grid inverter','solar-power','solar-power--expanded-product-families'),
('Installation system — Hybrid inverter','solar-power','solar-power--expanded-product-families'),
('Installation system — Microinverter','solar-power','solar-power--expanded-product-families'),
('Installation system — String inverter','solar-power','solar-power--expanded-product-families'),
('Installation system — Central inverter','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar pump inverter','solar-power','solar-power--expanded-product-families'),
('Installation system — Inverter combiner','solar-power','solar-power--expanded-product-families'),
('Installation system — Inverter monitoring unit','solar-power','solar-power--expanded-product-families'),
('Installation system — Inverter gateway','solar-power','solar-power--expanded-product-families'),
('Installation system — Lead-acid solar battery','solar-power','solar-power--expanded-product-families'),
('Installation system — Tubular battery','solar-power','solar-power--expanded-product-families'),
('Installation system — AGM battery','solar-power','solar-power--expanded-product-families'),
('Installation system — Gel battery','solar-power','solar-power--expanded-product-families'),
('Installation system — Lithium battery','solar-power','solar-power--expanded-product-families'),
('Installation system — LiFePO4 battery','solar-power','solar-power--expanded-product-families'),
('Installation system — Battery rack','solar-power','solar-power--expanded-product-families'),
('Installation system — Battery cabinet','solar-power','solar-power--expanded-product-families'),
('Installation system — Battery monitor','solar-power','solar-power--expanded-product-families'),
('Installation system — Battery balancer','solar-power','solar-power--expanded-product-families'),
('Installation system — DC breaker','solar-power','solar-power--expanded-product-families'),
('Installation system — AC breaker','solar-power','solar-power--expanded-product-families'),
('Installation system — Surge protection device','solar-power','solar-power--expanded-product-families'),
('Installation system — DC combiner box','solar-power','solar-power--expanded-product-families'),
('Installation system — AC combiner box','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar earthing kit','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar lightning protection','solar-power','solar-power--expanded-product-families'),
('Installation system — PV cable','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar extension cable','solar-power','solar-power--expanded-product-families'),
('Installation system — MC4 connector','solar-power','solar-power--expanded-product-families'),
('Installation system — MC4 branch connector','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar cable gland','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar junction box','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar wire clips','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar conduit','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar cable tray','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar cable marker','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar street light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar floodlight','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar security light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar garden light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar wall light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar lantern','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar area light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar traffic light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar pathway light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar billboard light','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar water pump','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar borehole pump','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar surface pump','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar irrigation pump','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar water heater','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar geyser','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar collector','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar circulation pump','solar-power','solar-power--expanded-product-families'),
('Installation system — Solar pump controller','solar-power','solar-power--expanded-product-families'),
('Installation system — Inverter generator','solar-power','solar-power--expanded-product-families'),
('Installation system — Standby generator','solar-power','solar-power--expanded-product-families'),
('Installation system — Generator controller','solar-power','solar-power--expanded-product-families'),
('Installation system — Automatic transfer switch','solar-power','solar-power--expanded-product-families'),
('Installation system — Battery charger','solar-power','solar-power--expanded-product-families'),
('Installation system — Power distribution unit','solar-power','solar-power--expanded-product-families'),
('Replacement component — Monocrystalline solar panel','solar-power','solar-power--expanded-product-families'),
('Replacement component — Polycrystalline solar panel','solar-power','solar-power--expanded-product-families'),
('Replacement component — Bifacial solar panel','solar-power','solar-power--expanded-product-families'),
('Replacement component — Flexible solar panel','solar-power','solar-power--expanded-product-families'),
('Replacement component — Portable solar panel','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar mounting rail','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar mounting clamp','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar roof hook','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar grounding clip','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar connector','solar-power','solar-power--expanded-product-families'),
('Replacement component — Grid-tied inverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — Off-grid inverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — Hybrid inverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — Microinverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — String inverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — Central inverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar pump inverter','solar-power','solar-power--expanded-product-families'),
('Replacement component — Inverter combiner','solar-power','solar-power--expanded-product-families'),
('Replacement component — Inverter monitoring unit','solar-power','solar-power--expanded-product-families'),
('Replacement component — Inverter gateway','solar-power','solar-power--expanded-product-families'),
('Replacement component — Lead-acid solar battery','solar-power','solar-power--expanded-product-families'),
('Replacement component — Tubular battery','solar-power','solar-power--expanded-product-families'),
('Replacement component — AGM battery','solar-power','solar-power--expanded-product-families'),
('Replacement component — Gel battery','solar-power','solar-power--expanded-product-families'),
('Replacement component — Lithium battery','solar-power','solar-power--expanded-product-families'),
('Replacement component — LiFePO4 battery','solar-power','solar-power--expanded-product-families'),
('Replacement component — Battery rack','solar-power','solar-power--expanded-product-families'),
('Replacement component — Battery cabinet','solar-power','solar-power--expanded-product-families'),
('Replacement component — Battery monitor','solar-power','solar-power--expanded-product-families'),
('Replacement component — Battery balancer','solar-power','solar-power--expanded-product-families'),
('Replacement component — DC breaker','solar-power','solar-power--expanded-product-families'),
('Replacement component — AC breaker','solar-power','solar-power--expanded-product-families'),
('Replacement component — Surge protection device','solar-power','solar-power--expanded-product-families'),
('Replacement component — DC combiner box','solar-power','solar-power--expanded-product-families'),
('Replacement component — AC combiner box','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar earthing kit','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar lightning protection','solar-power','solar-power--expanded-product-families'),
('Replacement component — PV cable','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar extension cable','solar-power','solar-power--expanded-product-families'),
('Replacement component — MC4 connector','solar-power','solar-power--expanded-product-families'),
('Replacement component — MC4 branch connector','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar cable gland','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar junction box','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar wire clips','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar conduit','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar cable tray','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar cable marker','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar street light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar floodlight','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar security light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar garden light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar wall light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar lantern','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar area light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar traffic light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar pathway light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar billboard light','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar water pump','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar borehole pump','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar surface pump','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar irrigation pump','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar water heater','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar geyser','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar collector','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar circulation pump','solar-power','solar-power--expanded-product-families'),
('Replacement component — Solar pump controller','solar-power','solar-power--expanded-product-families'),
('Replacement component — Inverter generator','solar-power','solar-power--expanded-product-families'),
('Replacement component — Standby generator','solar-power','solar-power--expanded-product-families'),
('Replacement component — Generator controller','solar-power','solar-power--expanded-product-families'),
('Replacement component — Automatic transfer switch','solar-power','solar-power--expanded-product-families'),
('Replacement component — Battery charger','solar-power','solar-power--expanded-product-families'),
('Replacement component — Power distribution unit','solar-power','solar-power--expanded-product-families'),
('Service equipment — Monocrystalline solar panel','solar-power','solar-power--expanded-product-families'),
('Service equipment — Polycrystalline solar panel','solar-power','solar-power--expanded-product-families'),
('Service equipment — Bifacial solar panel','solar-power','solar-power--expanded-product-families'),
('Service equipment — Flexible solar panel','solar-power','solar-power--expanded-product-families'),
('Service equipment — Portable solar panel','solar-power','solar-power--expanded-product-families'),
('Service equipment — Solar mounting rail','solar-power','solar-power--expanded-product-families'),
('Service equipment — Solar mounting clamp','solar-power','solar-power--expanded-product-families'),
('Service equipment — Solar roof hook','solar-power','solar-power--expanded-product-families'),
('Service equipment — Solar grounding clip','solar-power','solar-power--expanded-product-families'),
('Service equipment — Solar connector','solar-power','solar-power--expanded-product-families'),
('Service equipment — Grid-tied inverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — Off-grid inverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — Hybrid inverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — Microinverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — String inverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — Central inverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — Solar pump inverter','solar-power','solar-power--expanded-product-families'),
('Service equipment — Inverter combiner','solar-power','solar-power--expanded-product-families'),
('Service equipment — Inverter monitoring unit','solar-power','solar-power--expanded-product-families'),
('Service equipment — Inverter gateway','solar-power','solar-power--expanded-product-families'),
('Service equipment — Lead-acid solar battery','solar-power','solar-power--expanded-product-families'),
('Service equipment — Tubular battery','solar-power','solar-power--expanded-product-families'),
('Service equipment — AGM battery','solar-power','solar-power--expanded-product-families'),
('Service equipment — Gel battery','solar-power','solar-power--expanded-product-families'),
('Service equipment — Lithium battery','solar-power','solar-power--expanded-product-families'),
('Service equipment — LiFePO4 battery','solar-power','solar-power--expanded-product-families'),
('Service equipment — Battery rack','solar-power','solar-power--expanded-product-families'),
('Service equipment — Battery cabinet','solar-power','solar-power--expanded-product-families'),
('Service equipment — Battery monitor','solar-power','solar-power--expanded-product-families'),
('Service equipment — Battery balancer','solar-power','solar-power--expanded-product-families'),
('PVC water pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('HDPE water pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('PPR pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('CPVC pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('PEX pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('Copper pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('Multilayer pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('uPVC pressure pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('uPVC sewer pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('HDPE drainage pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Corrugated drain pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Perforated drain pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Soil pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Waste pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Rainwater pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Flexible drain pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Underground drain pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('PVC elbow','plumbing-sanitary','plumbing-sanitary--fittings'),
('PVC tee','plumbing-sanitary','plumbing-sanitary--fittings'),
('PVC coupler','plumbing-sanitary','plumbing-sanitary--fittings'),
('PVC reducer','plumbing-sanitary','plumbing-sanitary--fittings'),
('PPR elbow','plumbing-sanitary','plumbing-sanitary--fittings'),
('PPR tee','plumbing-sanitary','plumbing-sanitary--fittings'),
('PPR coupler','plumbing-sanitary','plumbing-sanitary--fittings'),
('HDPE fitting','plumbing-sanitary','plumbing-sanitary--fittings'),
('GI elbow','plumbing-sanitary','plumbing-sanitary--fittings'),
('GI tee','plumbing-sanitary','plumbing-sanitary--fittings'),
('Ball valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Gate valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Globe valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Check valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Butterfly valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Float valve','plumbing-sanitary','plumbing-sanitary--valves'),
('Pressure reducing valve','plumbing-sanitary','plumbing-sanitary--valves'),
('Foot valve','plumbing-sanitary','plumbing-sanitary--valves'),
('Needle valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Solenoid valve','other-industrial-supplies','other-industrial-supplies--pneumatics'),
('Pipe clamp','plumbing-sanitary','plumbing-sanitary--pipe-accessories'),
('Pipe support','plumbing-sanitary','plumbing-sanitary--pipe-accessories'),
('Pipe insulation','plumbing-sanitary','plumbing-sanitary--pipe-accessories'),
('Thread seal tape','plumbing-sanitary','plumbing-sanitary--pipe-accessories'),
('Pipe repair clamp','plumbing-sanitary','plumbing-sanitary--pipe-accessories'),
('Pipe saddle','plumbing-sanitary','plumbing-sanitary--pipe-accessories'),
('WC suite','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Wall-hung toilet','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Wash basin','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Pedestal basin','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Countertop basin','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Squatting pan','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Cistern','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Toilet seat','plumbing-sanitary','plumbing-sanitary--sanitaryware'),
('Shower set','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Shower mixer','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Basin mixer','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Kitchen tap','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Angle valve','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Floor drain','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Hand shower','plumbing-sanitary','plumbing-sanitary--bathroom-fittings'),
('Kitchen sink','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Double bowl sink','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Single bowl sink','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Sink mixer','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Sink waste','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Dishwasher hose','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Sink strainer','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Sink trap','plumbing-sanitary','plumbing-sanitary--kitchen-plumbing'),
('Pressed steel tank','plumbing-sanitary','plumbing-sanitary--water-tanks'),
('Water pump','auto-parts','auto-parts--core-products'),
('Submersible pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Borehole pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Booster pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Pressure pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Drainage pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Sewage pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Circulation pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Transfer pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Dosing pump','plumbing-sanitary','plumbing-sanitary--pumps'),
('Sewer backflow valve','plumbing-sanitary','plumbing-sanitary--sewerage'),
('Pipe deburring tool','plumbing-sanitary','plumbing-sanitary--plumbing-tools'),
('Linear drain','plumbing-sanitary','plumbing-sanitary--fixtures'),
('Shower channel','plumbing-sanitary','plumbing-sanitary--fixtures'),
('Shower tray','plumbing-sanitary','plumbing-sanitary--fixtures'),
('Toilet brush holder','plumbing-sanitary','plumbing-sanitary--fixtures'),
('Installation system — PVC water pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — HDPE water pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PPR pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — CPVC pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PEX pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Copper pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Multilayer pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — uPVC pressure pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — uPVC sewer pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — HDPE drainage pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Corrugated drain pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Perforated drain pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Soil pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Waste pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Rainwater pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Flexible drain pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Underground drain pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PVC elbow','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PVC tee','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PVC coupler','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PVC reducer','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PPR elbow','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PPR tee','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — PPR coupler','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — HDPE fitting','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — GI elbow','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — GI tee','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Ball valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Gate valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Globe valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Check valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Butterfly valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Float valve','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pressure reducing valve','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Foot valve','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Needle valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Solenoid valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Pipe clamp','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pipe support','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pipe insulation','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Thread seal tape','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pipe repair clamp','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pipe saddle','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — WC suite','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Wall-hung toilet','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Wash basin','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pedestal basin','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Countertop basin','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Squatting pan','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Cistern','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Toilet seat','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Shower set','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Shower mixer','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Basin mixer','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Kitchen tap','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Angle valve','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Floor drain','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Hand shower','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Kitchen sink','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Double bowl sink','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Single bowl sink','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Sink mixer','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Sink waste','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Dishwasher hose','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Sink strainer','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Sink trap','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pressed steel tank','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Water pump','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Submersible pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Borehole pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Booster pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pressure pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Drainage pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Sewage pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Circulation pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Transfer pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Dosing pump','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Sewer backflow valve','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pipe deburring tool','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Linear drain','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Shower channel','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Shower tray','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Toilet brush holder','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Replacement component — PVC water pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Replacement component — HDPE water pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Replacement component — PPR pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Replacement component — CPVC pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Weatherproof paint','paints-finishes','paints-finishes--core-products'),
('Masonry paint','paints-finishes','paints-finishes--core-products'),
('Acrylic paint','paints-finishes','paints-finishes--core-products'),
('Textured paint','paints-finishes','paints-finishes--core-products'),
('Silicate paint','paints-finishes','paints-finishes--core-products'),
('Lime paint','paints-finishes','paints-finishes--core-products'),
('Washable paint','paints-finishes','paints-finishes--core-products'),
('Anti-mould paint','paints-finishes','paints-finishes--core-products'),
('Wall primer','paints-finishes','paints-finishes--components'),
('Acrylic primer','paints-finishes','paints-finishes--components')
on conflict (n) do update set m = excluded.m, s = excluded.s;
