-- 0065 part 2 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('C25 concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('C30 concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('C35 concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('C40 concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('Pumpable concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('Self-compacting concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('Lean concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('Mass concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('Building sand','cement-aggregates','cement-aggregates--sand'),
('Plaster sand','cement-aggregates','cement-aggregates--sand'),
('River sand','cement-aggregates','cement-aggregates--sand'),
('Lake sand','cement-aggregates','cement-aggregates--sand'),
('Washed sand','cement-aggregates','cement-aggregates--sand'),
('Fine sand','cement-aggregates','cement-aggregates--sand'),
('Coarse sand','cement-aggregates','cement-aggregates--sand'),
('Masonry sand','cement-aggregates','cement-aggregates--sand'),
('Concrete sand','cement-aggregates','cement-aggregates--sand'),
('Fill sand','cement-aggregates','cement-aggregates--sand'),
('10mm aggregate','cement-aggregates','cement-aggregates--aggregates'),
('14mm aggregate','cement-aggregates','cement-aggregates--aggregates'),
('20mm aggregate','cement-aggregates','cement-aggregates--aggregates'),
('25mm aggregate','cement-aggregates','cement-aggregates--aggregates'),
('40mm aggregate','cement-aggregates','cement-aggregates--aggregates'),
('Crushed stone','cement-aggregates','cement-aggregates--aggregates'),
('Stone dust','cement-aggregates','cement-aggregates--aggregates'),
('Quarry dust','cement-aggregates','cement-aggregates--aggregates'),
('Gravel','cement-aggregates','cement-aggregates--aggregates'),
('Ballast','cement-aggregates','cement-aggregates--aggregates'),
('Base-course aggregate','cement-aggregates','cement-aggregates--road-aggregates'),
('Sub-base aggregate','cement-aggregates','cement-aggregates--road-aggregates'),
('Crusher run','cement-aggregates','cement-aggregates--road-aggregates'),
('G5 material','cement-aggregates','cement-aggregates--road-aggregates'),
('G7 material','cement-aggregates','cement-aggregates--road-aggregates'),
('Shoulder gravel','cement-aggregates','cement-aggregates--road-aggregates'),
('Road stone','cement-aggregates','cement-aggregates--road-aggregates'),
('Drainage stone','cement-aggregates','cement-aggregates--road-aggregates'),
('Gabion stone','cement-aggregates','cement-aggregates--road-aggregates'),
('Riprap','cement-aggregates','cement-aggregates--road-aggregates'),
('Lightweight aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Recycled aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Decorative aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Granite aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Basalt aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Limestone aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Quartz aggregate','cement-aggregates','cement-aggregates--specialty-aggregates'),
('River gravel','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Pea gravel','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Filter gravel','cement-aggregates','cement-aggregates--specialty-aggregates'),
('Plasticizer','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Superplasticizer','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Accelerator','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Retarder','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Air entrainer','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Water reducer','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Shrinkage reducer','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Corrosion inhibitor','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Bonding admixture','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Curing compound','cement-aggregates','cement-aggregates--concrete-admixtures'),
('Lime putty','cement-aggregates','cement-aggregates--lime'),
('Lime mortar','cement-aggregates','cement-aggregates--lime'),
('Dry mortar','cement-aggregates','cement-aggregates--mortars'),
('Plaster mortar','cement-aggregates','cement-aggregates--mortars'),
('Screed mortar','cement-aggregates','cement-aggregates--mortars'),
('Tile grout','cement-aggregates','cement-aggregates--mortars'),
('Anchoring grout','cement-aggregates','cement-aggregates--mortars'),
('Repair mortar','cement-aggregates','cement-aggregates--mortars'),
('Flowable grout','cement-aggregates','cement-aggregates--mortars'),
('Concrete block','cement-aggregates','cement-aggregates--precast'),
('Concrete lintel','cement-aggregates','cement-aggregates--precast'),
('Concrete beam','cement-aggregates','cement-aggregates--precast'),
('Concrete column','cement-aggregates','cement-aggregates--precast'),
('Concrete slab','cement-aggregates','cement-aggregates--precast'),
('Concrete kerb','cement-aggregates','cement-aggregates--precast'),
('Concrete manhole','cement-aggregates','cement-aggregates--precast'),
('Concrete cover','cement-aggregates','cement-aggregates--precast'),
('Concrete bollard','cement-aggregates','cement-aggregates--precast'),
('Concrete cube mould','cement-aggregates','cement-aggregates--testing'),
('Concrete thermometer','cement-aggregates','cement-aggregates--testing'),
('Concrete rebound hammer','cement-aggregates','cement-aggregates--testing'),
('Concrete moisture meter','cement-aggregates','cement-aggregates--testing'),
('Cement test sieve','cement-aggregates','cement-aggregates--testing'),
('Cement soundness apparatus','cement-aggregates','cement-aggregates--testing'),
('Mortar flow table','cement-aggregates','cement-aggregates--testing'),
('Aggregate impact tester','cement-aggregates','cement-aggregates--testing'),
('Aggregate sieve set','cement-aggregates','cement-aggregates--testing'),
('Cement silo','cement-aggregates','cement-aggregates--bulk-handling'),
('Aggregate hopper','cement-aggregates','cement-aggregates--bulk-handling'),
('Concrete conveyor','cement-aggregates','cement-aggregates--bulk-handling'),
('Screw conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--service'),
('Cement screw feeder','cement-aggregates','cement-aggregates--bulk-handling'),
('Aggregate feeder','cement-aggregates','cement-aggregates--bulk-handling'),
('Cement tanker','cement-aggregates','cement-aggregates--bulk-handling'),
('Cement bag','cement-aggregates','cement-aggregates--packaging'),
('Valve sack','cement-aggregates','cement-aggregates--packaging'),
('Kraft cement bag','cement-aggregates','cement-aggregates--packaging'),
('PP cement bag','cement-aggregates','cement-aggregates--packaging'),
('Aggregate bulk bag','cement-aggregates','cement-aggregates--packaging'),
('Grout bag','cement-aggregates','cement-aggregates--packaging'),
('Mortar bag','cement-aggregates','cement-aggregates--packaging'),
('Cement test chemical','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete mould oil','cement-aggregates','cement-aggregates--quality-inputs'),
('Aggregate washing aid','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete stain remover','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete surface hardener','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete densifier','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete sealer','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete polishing compound','cement-aggregates','cement-aggregates--quality-inputs'),
('Glass aggregate','cement-aggregates','cement-aggregates--decorative-aggregates'),
('Coloured stone','cement-aggregates','cement-aggregates--decorative-aggregates'),
('River stone','cement-aggregates','cement-aggregates--decorative-aggregates'),
('Decorative gravel','cement-aggregates','cement-aggregates--decorative-aggregates'),
('Black stone chips','cement-aggregates','cement-aggregates--decorative-aggregates'),
('White stone chips','cement-aggregates','cement-aggregates--decorative-aggregates'),
('Installation system — OPC cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — PPC cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — White cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Masonry cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Rapid-hardening cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — High-strength cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Sulphate-resistant cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Low-heat cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Hydraulic cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Limestone cement','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — C15 concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — C20 concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — C25 concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — C30 concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — C35 concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — C40 concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Pumpable concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Self-compacting concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Lean concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Mass concrete','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Building sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Plaster sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — River sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Lake sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Washed sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Fine sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Coarse sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Masonry sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Fill sand','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — 10mm aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — 14mm aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — 20mm aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — 25mm aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — 40mm aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Crushed stone','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Stone dust','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Quarry dust','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Gravel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Ballast','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Base-course aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Sub-base aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Crusher run','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — G5 material','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — G7 material','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Shoulder gravel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Road stone','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Drainage stone','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Gabion stone','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Riprap','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Lightweight aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Recycled aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Decorative aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Granite aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Basalt aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Limestone aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Quartz aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — River gravel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Pea gravel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Filter gravel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Plasticizer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Superplasticizer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Accelerator','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Retarder','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Air entrainer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Water reducer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Shrinkage reducer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Corrosion inhibitor','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Bonding admixture','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Curing compound','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Lime putty','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Lime mortar','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Dry mortar','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Plaster mortar','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Screed mortar','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Tile grout','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Anchoring grout','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Repair mortar','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Flowable grout','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete block','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete lintel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete beam','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete column','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete slab','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete kerb','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete manhole','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete cover','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete bollard','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete cube mould','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete thermometer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete rebound hammer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete moisture meter','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Cement test sieve','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Cement soundness apparatus','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Mortar flow table','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Aggregate impact tester','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Aggregate sieve set','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Cement silo','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Aggregate hopper','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete conveyor','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Screw conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Cement screw feeder','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Aggregate feeder','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Cement tanker','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Cement bag','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Valve sack','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Kraft cement bag','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — PP cement bag','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Aggregate bulk bag','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Grout bag','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Mortar bag','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Cement test chemical','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete mould oil','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Aggregate washing aid','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete stain remover','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete surface hardener','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete densifier','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete sealer','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete polishing compound','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Glass aggregate','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Coloured stone','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — River stone','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Decorative gravel','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Black stone chips','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — White stone chips','cement-aggregates','cement-aggregates--expanded-product-families'),
('I-beam','steel-metal','steel-metal--structural-sections'),
('H-beam','steel-metal','steel-metal--structural-sections'),
('Universal beam','steel-metal','steel-metal--structural-sections'),
('Universal column','steel-metal','steel-metal--structural-sections'),
('Channel','steel-metal','steel-metal--structural-sections'),
('Angle','steel-metal','steel-metal--structural-sections'),
('T-section','steel-metal','steel-metal--structural-sections'),
('Z-section','steel-metal','steel-metal--structural-sections'),
('C-section','steel-metal','steel-metal--structural-sections'),
('Round bar','steel-metal','steel-metal--bars-and-rods'),
('Square bar','steel-metal','steel-metal--bars-and-rods'),
('Hex bar','steel-metal','steel-metal--bars-and-rods'),
('Flat bar','steel-metal','steel-metal--bars-and-rods'),
('Threaded bar','steel-metal','steel-metal--bars-and-rods'),
('Bright bar','steel-metal','steel-metal--bars-and-rods'),
('Spring steel bar','steel-metal','steel-metal--bars-and-rods'),
('Tool steel bar','steel-metal','steel-metal--bars-and-rods'),
('Cold-drawn bar','steel-metal','steel-metal--bars-and-rods'),
('Steel rod','steel-metal','steel-metal--bars-and-rods'),
('Mild steel sheet','steel-metal','steel-metal--sheets-and-plates'),
('Galvanized sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Stainless sheet','steel-metal','steel-metal--sheets-and-plates'),
('Steel plate','steel-metal','steel-metal--sheets-and-plates'),
('Perforated sheet','steel-metal','steel-metal--sheets-and-plates'),
('Cold-rolled sheet','steel-metal','steel-metal--sheets-and-plates'),
('Hot-rolled sheet','steel-metal','steel-metal--sheets-and-plates'),
('Color-coated sheet','steel-metal','steel-metal--sheets-and-plates'),
('Zinc sheet','steel-metal','steel-metal--sheets-and-plates'),
('Seamless pipe','steel-metal','steel-metal--pipes-and-tubes'),
('Welded pipe','steel-metal','steel-metal--pipes-and-tubes'),
('GI pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('Stainless pipe','plumbing-sanitary','plumbing-sanitary--water-pipes'),
('Black steel pipe','steel-metal','steel-metal--pipes-and-tubes'),
('Welded mesh','steel-metal','steel-metal--reinforcement'),
('Mechanical splice','steel-metal','steel-metal--reinforcement'),
('Threaded coupler','steel-metal','steel-metal--reinforcement'),
('Chain-link mesh','steel-metal','steel-metal--fencing'),
('Barbed wire','steel-metal','steel-metal--fencing'),
('Razor wire','steel-metal','steel-metal--fencing'),
('Chicken wire','steel-metal','steel-metal--fencing'),
('Expanded metal','steel-metal','steel-metal--fencing'),
('Security mesh','steel-metal','steel-metal--fencing'),
('Gabion mesh','steel-metal','steel-metal--fencing'),
('Livestock mesh','steel-metal','steel-metal--fencing'),
('Fence post','steel-metal','steel-metal--fencing'),
('Stainless wire','steel-metal','steel-metal--stainless-steel'),
('Stainless mesh','steel-metal','steel-metal--stainless-steel'),
('Stainless fitting','steel-metal','steel-metal--stainless-steel'),
('Stainless fastener','steel-metal','steel-metal--stainless-steel'),
('Aluminium sheet','steel-metal','steel-metal--aluminium'),
('Aluminium flat bar','steel-metal','steel-metal--aluminium'),
('Aluminium wire','steel-metal','steel-metal--aluminium'),
('Copper sheet','steel-metal','steel-metal--copper-and-brass'),
('Copper wire','steel-metal','steel-metal--copper-and-brass'),
('Brass sheet','steel-metal','steel-metal--copper-and-brass'),
('Brass fitting','steel-metal','steel-metal--copper-and-brass'),
('Welding wire','steel-metal','steel-metal--fabrication-consumables'),
('Solder wire','steel-metal','steel-metal--fabrication-consumables'),
('Hex bolt','steel-metal','steel-metal--metal-fasteners'),
('Hex nut','steel-metal','steel-metal--metal-fasteners'),
('Flat washer','steel-metal','steel-metal--metal-fasteners'),
('Spring washer','steel-metal','steel-metal--metal-fasteners'),
('Anchor bolt','steel-metal','steel-metal--metal-fasteners'),
('Machine screw','hardware-tools','hardware-tools--fasteners'),
('Corrugated steel sheet','steel-metal','steel-metal--roofing-steel'),
('Box profile sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('IBR sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Tile profile sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Standing seam sheet','steel-metal','steel-metal--roofing-steel'),
('Roof ridge steel','steel-metal','steel-metal--roofing-steel'),
('Roof flashing steel','steel-metal','steel-metal--roofing-steel'),
('Valley steel','steel-metal','steel-metal--roofing-steel'),
('Roof gutter steel','steel-metal','steel-metal--roofing-steel'),
('Barge steel','steel-metal','steel-metal--roofing-steel'),
('Steel drum','steel-metal','steel-metal--metal-products'),
('Steel bucket','steel-metal','steel-metal--metal-products'),
('Steel cabinet','steel-metal','steel-metal--metal-products'),
('Steel locker','steel-metal','steel-metal--metal-products'),
('Steel pallet','steel-metal','steel-metal--metal-products'),
('Steel crate','steel-metal','steel-metal--metal-products'),
('Steel tank','steel-metal','steel-metal--metal-products'),
('Steel mesh basket','steel-metal','steel-metal--metal-products'),
('Steel trolley','steel-metal','steel-metal--metal-products'),
('Steel bin','steel-metal','steel-metal--metal-products'),
('Galvanized wire','steel-metal','steel-metal--wire-products'),
('Spring wire','steel-metal','steel-metal--wire-products'),
('Tie wire','steel-metal','steel-metal--wire-products'),
('Zinc primer','steel-metal','steel-metal--surface-treatment'),
('Metal primer','paints-finishes','paints-finishes--components'),
('Installation system — I-beam','steel-metal','steel-metal--expanded-product-families'),
('Installation system — H-beam','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Universal beam','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Universal column','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Channel','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Angle','steel-metal','steel-metal--expanded-product-families'),
('Installation system — T-section','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Z-section','steel-metal','steel-metal--expanded-product-families'),
('Installation system — C-section','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Round bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Square bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Hex bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Flat bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Threaded bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Bright bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Spring steel bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Tool steel bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Cold-drawn bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel rod','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Mild steel sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Galvanized sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Stainless sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel plate','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Perforated sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Cold-rolled sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Hot-rolled sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Color-coated sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Zinc sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Seamless pipe','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Welded pipe','steel-metal','steel-metal--expanded-product-families'),
('Installation system — GI pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Stainless pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Black steel pipe','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Welded mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Mechanical splice','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Threaded coupler','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Chain-link mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Barbed wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Razor wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Chicken wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Expanded metal','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Security mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Gabion mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Livestock mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Fence post','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Stainless wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Stainless mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Stainless fitting','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Stainless fastener','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Aluminium sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Aluminium flat bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Aluminium wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Copper sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Copper wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Brass sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Brass fitting','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Welding wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Solder wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Hex bolt','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Hex nut','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Flat washer','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Spring washer','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Anchor bolt','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Machine screw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Corrugated steel sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Box profile sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — IBR sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Tile profile sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Standing seam sheet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Roof ridge steel','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Roof flashing steel','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Valley steel','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Roof gutter steel','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Barge steel','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel drum','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel bucket','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel cabinet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel locker','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel pallet','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel crate','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel tank','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel mesh basket','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel trolley','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel bin','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Galvanized wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Spring wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Tie wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Zinc primer','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Metal primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — I-beam','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — H-beam','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Universal beam','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Universal column','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Channel','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Angle','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — T-section','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Z-section','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — C-section','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Steel truss','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Round bar','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Square bar','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Hex bar','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Flat bar','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Threaded bar','steel-metal','steel-metal--expanded-product-families'),
('Replacement component — Bright bar','steel-metal','steel-metal--expanded-product-families'),
('Hammer','hardware-tools','hardware-tools--hand-tools'),
('Screwdriver','hardware-tools','hardware-tools--hand-tools'),
('Pliers','hardware-tools','hardware-tools--hand-tools'),
('Spanner','hardware-tools','hardware-tools--hand-tools'),
('Adjustable wrench','hardware-tools','hardware-tools--hand-tools'),
('Pipe wrench','plumbing-sanitary','plumbing-sanitary--plumbing-tools'),
('Allen key set','hardware-tools','hardware-tools--hand-tools'),
('Chisel','hardware-tools','hardware-tools--hand-tools'),
('Punch set','hardware-tools','hardware-tools--hand-tools'),
('Hand saw','hardware-tools','hardware-tools--hand-tools'),
('Measuring tape','hardware-tools','hardware-tools--measuring'),
('Spirit level','hardware-tools','hardware-tools--measuring'),
('Laser level','hardware-tools','hardware-tools--measuring'),
('Vernier caliper','hardware-tools','hardware-tools--measuring'),
('Micrometer','hardware-tools','hardware-tools--measuring'),
('Steel ruler','hardware-tools','hardware-tools--measuring'),
('Angle finder','hardware-tools','hardware-tools--measuring'),
('Measuring wheel','hardware-tools','hardware-tools--measuring'),
('Feeler gauge','hardware-tools','hardware-tools--measuring'),
('Bolt cutter','hardware-tools','hardware-tools--cutting'),
('Pipe cutter','hardware-tools','hardware-tools--cutting'),
('Hacksaw','hardware-tools','hardware-tools--cutting'),
('Tile cutter','hardware-tools','hardware-tools--cutting'),
('Glass cutter','hardware-tools','hardware-tools--cutting'),
('Tin snips','hardware-tools','hardware-tools--cutting'),
('Utility knife','hardware-tools','hardware-tools--cutting'),
('Cable cutter','hardware-tools','hardware-tools--cutting'),
('Rebar cutter','hardware-tools','hardware-tools--cutting'),
('Hole saw','hardware-tools','hardware-tools--cutting'),
('Electric drill','hardware-tools','hardware-tools--power-tools'),
('Hammer drill','hardware-tools','hardware-tools--power-tools'),
('Rotary hammer','hardware-tools','hardware-tools--power-tools'),
('Angle grinder','hardware-tools','hardware-tools--power-tools'),
('Bench grinder','hardware-tools','hardware-tools--power-tools'),
('Circular saw','hardware-tools','hardware-tools--power-tools'),
('Jigsaw','hardware-tools','hardware-tools--power-tools'),
('Reciprocating saw','hardware-tools','hardware-tools--power-tools'),
('Heat gun','hardware-tools','hardware-tools--power-tools'),
('Common nail','hardware-tools','hardware-tools--fasteners'),
('Masonry nail','hardware-tools','hardware-tools--fasteners'),
('Roofing nail','roofing-ceilings','roofing-ceilings--fasteners'),
('Self-tapping screw','roofing-ceilings','roofing-ceilings--fasteners'),
('Coach screw','hardware-tools','hardware-tools--fasteners'),
('Bolt','hardware-tools','hardware-tools--fasteners'),
('Nut','hardware-tools','hardware-tools--fasteners'),
('Washer','hardware-tools','hardware-tools--fasteners'),
('Chemical anchor','hardware-tools','hardware-tools--anchors'),
('Sleeve anchor','hardware-tools','hardware-tools--anchors'),
('Wedge anchor','hardware-tools','hardware-tools--anchors'),
('Drop-in anchor','hardware-tools','hardware-tools--anchors'),
('Drywall anchor','hardware-tools','hardware-tools--anchors'),
('Toggle bolt','hardware-tools','hardware-tools--anchors'),
('Anchor rod','hardware-tools','hardware-tools--anchors'),
('PVC adhesive','hardware-tools','hardware-tools--adhesives'),
('Contact adhesive','chemicals-industrial','chemicals-industrial--consumables'),
('Epoxy adhesive','hardware-tools','hardware-tools--adhesives'),
('Cyanoacrylate adhesive','chemicals-industrial','chemicals-industrial--consumables'),
('Pipe sealant','hardware-tools','hardware-tools--adhesives'),
('Silicone adhesive','hardware-tools','hardware-tools--adhesives'),
('Hot-melt adhesive','chemicals-industrial','chemicals-industrial--consumables'),
('Sanding sheet','hardware-tools','hardware-tools--abrasives'),
('Sanding belt','hardware-tools','hardware-tools--abrasives'),
('Wire wheel','hardware-tools','hardware-tools--abrasives'),
('Grinding stone','hardware-tools','hardware-tools--abrasives'),
('Tool box','hardware-tools','hardware-tools--workshop'),
('Tool bag','hardware-tools','hardware-tools--workshop'),
('Workshop stool','hardware-tools','hardware-tools--workshop'),
('Tool cabinet','other-industrial-supplies','other-industrial-supplies--workshop-equipment'),
('Secateurs','hardware-tools','hardware-tools--garden-tools'),
('Pruning saw','hardware-tools','hardware-tools--garden-tools'),
('Hedge shear','hardware-tools','hardware-tools--garden-tools'),
('Garden fork','hardware-tools','hardware-tools--garden-tools'),
('Spade','hardware-tools','hardware-tools--garden-tools'),
('Shovel','hardware-tools','hardware-tools--garden-tools'),
('Hoe','hardware-tools','hardware-tools--garden-tools'),
('Rake','hardware-tools','hardware-tools--garden-tools'),
('Hand trowel','hardware-tools','hardware-tools--garden-tools'),
('Basin wrench','plumbing-sanitary','plumbing-sanitary--plumbing-tools'),
('Tube cutter','hardware-tools','hardware-tools--plumbing-tools'),
('PEX crimper','hardware-tools','hardware-tools--plumbing-tools'),
('PPR fusion tool','hardware-tools','hardware-tools--plumbing-tools'),
('Pipe threading machine','plumbing-sanitary','plumbing-sanitary--plumbing-tools'),
('Drain auger','plumbing-sanitary','plumbing-sanitary--plumbing-tools'),
('Pipe reamer','plumbing-sanitary','plumbing-sanitary--plumbing-tools'),
('Flare tool','hardware-tools','hardware-tools--plumbing-tools'),
('Press tool','hardware-tools','hardware-tools--plumbing-tools'),
('Cable stripper','hardware-tools','hardware-tools--electrical-tools'),
('Crimping tool','hardware-tools','hardware-tools--electrical-tools'),
('Wire cutter','hardware-tools','hardware-tools--electrical-tools'),
('Multimeter','hardware-tools','hardware-tools--electrical-tools'),
('Clamp meter','hardware-tools','hardware-tools--electrical-tools'),
('Voltage tester','hardware-tools','hardware-tools--electrical-tools'),
('Insulation tester','hardware-tools','hardware-tools--electrical-tools'),
('Cable tracer','hardware-tools','hardware-tools--electrical-tools'),
('Phase tester','hardware-tools','hardware-tools--electrical-tools'),
('Terminal crimper','hardware-tools','hardware-tools--electrical-tools'),
('Brick trowel','hardware-tools','hardware-tools--masonry-tools'),
('Pointing trowel','hardware-tools','hardware-tools--masonry-tools'),
('Float','hardware-tools','hardware-tools--masonry-tools'),
('Mason''s hammer','hardware-tools','hardware-tools--masonry-tools'),
('Brick bolster','hardware-tools','hardware-tools--masonry-tools'),
('Mortar board','hardware-tools','hardware-tools--masonry-tools'),
('Plastering rule','hardware-tools','hardware-tools--masonry-tools'),
('Screeding rule','hardware-tools','hardware-tools--masonry-tools'),
('Brick jointer','hardware-tools','hardware-tools--masonry-tools'),
('Block splitter','hardware-tools','hardware-tools--masonry-tools'),
('Paint brush','paints-finishes','paints-finishes--control'),
('Paint roller','paints-finishes','paints-finishes--control'),
('Roller frame','hardware-tools','hardware-tools--painting-tools'),
('Paint tray','paints-finishes','paints-finishes--control'),
('Extension pole','hardware-tools','hardware-tools--painting-tools'),
('Spray gun','hardware-tools','hardware-tools--painting-tools'),
('Paint mixer','paints-finishes','paints-finishes--protection'),
('Paint strainer','hardware-tools','hardware-tools--painting-tools'),
('Putty knife','hardware-tools','hardware-tools--painting-tools'),
('Caulking gun','hardware-tools','hardware-tools--painting-tools'),
('Step ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Extension ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Platform ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Folding ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Telescopic ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Roof ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Ladder stabilizer','hardware-tools','hardware-tools--ladders-and-access'),
('Ladder stand','hardware-tools','hardware-tools--ladders-and-access'),
('Installation system — Hammer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Screwdriver','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Pliers','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Spanner','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Adjustable wrench','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Pipe wrench','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Allen key set','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Chisel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Punch set','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hand saw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Measuring tape','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Spirit level','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Laser level','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Vernier caliper','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Micrometer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Steel ruler','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Angle finder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Measuring wheel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Feeler gauge','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Bolt cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Pipe cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hacksaw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Tile cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Glass cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Tin snips','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Utility knife','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Cable cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Rebar cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hole saw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Electric drill','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hammer drill','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Rotary hammer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Angle grinder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Bench grinder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Circular saw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Jigsaw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Reciprocating saw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Heat gun','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Common nail','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Masonry nail','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Roofing nail','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Self-tapping screw','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Coach screw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Bolt','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Nut','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Washer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Chemical anchor','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Sleeve anchor','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Wedge anchor','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Drop-in anchor','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Drywall anchor','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Toggle bolt','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Anchor rod','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — PVC adhesive','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Contact adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Epoxy adhesive','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Cyanoacrylate adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Pipe sealant','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Silicone adhesive','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hot-melt adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Sanding sheet','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Sanding belt','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Wire wheel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Grinding stone','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Tool box','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Tool bag','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Workshop stool','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Tool cabinet','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Secateurs','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Pruning saw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hedge shear','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Garden fork','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Spade','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Shovel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hoe','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Rake','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Hand trowel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Basin wrench','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Tube cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — PEX crimper','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — PPR fusion tool','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Pipe threading machine','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Drain auger','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Pipe reamer','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Flare tool','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Press tool','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Cable stripper','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Crimping tool','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Wire cutter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Multimeter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Clamp meter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Voltage tester','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Insulation tester','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Cable tracer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Phase tester','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Terminal crimper','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Brick trowel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Pointing trowel','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Float','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Mason''s hammer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Brick bolster','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Mortar board','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Plastering rule','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Screeding rule','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Brick jointer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Block splitter','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Paint brush','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Paint roller','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Roller frame','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Paint tray','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Extension pole','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Spray gun','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Paint mixer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Paint strainer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Putty knife','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Caulking gun','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Step ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Extension ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Platform ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Folding ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Telescopic ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Roof ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Ladder stabilizer','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Ladder stand','hardware-tools','hardware-tools--expanded-product-families'),
('Replacement component — Hammer','hardware-tools','hardware-tools--expanded-product-families'),
('Replacement component — Screwdriver','hardware-tools','hardware-tools--expanded-product-families'),
('Corrugated roofing sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Pre-painted sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Aluminium roofing sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Stone-coated sheet','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Roof sandwich panel','roofing-ceilings','roofing-ceilings--roof-sheets'),
('Clay tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Concrete tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Interlocking tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Stone-coated tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Roman tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Mission tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Slate tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Terracotta tile','roofing-ceilings','roofing-ceilings--roof-tiles'),
('Roof flashing','roofing-ceilings','roofing-ceilings--roof-accessories'),
('Barge flashing','roofing-ceilings','roofing-ceilings--roof-accessories'),
('Roof vent','roofing-ceilings','roofing-ceilings--roof-accessories'),
('Skylight','roofing-ceilings','roofing-ceilings--roof-accessories'),
('Roof boot','roofing-ceilings','roofing-ceilings--roof-accessories'),
('PVC gutter','roofing-ceilings','roofing-ceilings--gutters'),
('Metal gutter','roofing-ceilings','roofing-ceilings--gutters'),
('Box gutter','roofing-ceilings','roofing-ceilings--gutters'),
('Half-round gutter','roofing-ceilings','roofing-ceilings--gutters'),
('Downpipe','roofing-ceilings','roofing-ceilings--gutters'),
('Gutter outlet','roofing-ceilings','roofing-ceilings--gutters'),
('Gutter bracket','roofing-ceilings','roofing-ceilings--gutters'),
('Gutter guard','roofing-ceilings','roofing-ceilings--gutters'),
('Drainage hopper','roofing-ceilings','roofing-ceilings--gutters'),
('Roofing screw','roofing-ceilings','roofing-ceilings--fasteners'),
('Self-drilling screw','roofing-ceilings','roofing-ceilings--fasteners'),
('Hook bolt','roofing-ceilings','roofing-ceilings--fasteners'),
('J-bolt','roofing-ceilings','roofing-ceilings--fasteners'),
('Rubber washer','roofing-ceilings','roofing-ceilings--fasteners'),
('Metal washer','roofing-ceilings','roofing-ceilings--fasteners'),
('Roof clip','roofing-ceilings','roofing-ceilings--fasteners'),
('Fastener cap','roofing-ceilings','roofing-ceilings--fasteners'),
('PU foam board','roofing-ceilings','roofing-ceilings--insulation'),
('Roof blanket','roofing-ceilings','roofing-ceilings--insulation'),
('Thermal membrane','roofing-ceilings','roofing-ceilings--insulation'),
('PVC ceiling panel','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Mineral fibre tile','roofing-ceilings','roofing-ceilings--ceiling-boards'),
('Acoustic tile','roofing-ceilings','roofing-ceilings--ceiling-boards'),
('Metal ceiling tile','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Wood ceiling panel','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Baffle ceiling','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Stretch ceiling','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Ceiling grid','roofing-ceilings','roofing-ceilings--suspended-ceilings'),
('Cross tee','roofing-ceilings','roofing-ceilings--suspended-ceilings'),
('Hanger wire','roofing-ceilings','roofing-ceilings--suspended-ceilings'),
('Ceiling angle','roofing-ceilings','roofing-ceilings--suspended-ceilings'),
('Roof rafter','roofing-ceilings','roofing-ceilings--roof-timber'),
('Roof batten','roofing-ceilings','roofing-ceilings--roof-timber'),
('Timber purlin','roofing-ceilings','roofing-ceilings--roof-timber'),
('Roof truss','roofing-ceilings','roofing-ceilings--roof-timber'),
('Timber fascia','roofing-ceilings','roofing-ceilings--roof-timber'),
('Timber soffit','roofing-ceilings','roofing-ceilings--roof-timber'),
('Roof pole','roofing-ceilings','roofing-ceilings--roof-timber'),
('Roof bracing','roofing-ceilings','roofing-ceilings--roof-timber'),
('Timber ridge board','roofing-ceilings','roofing-ceilings--roof-timber'),
('Treated roof timber','roofing-ceilings','roofing-ceilings--roof-timber'),
('Static roof vent','roofing-ceilings','roofing-ceilings--ventilation'),
('Vent mesh','roofing-ceilings','roofing-ceilings--ventilation'),
('Roof coating','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Waterproof tape','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Roof sealant','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Flashing sealant','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Roof repair compound','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Butyl tape','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('EPDM membrane','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Roof primer','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Roof skylight','roofing-ceilings','roofing-ceilings--daylighting'),
('Polycarbonate sheet','roofing-ceilings','roofing-ceilings--daylighting'),
('Fiberglass roof sheet','roofing-ceilings','roofing-ceilings--daylighting'),
('Translucent roof panel','roofing-ceilings','roofing-ceilings--daylighting'),
('Dome skylight','roofing-ceilings','roofing-ceilings--daylighting'),
('Roof lantern','roofing-ceilings','roofing-ceilings--daylighting'),
('Light pipe','roofing-ceilings','roofing-ceilings--daylighting'),
('Skylight curb','roofing-ceilings','roofing-ceilings--daylighting'),
('Skylight flashing','roofing-ceilings','roofing-ceilings--daylighting'),
('Skylight seal','roofing-ceilings','roofing-ceilings--daylighting'),
('Roof anchor','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof walkway','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof guardrail','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof ladder hook','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof access hatch','roofing-ceilings','roofing-ceilings--roof-safety'),
('Safety mesh','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof warning sign','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof edge barrier','roofing-ceilings','roofing-ceilings--roof-safety'),
('Roof fall-arrest point','roofing-ceilings','roofing-ceilings--roof-safety'),
('Ceiling plaster','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Ceiling filler','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Decorative ceiling moulding','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Ceiling primer','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Ceiling paint','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Ceiling adhesive','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Ceiling access hatch','roofing-ceilings','roofing-ceilings--ceiling-finishes'),
('Downpipe shoe','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Downpipe offset','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Gutter union','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Gutter end cap','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Gutter stop end','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Gutter leaf guard','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Gutter strainer','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Downpipe connector','roofing-ceilings','roofing-ceilings--roof-drainage'),
('Installation system — Corrugated roofing sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Pre-painted sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Aluminium roofing sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Stone-coated sheet','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof sandwich panel','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Clay tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Concrete tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Interlocking tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Stone-coated tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roman tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Mission tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Slate tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Terracotta tile','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Roof flashing','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Barge flashing','roofing-ceilings','roofing-ceilings--expanded-product-families')
on conflict (n) do update set m = excluded.m, s = excluded.s;
