-- 0065 part 8 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Colorimeter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Flame photometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Moisture analyzer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('DO meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Compound microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Stereo microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Digital microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Fluorescence microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Microscope camera','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Microscope light source','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Microscope stage','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Microscope eyepiece','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Beaker','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Erlenmeyer flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Volumetric flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Measuring cylinder','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Burette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Pipette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Watch glass','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Reagent bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Specimen bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Sample bag','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Cryovial','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Microtube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Sample rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Specimen transport box','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Sample tray','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Laboratory oven','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Heating mantle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Water bath','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Incubator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Laboratory refrigerator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Laboratory freezer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Dry block heater','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--accessories'),
('Benchtop centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('High-speed centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Microcentrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Refrigerated centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Centrifuge rotor','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Centrifuge bucket','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Tube rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Rotor adapter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--service'),
('Lab gloves','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--replacement-parts'),
('Lab goggles','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--replacement-parts'),
('Lab coat','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--replacement-parts'),
('Installation system — Analytical balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Top-pan balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — pH meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Conductivity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Turbidity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Spectrophotometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Colorimeter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Flame photometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Moisture analyzer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — DO meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Compound microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Stereo microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Digital microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Fluorescence microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Microscope camera','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Microscope light source','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Microscope stage','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Microscope eyepiece','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Beaker','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Erlenmeyer flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Volumetric flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Measuring cylinder','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Burette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Pipette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Watch glass','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Reagent bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Specimen bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Sample bag','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Cryovial','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Microtube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Sample rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Specimen transport box','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Sample tray','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Laboratory oven','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Heating mantle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Water bath','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Incubator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Laboratory refrigerator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Laboratory freezer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Dry block heater','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Benchtop centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — High-speed centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Microcentrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Refrigerated centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Centrifuge rotor','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Centrifuge bucket','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Tube rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Rotor adapter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Lab gloves','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Lab goggles','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Lab coat','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Analytical balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Top-pan balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — pH meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Conductivity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Turbidity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Spectrophotometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Colorimeter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Flame photometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Moisture analyzer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — DO meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Compound microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Stereo microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Digital microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Fluorescence microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Microscope camera','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Microscope light source','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Microscope stage','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Microscope eyepiece','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Beaker','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Erlenmeyer flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Volumetric flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Measuring cylinder','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Burette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Pipette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Watch glass','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Reagent bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Specimen bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Sample bag','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Cryovial','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Microtube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Sample rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Specimen transport box','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Sample tray','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Laboratory oven','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Heating mantle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Water bath','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Incubator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Laboratory refrigerator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Laboratory freezer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Dry block heater','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Benchtop centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — High-speed centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Microcentrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Refrigerated centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Centrifuge rotor','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Centrifuge bucket','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Tube rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Rotor adapter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Lab gloves','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Lab goggles','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Lab coat','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Analytical balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Top-pan balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — pH meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Conductivity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Turbidity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Spectrophotometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Colorimeter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Flame photometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Moisture analyzer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — DO meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Compound microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Stereo microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Digital microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Fluorescence microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Microscope camera','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Microscope light source','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Microscope stage','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Microscope eyepiece','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Beaker','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Erlenmeyer flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Volumetric flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Measuring cylinder','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Burette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Pipette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Watch glass','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Reagent bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Specimen bottle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Sample bag','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Cryovial','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Microtube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Sample rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Specimen transport box','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Sample tray','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Laboratory oven','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Heating mantle','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Water bath','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Incubator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Laboratory refrigerator','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Laboratory freezer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Dry block heater','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Benchtop centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — High-speed centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Microcentrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Refrigerated centrifuge','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Centrifuge rotor','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Centrifuge bucket','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Tube rack','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Rotor adapter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Lab gloves','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Lab goggles','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Lab coat','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Analytical balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Top-pan balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — pH meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Conductivity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Turbidity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Spectrophotometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Colorimeter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Flame photometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Moisture analyzer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — DO meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Compound microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Stereo microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Digital microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Fluorescence microscope','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Microscope camera','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Microscope slide','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Cover slip','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Microscope light source','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Microscope stage','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Microscope eyepiece','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Beaker','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Erlenmeyer flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Volumetric flask','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Measuring cylinder','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Test tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Burette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Pipette','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Decorative stone panel','furniture-and-interior-products','furniture-and-interior-products--vehicles-core'),
('Decorative ceiling panel','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Acoustic ceiling panel','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Gypsum ceiling tile','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Linear ceiling','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Coffered ceiling','furniture-and-interior-products','furniture-and-interior-products--equipment'),
('Roller blind','furniture-and-interior-products','furniture-and-interior-products--components'),
('Drawer slide','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Cabinet hinge','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Furniture handle','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Table leg','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Furniture connector','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Shelf bracket','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Bed fitting','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Furniture gas lift','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Wardrobe cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Pantry unit','furniture-and-interior-products','furniture-and-interior-products--service'),
('Vanity unit','furniture-and-interior-products','furniture-and-interior-products--service'),
('TV cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Wine cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Bathroom cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Bed bench','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Bedroom mirror','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Bedroom shelf','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Jewelry cabinet','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Bedroom screen','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Installation system — Decorative stone panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Decorative ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Acoustic ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Gypsum ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Linear ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Coffered ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Roller blind','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Drawer slide','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Cabinet hinge','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Furniture handle','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Table leg','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Furniture connector','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Shelf bracket','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bed fitting','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Furniture gas lift','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Wardrobe cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Pantry unit','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Vanity unit','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — TV cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Wine cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bathroom cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bed bench','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bedroom mirror','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bedroom shelf','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Jewelry cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bedroom screen','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Decorative stone panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Decorative ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Acoustic ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — PVC ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Gypsum ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Metal ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Wood ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Baffle ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Linear ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Stretch ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Coffered ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Roller blind','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Drawer slide','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Cabinet hinge','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Furniture handle','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Table leg','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Furniture connector','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Shelf bracket','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bed fitting','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Furniture gas lift','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Wardrobe cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Pantry unit','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Vanity unit','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — TV cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Wine cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bathroom cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bed bench','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bedroom mirror','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bedroom shelf','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Jewelry cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bedroom screen','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Decorative stone panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Decorative ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Acoustic ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — PVC ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Gypsum ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Metal ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Wood ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Baffle ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Linear ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Stretch ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Coffered ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Roller blind','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Drawer slide','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Cabinet hinge','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Furniture handle','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Table leg','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Furniture connector','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Shelf bracket','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bed fitting','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Furniture gas lift','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Wardrobe cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Pantry unit','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Vanity unit','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — TV cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Wine cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bathroom cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bed bench','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bedroom mirror','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bedroom shelf','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Jewelry cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bedroom screen','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Decorative stone panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Decorative ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Acoustic ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — PVC ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Gypsum ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Metal ceiling tile','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Wood ceiling panel','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Baffle ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Linear ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Stretch ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Coffered ceiling','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Testing equipment — Roller blind','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Liquid filling machine','packaging-machinery','packaging-machinery--vehicles-core'),
('Paste filling machine','packaging-machinery','packaging-machinery--vehicles-core'),
('Powder filling machine','packaging-machinery','packaging-machinery--vehicles-core'),
('Granule filling machine','packaging-machinery','packaging-machinery--vehicles-core'),
('Oil filling machine','packaging-machinery','packaging-machinery--vehicles-core'),
('Water filling machine','packaging-machinery','packaging-machinery--vehicles-core'),
('Bottle filler','packaging-machinery','packaging-machinery--vehicles-core'),
('Pouch filler','packaging-machinery','packaging-machinery--vehicles-core'),
('Cup filler','packaging-machinery','packaging-machinery--vehicles-core'),
('Tube filler','packaging-machinery','packaging-machinery--vehicles-core'),
('Induction sealer','packaging-machinery','packaging-machinery--equipment'),
('Continuous band sealer','packaging-machinery','packaging-machinery--equipment'),
('Impulse sealer','packaging-machinery','packaging-machinery--equipment'),
('Cup sealer','packaging-machinery','packaging-machinery--equipment'),
('Tray sealer','packaging-machinery','packaging-machinery--equipment'),
('Vacuum sealer','packaging-machinery','packaging-machinery--equipment'),
('Heat sealer','packaging-machinery','packaging-machinery--equipment'),
('Carton labeller','packaging-machinery','packaging-machinery--components'),
('Wrap-around labeller','packaging-machinery','packaging-machinery--components'),
('Shrink sleeve machine','packaging-machinery','packaging-machinery--components'),
('Inkjet coder','packaging-machinery','packaging-machinery--systems'),
('Laser coder','packaging-machinery','packaging-machinery--systems'),
('Thermal transfer printer','packaging-machinery','packaging-machinery--systems'),
('Batch coder','packaging-machinery','packaging-machinery--systems'),
('Date coder','packaging-machinery','packaging-machinery--systems'),
('Barcode printer','packaging-machinery','packaging-machinery--systems'),
('Marking machine','packaging-machinery','packaging-machinery--systems'),
('Embossing machine','packaging-machinery','packaging-machinery--systems'),
('Coding controller','packaging-machinery','packaging-machinery--systems'),
('Stretch wrapper','packaging-machinery','packaging-machinery--accessories'),
('Shrink wrapper','packaging-machinery','packaging-machinery--accessories'),
('Flow wrapper','packaging-machinery','packaging-machinery--accessories'),
('Horizontal wrapper','packaging-machinery','packaging-machinery--accessories'),
('Vertical wrapper','packaging-machinery','packaging-machinery--accessories'),
('Pallet wrapper','packaging-machinery','packaging-machinery--accessories'),
('Overwrapping machine','packaging-machinery','packaging-machinery--accessories'),
('Film wrapping machine','packaging-machinery','packaging-machinery--accessories'),
('Paper wrapping machine','packaging-machinery','packaging-machinery--accessories'),
('Carton erector','packaging-machinery','packaging-machinery--service'),
('Carton former','packaging-machinery','packaging-machinery--service'),
('Carton closer','packaging-machinery','packaging-machinery--service'),
('Cartoning machine','packaging-machinery','packaging-machinery--service'),
('Case sealer','packaging-machinery','packaging-machinery--service'),
('Carton coding machine','packaging-machinery','packaging-machinery--service'),
('Carton palletizer','packaging-machinery','packaging-machinery--replacement-parts'),
('Pallet conveyor','packaging-machinery','packaging-machinery--replacement-parts'),
('Installation system — Liquid filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Paste filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Powder filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Granule filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Oil filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Water filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Bottle filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Pouch filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Cup filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Tube filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Induction sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Continuous band sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Impulse sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Cup sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Tray sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Vacuum sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Heat sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Carton labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Wrap-around labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Shrink sleeve machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Inkjet coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Laser coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Thermal transfer printer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Batch coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Date coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Barcode printer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Marking machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Embossing machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Coding controller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Stretch wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Shrink wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Flow wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Horizontal wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Vertical wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Pallet wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Overwrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Film wrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Paper wrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Carton erector','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Carton former','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Carton closer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Cartoning machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Case sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Carton coding machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Carton palletizer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Pallet conveyor','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Liquid filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Paste filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Powder filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Granule filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Oil filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Water filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Bottle filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Pouch filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Cup filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Tube filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Induction sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Continuous band sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Impulse sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Cup sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Tray sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Vacuum sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Heat sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Carton labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Wrap-around labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Shrink sleeve machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Inkjet coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Laser coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Thermal transfer printer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Batch coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Date coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Barcode printer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Marking machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Embossing machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Coding controller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Stretch wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Shrink wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Flow wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Horizontal wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Vertical wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Pallet wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Overwrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Film wrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Paper wrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Carton erector','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Carton former','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Carton closer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Cartoning machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Case sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Carton coding machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Carton palletizer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Pallet conveyor','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Liquid filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Paste filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Powder filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Granule filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Oil filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Water filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Bottle filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Pouch filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Cup filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Tube filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Induction sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Continuous band sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Impulse sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Cup sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Tray sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Vacuum sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Heat sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Carton labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Wrap-around labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Shrink sleeve machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Inkjet coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Laser coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Thermal transfer printer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Batch coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Date coder','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Barcode printer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Marking machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Embossing machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Coding controller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Stretch wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Shrink wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Flow wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Horizontal wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Vertical wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Pallet wrapper','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Overwrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Film wrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Paper wrapping machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Carton erector','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Carton former','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Carton closer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Cartoning machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Case sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Carton coding machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Carton palletizer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Pallet conveyor','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Liquid filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Paste filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Powder filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Granule filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Oil filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Water filling machine','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Bottle filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Pouch filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Cup filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Tube filler','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Induction sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Continuous band sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Impulse sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Cup sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Tray sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Vacuum sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Heat sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Testing equipment — Carton labeller','packaging-machinery','packaging-machinery--expanded-product-families'),
('Deep-groove ball bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Angular-contact bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Self-aligning bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Cylindrical roller bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Tapered roller bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Needle bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Spherical roller bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Thrust bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Pillow-block bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('Flange bearing','other-industrial-supplies','other-industrial-supplies--bearings'),
('V-belt','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Roller chain','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Leaf chain','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Sprocket','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Pulley','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Gear','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Coupling','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Oil seal','other-industrial-supplies','other-industrial-supplies--seals'),
('Mechanical seal','other-industrial-supplies','other-industrial-supplies--seals'),
('Packing seal','other-industrial-supplies','other-industrial-supplies--seals'),
('Hydraulic seal','other-industrial-supplies','other-industrial-supplies--seals'),
('Pneumatic seal','other-industrial-supplies','other-industrial-supplies--seals'),
('Pneumatic hose','other-industrial-supplies','other-industrial-supplies--pneumatics'),
('Hydraulic pump','other-industrial-supplies','other-industrial-supplies--hydraulics'),
('Hydraulic valve','other-industrial-supplies','other-industrial-supplies--hydraulics'),
('Hydraulic hose','other-industrial-supplies','other-industrial-supplies--hydraulics'),
('Hydraulic fitting','other-industrial-supplies','other-industrial-supplies--hydraulics'),
('Hydraulic motor','other-industrial-supplies','other-industrial-supplies--hydraulics'),
('Plug valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Control valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Safety valve','other-industrial-supplies','other-industrial-supplies--flow-control'),
('Gear motor','other-industrial-supplies','other-industrial-supplies--motors-and-drives'),
('Motor brake','other-industrial-supplies','other-industrial-supplies--motors-and-drives'),
('Welding electrode','other-industrial-supplies','other-industrial-supplies--workshop-consumables'),
('Threaded rod','other-industrial-supplies','other-industrial-supplies--industrial-hardware'),
('Brake motor','other-industrial-supplies','other-industrial-supplies--motors-and-electrical'),
('Chain block','other-industrial-supplies','other-industrial-supplies--material-handling'),
('Thread sealant','other-industrial-supplies','other-industrial-supplies--maintenance-products'),
('Bearing grease','other-industrial-supplies','other-industrial-supplies--maintenance-products'),
('Chain lubricant','other-industrial-supplies','other-industrial-supplies--maintenance-products'),
('Installation system — Deep-groove ball bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Angular-contact bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Self-aligning bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Cylindrical roller bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Tapered roller bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Needle bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Spherical roller bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Thrust bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Pillow-block bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Flange bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — V-belt','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Roller chain','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Leaf chain','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Sprocket','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Pulley','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Gear','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Coupling','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Oil seal','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Mechanical seal','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Packing seal','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Hydraulic seal','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Pneumatic seal','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Pneumatic hose','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Hydraulic pump','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Hydraulic valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Hydraulic hose','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Hydraulic fitting','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Hydraulic motor','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Plug valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Control valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Safety valve','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Gear motor','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Motor brake','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Welding electrode','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Threaded rod','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Brake motor','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Chain block','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Thread sealant','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Bearing grease','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Chain lubricant','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Deep-groove ball bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Angular-contact bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Self-aligning bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Cylindrical roller bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Tapered roller bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Needle bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Spherical roller bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Thrust bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Pillow-block bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Flange bearing','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — V-belt','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Roller chain','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Leaf chain','other-industrial-supplies','other-industrial-supplies--expanded-product-families')
on conflict (n) do update set m = excluded.m, s = excluded.s;
