-- 0065 part 5 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Road roller','construction-machinery-and-equipment','construction-machinery-and-equipment--systems'),
('Tandem roller','construction-machinery-and-equipment','construction-machinery-and-equipment--systems'),
('Vibratory roller','construction-machinery-and-equipment','construction-machinery-and-equipment--systems'),
('Rock drill','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Core drill','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Rotary drill','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('DTH drill','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Diamond drill','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Drill compressor','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Drill rod','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Drill bit','construction-machinery-and-equipment','construction-machinery-and-equipment--accessories'),
('Installation system — Backhoe loader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Motor grader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Concrete pump','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Road roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Tandem roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Vibratory roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Rock drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Core drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Rotary drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — DTH drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Diamond drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Drill compressor','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Drill rod','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Drill bit','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Backhoe loader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Motor grader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Concrete pump','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Road roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Tandem roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Vibratory roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Rock drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Core drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Rotary drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — DTH drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Diamond drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Drill compressor','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Drill rod','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Drill bit','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Backhoe loader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Motor grader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Concrete pump','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Road roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Tandem roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Vibratory roller','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Rock drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Core drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Rotary drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — DTH drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Diamond drill','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Drill compressor','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Drill rod','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Drill bit','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Testing equipment — Backhoe loader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Testing equipment — Motor grader','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Mouldboard plough','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--equipment'),
('Maize planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--components'),
('Rice planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--components'),
('Vegetable planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--components'),
('Maize sheller','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--systems'),
('Maize harvester','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--systems'),
('Boom sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('Knapsack sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('Motorized sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('Tractor sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('ULV sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('Sprayer boom','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('Sprayer pump','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--accessories'),
('Grain sorter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--service'),
('Grain mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--service'),
('Rice mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--service'),
('Feed mixer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--service'),
('Feed pelletizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Feed grinder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Feed crusher','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Feed extruder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Feed conveyor','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Feed bagging machine','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Dairy pasteurizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Installation system — Mouldboard plough','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Maize planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Rice planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Vegetable planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Maize sheller','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Maize harvester','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Boom sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Knapsack sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Motorized sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Tractor sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — ULV sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Sprayer boom','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Sprayer pump','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Grain sorter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Grain mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Rice mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed mixer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed pelletizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed grinder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed crusher','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed extruder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed conveyor','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Feed bagging machine','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Dairy pasteurizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Mouldboard plough','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Maize planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Rice planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Vegetable planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Maize sheller','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Maize harvester','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Boom sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Knapsack sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Motorized sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Tractor sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — ULV sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Sprayer boom','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Sprayer pump','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Grain sorter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Grain mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Rice mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed mixer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed pelletizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed grinder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed crusher','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed extruder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed conveyor','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Feed bagging machine','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Dairy pasteurizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Mouldboard plough','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Maize planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Rice planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Vegetable planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Maize sheller','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Maize harvester','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Boom sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Knapsack sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Motorized sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Tractor sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — ULV sprayer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Sprayer boom','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Sprayer pump','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Grain sorter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Grain mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Rice mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed mixer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed pelletizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed grinder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed crusher','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed extruder','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed conveyor','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Feed bagging machine','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Dairy pasteurizer','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Testing equipment — Mouldboard plough','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Testing equipment — Maize planter','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Sofa','furniture-fittings','furniture-fittings--vehicles-core'),
('Sectional sofa','furniture-fittings','furniture-fittings--vehicles-core'),
('Armchair','furniture-fittings','furniture-fittings--vehicles-core'),
('Recliner','furniture-fittings','furniture-fittings--vehicles-core'),
('Coffee table','furniture-fittings','furniture-fittings--vehicles-core'),
('Side table','furniture-fittings','furniture-fittings--vehicles-core'),
('TV stand','furniture-fittings','furniture-fittings--vehicles-core'),
('Console table','furniture-fittings','furniture-fittings--vehicles-core'),
('Ottoman','furniture-fittings','furniture-fittings--vehicles-core'),
('Bed frame','furniture-fittings','furniture-fittings--equipment'),
('Platform bed','furniture-fittings','furniture-fittings--equipment'),
('Bunk bed','furniture-fittings','furniture-fittings--equipment'),
('Bedside table','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Wardrobe','furniture-fittings','furniture-fittings--equipment'),
('Chest of drawers','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Dressing table','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Bedroom bench','furniture-fittings','furniture-fittings--equipment'),
('Headboard','furniture-and-interior-products','furniture-and-interior-products--replacement-parts'),
('Mattress','furniture-fittings','furniture-fittings--equipment'),
('Office desk','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Executive desk','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Workstation','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Office chair','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Visitor chair','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Conference table','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Filing cabinet','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Bookcase','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Reception desk','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Meeting chair','office-and-business-supplies','office-and-business-supplies--vehicles-core'),
('Student desk','furniture-fittings','furniture-fittings--systems'),
('Student chair','furniture-fittings','furniture-fittings--systems'),
('Teacher desk','furniture-fittings','furniture-fittings--systems'),
('Teacher chair','furniture-fittings','furniture-fittings--systems'),
('School table','furniture-fittings','furniture-fittings--systems'),
('School bench','furniture-fittings','furniture-fittings--systems'),
('Laboratory stool','furniture-fittings','furniture-fittings--systems'),
('Library shelf','furniture-fittings','furniture-fittings--systems'),
('Computer desk','furniture-fittings','furniture-fittings--systems'),
('Training table','furniture-fittings','furniture-fittings--systems'),
('Kitchen cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Base cabinet','furniture-fittings','furniture-fittings--accessories'),
('Wall cabinet','furniture-fittings','furniture-fittings--accessories'),
('Kitchen island','furniture-and-interior-products','furniture-and-interior-products--service'),
('Pantry cabinet','furniture-fittings','furniture-fittings--accessories'),
('Breakfast counter','furniture-fittings','furniture-fittings--accessories'),
('Kitchen trolley','furniture-fittings','furniture-fittings--accessories'),
('Utility cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Sink cabinet','furniture-fittings','furniture-fittings--accessories'),
('Kitchen shelf','furniture-fittings','furniture-fittings--accessories'),
('Dining table','furniture-fittings','furniture-fittings--service'),
('Dining chair','furniture-fittings','furniture-fittings--service'),
('Bar stool','furniture-fittings','furniture-fittings--service'),
('Dining bench','furniture-fittings','furniture-fittings--service'),
('Buffet cabinet','furniture-fittings','furniture-fittings--service'),
('Sideboard','furniture-fittings','furniture-fittings--service'),
('Serving trolley','hospitality-and-catering-supplies','hospitality-and-catering-supplies--systems'),
('Bar table','furniture-fittings','furniture-fittings--service'),
('Dining console','furniture-fittings','furniture-fittings--service'),
('Display cabinet','furniture-and-interior-products','furniture-and-interior-products--service'),
('Garden chair','furniture-fittings','furniture-fittings--replacement-parts'),
('Garden table','furniture-fittings','furniture-fittings--replacement-parts'),
('Outdoor sofa','furniture-fittings','furniture-fittings--replacement-parts'),
('Sun lounger','furniture-fittings','furniture-fittings--replacement-parts'),
('Park bench','furniture-fittings','furniture-fittings--replacement-parts'),
('Picnic table','furniture-fittings','furniture-fittings--replacement-parts'),
('Plastic chair','furniture-fittings','furniture-fittings--replacement-parts'),
('Plastic table','furniture-fittings','furniture-fittings--replacement-parts'),
('Outdoor bench','furniture-fittings','furniture-fittings--replacement-parts'),
('Installation system — Sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Sectional sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Armchair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Recliner','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Coffee table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Side table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — TV stand','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Console table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Ottoman','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Bed frame','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Platform bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Bunk bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Bedside table','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Wardrobe','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Chest of drawers','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Dressing table','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Bedroom bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Headboard','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Mattress','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Office desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Executive desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Workstation','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Office chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Visitor chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Conference table','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Filing cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Bookcase','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Reception desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Meeting chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Student desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Student chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Teacher desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Teacher chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — School table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — School bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Laboratory stool','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Library shelf','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Computer desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Training table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Kitchen cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Base cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Wall cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Kitchen island','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Pantry cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Breakfast counter','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Kitchen trolley','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Utility cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Sink cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Kitchen shelf','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Dining table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Dining chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Bar stool','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Dining bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Buffet cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Sideboard','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Serving trolley','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Bar table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Dining console','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Display cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Garden chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Garden table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Outdoor sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Sun lounger','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Park bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Picnic table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Plastic chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Plastic table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Installation system — Outdoor bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Sectional sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Armchair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Recliner','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Coffee table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Side table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — TV stand','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Console table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Ottoman','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Bed frame','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Platform bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Bunk bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Bedside table','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Wardrobe','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Chest of drawers','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Dressing table','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Bedroom bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Headboard','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Mattress','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Office desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Executive desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Workstation','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Office chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Visitor chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Conference table','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Filing cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Bookcase','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Reception desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Meeting chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Student desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Student chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Teacher desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Teacher chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — School table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — School bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Laboratory stool','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Library shelf','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Computer desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Training table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Kitchen cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Base cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Wall cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Kitchen island','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Pantry cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Breakfast counter','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Kitchen trolley','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Utility cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Sink cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Kitchen shelf','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Dining table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Dining chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Bar stool','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Dining bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Buffet cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Sideboard','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Serving trolley','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Bar table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Dining console','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Display cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Garden chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Garden table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Outdoor sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Sun lounger','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Park bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Picnic table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Plastic chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Plastic table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Replacement component — Outdoor bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Sectional sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Armchair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Recliner','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Coffee table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Side table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — TV stand','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Console table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Ottoman','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Bed frame','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Platform bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Bunk bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Bedside table','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Wardrobe','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Chest of drawers','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Dressing table','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Bedroom bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Headboard','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Mattress','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Office desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Executive desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Workstation','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Office chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Visitor chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Conference table','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Filing cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Bookcase','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Reception desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Meeting chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Student desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Student chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Teacher desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Teacher chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — School table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — School bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Laboratory stool','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Library shelf','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Computer desk','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Training table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Kitchen cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Base cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Wall cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Kitchen island','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Pantry cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Breakfast counter','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Kitchen trolley','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Utility cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Sink cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Kitchen shelf','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Dining table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Dining chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Bar stool','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Dining bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Buffet cabinet','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Sideboard','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Serving trolley','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Bar table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Dining console','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Display cabinet','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Garden chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Garden table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Outdoor sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Sun lounger','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Park bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Picnic table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Plastic chair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Plastic table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Service equipment — Outdoor bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Sectional sofa','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Armchair','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Recliner','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Coffee table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Side table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — TV stand','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Console table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Ottoman','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Bed frame','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Platform bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Bunk bed','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Bedside table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Wardrobe','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Chest of drawers','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Dressing table','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Bedroom bench','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Headboard','furniture-fittings','furniture-fittings--expanded-product-families'),
('Testing equipment — Mattress','furniture-fittings','furniture-fittings--expanded-product-families'),
('Cotton fabric','textiles-apparel','textiles-apparel--vehicles-core'),
('Poly-cotton fabric','textiles-apparel','textiles-apparel--vehicles-core'),
('T-shirts','textiles-apparel','textiles-apparel--equipment'),
('Polo shirts','textiles-apparel','textiles-apparel--equipment'),
('Shirts','textiles-apparel','textiles-apparel--equipment'),
('Trousers','textiles-apparel','textiles-apparel--equipment'),
('Jeans','textiles-apparel','textiles-apparel--equipment'),
('Shorts','textiles-apparel','textiles-apparel--equipment'),
('Work trousers','textiles-apparel','textiles-apparel--components'),
('Work shirts','textiles-apparel','textiles-apparel--components'),
('School shirts','textiles-apparel','textiles-apparel--systems'),
('School trousers','textiles-apparel','textiles-apparel--systems'),
('Protective fabric','textiles-apparel','textiles-apparel--service'),
('Installation system — Cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Poly-cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — T-shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Polo shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Jeans','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Shorts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Work trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Work shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — School shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — School trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Installation system — Protective fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Poly-cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — T-shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Polo shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Jeans','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Shorts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Work trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Work shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — School shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — School trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Replacement component — Protective fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Poly-cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — T-shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Polo shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Jeans','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Shorts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Work trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Work shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — School shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — School trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Service equipment — Protective fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Poly-cotton fabric','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — T-shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Polo shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Jeans','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Shorts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Work trousers','textiles-apparel','textiles-apparel--expanded-product-families'),
('Testing equipment — Work shirts','textiles-apparel','textiles-apparel--expanded-product-families'),
('Floor cleaner','cleaning-hygiene','cleaning-hygiene--core'),
('Toilet cleaner','cleaning-hygiene','cleaning-hygiene--core'),
('Glass cleaner','cleaning-hygiene','cleaning-hygiene--core'),
('Kitchen cleaner','cleaning-hygiene','cleaning-hygiene--core'),
('Bathroom cleaner','cleaning-hygiene','cleaning-hygiene--core'),
('All-purpose cleaner','cleaning-hygiene','cleaning-hygiene--core'),
('Dishwashing liquid','cleaning-hygiene','cleaning-hygiene--core'),
('Laundry detergent','cleaning-hygiene','cleaning-hygiene--core'),
('Bleach','cleaning-hygiene','cleaning-hygiene--core'),
('Disinfectant','cleaning-hygiene','cleaning-hygiene--core'),
('Industrial degreaser','cleaning-hygiene','cleaning-hygiene--equipment'),
('Machine cleaner','cleaning-hygiene','cleaning-hygiene--equipment'),
('Parts cleaner','cleaning-hygiene','cleaning-hygiene--equipment'),
('Heavy-duty detergent','cleaning-hygiene','cleaning-hygiene--equipment'),
('Foam cleaner','cleaning-hygiene','cleaning-hygiene--equipment'),
('Soap dispenser','cleaning-hygiene','cleaning-hygiene--consumables'),
('Pressure washer','cleaning-hygiene','cleaning-hygiene--installation'),
('Steam cleaner','cleaning-hygiene','cleaning-hygiene--installation'),
('Hand wash','cleaning-hygiene','cleaning-hygiene--maintenance'),
('Hand sanitizer','cleaning-hygiene','cleaning-hygiene--maintenance'),
('Liquid soap','cleaning-hygiene','cleaning-hygiene--maintenance'),
('Bar soap','cleaning-hygiene','cleaning-hygiene--maintenance'),
('Body wash','cleaning-hygiene','cleaning-hygiene--maintenance'),
('Installation system — Floor cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Toilet cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Glass cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Kitchen cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Bathroom cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — All-purpose cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Dishwashing liquid','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Laundry detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Bleach','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Disinfectant','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Industrial degreaser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Machine cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Parts cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Heavy-duty detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Foam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Soap dispenser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Pressure washer','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Steam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Hand wash','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Hand sanitizer','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Liquid soap','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Bar soap','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Body wash','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Floor cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Toilet cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Glass cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Kitchen cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Bathroom cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — All-purpose cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Dishwashing liquid','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Laundry detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Bleach','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Disinfectant','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Industrial degreaser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Machine cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Parts cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Heavy-duty detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Foam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Soap dispenser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Pressure washer','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Steam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Hand wash','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Hand sanitizer','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Liquid soap','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Bar soap','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Body wash','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Floor cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Toilet cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Glass cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Kitchen cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Bathroom cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — All-purpose cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Dishwashing liquid','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Laundry detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Bleach','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Disinfectant','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Industrial degreaser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Machine cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Parts cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Heavy-duty detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Foam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Soap dispenser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Pressure washer','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Steam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Hand wash','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Hand sanitizer','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Liquid soap','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Bar soap','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Body wash','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Floor cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Toilet cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Glass cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Kitchen cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Bathroom cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — All-purpose cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Dishwashing liquid','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Laundry detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Bleach','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Disinfectant','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Industrial degreaser','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Machine cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Boiler cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Solvent cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Parts cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Heavy-duty detergent','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Testing equipment — Foam cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Surgical mask','medical-supplies','medical-supplies--core'),
('N95 respirator','safety-ppe','safety-ppe--consumables'),
('Examination gloves','medical-supplies','medical-supplies--core'),
('Surgical gloves','medical-supplies','medical-supplies--core'),
('Gown','medical-supplies','medical-supplies--core'),
('Apron','medical-supplies','medical-supplies--core'),
('Face shield','safety-ppe','safety-ppe--core'),
('Surgical cap','medical-supplies','medical-supplies--core'),
('Shoe covers','medical-supplies','medical-supplies--core'),
('Protective goggles','medical-supplies','medical-supplies--core'),
('Gauze','medical-supplies','medical-supplies--equipment'),
('Cotton wool','medical-supplies','medical-supplies--equipment'),
('Adhesive bandage','medical-supplies','medical-supplies--equipment'),
('Elastic bandage','medical-supplies','medical-supplies--equipment'),
('Crepe bandage','medical-supplies','medical-supplies--equipment'),
('Plaster roll','medical-supplies','medical-supplies--equipment'),
('Wound dressing','medical-supplies','medical-supplies--equipment'),
('Burn dressing','medical-supplies','medical-supplies--equipment'),
('Absorbent dressing','medical-supplies','medical-supplies--equipment'),
('Medical tape','medical-supplies','medical-supplies--equipment'),
('Disposable syringe','medical-supplies','medical-supplies--consumables'),
('Insulin syringe','medical-supplies','medical-supplies--consumables'),
('Safety syringe','medical-supplies','medical-supplies--consumables'),
('Hypodermic needle','medical-supplies','medical-supplies--consumables'),
('IV cannula','medical-supplies','medical-supplies--consumables'),
('Butterfly needle','medical-supplies','medical-supplies--consumables'),
('Spinal needle','medical-supplies','medical-supplies--consumables'),
('Dental needle','medical-supplies','medical-supplies--consumables'),
('Sharps container','medical-supplies','medical-supplies--consumables'),
('Needle holder','medical-supplies','medical-supplies--consumables'),
('IV giving set','medical-supplies','medical-supplies--components'),
('Blood transfusion set','medical-supplies','medical-supplies--components'),
('IV extension set','medical-supplies','medical-supplies--components'),
('Three-way stopcock','medical-supplies','medical-supplies--components'),
('IV connector','medical-supplies','medical-supplies--components'),
('Infusion pump set','medical-supplies','medical-supplies--components'),
('Pressure infusion bag','medical-supplies','medical-supplies--components'),
('IV stand','medical-supplies','medical-supplies--components'),
('IV dressing','medical-supplies','medical-supplies--components'),
('Blood collection set','medical-supplies','medical-supplies--components'),
('Blood pressure monitor','medical-supplies','medical-supplies--installation'),
('Pulse oximeter','medical-supplies','medical-supplies--installation'),
('Thermometer','medical-supplies','medical-supplies--installation'),
('Stethoscope','medical-supplies','medical-supplies--installation'),
('Nebulizer','medical-supplies','medical-supplies--installation'),
('Fetal doppler','medical-supplies','medical-supplies--installation'),
('ECG machine','medical-supplies','medical-supplies--installation'),
('Patient monitor','medical-supplies','medical-supplies--installation'),
('Otoscope','medical-supplies','medical-supplies--installation'),
('Hospital bed','medical-supplies','medical-supplies--protection'),
('Examination couch','medical-supplies','medical-supplies--protection'),
('Bedside locker','medical-supplies','medical-supplies--protection'),
('Overbed table','medical-supplies','medical-supplies--protection'),
('Wheelchair','medical-supplies','medical-supplies--protection'),
('Patient stretcher','medical-supplies','medical-supplies--protection'),
('Hospital trolley','medical-supplies','medical-supplies--protection'),
('Instrument trolley','medical-supplies','medical-supplies--protection'),
('IV pole','medical-supplies','medical-supplies--protection'),
('Sample container','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Urine container','medical-supplies','medical-supplies--maintenance'),
('Blood tube','medical-supplies','medical-supplies--maintenance'),
('Microscope slide','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Cover slip','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--equipment'),
('Test tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--components'),
('Centrifuge tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--systems'),
('Installation system — Surgical mask','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — N95 respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Examination gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Surgical gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Gown','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Apron','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Face shield','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Surgical cap','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Shoe covers','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Protective goggles','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Gauze','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Cotton wool','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Adhesive bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Elastic bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Crepe bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Plaster roll','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Wound dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Burn dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Absorbent dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Medical tape','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Disposable syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Insulin syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Safety syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Hypodermic needle','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV cannula','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Butterfly needle','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Spinal needle','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Dental needle','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Sharps container','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Needle holder','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV giving set','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Blood transfusion set','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV extension set','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Three-way stopcock','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV connector','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Infusion pump set','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Pressure infusion bag','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV stand','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Blood collection set','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Blood pressure monitor','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Pulse oximeter','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Thermometer','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Stethoscope','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Nebulizer','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Fetal doppler','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — ECG machine','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Patient monitor','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Otoscope','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Hospital bed','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Examination couch','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Bedside locker','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Overbed table','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Wheelchair','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Patient stretcher','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Hospital trolley','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Instrument trolley','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — IV pole','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Sample container','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Urine container','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Blood tube','medical-supplies','medical-supplies--expanded-product-families'),
('Installation system — Microscope slide','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Cover slip','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Test tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Installation system — Centrifuge tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Surgical mask','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — N95 respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Examination gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Surgical gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Gown','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Apron','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Face shield','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Surgical cap','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Shoe covers','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Protective goggles','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Gauze','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Cotton wool','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Adhesive bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Elastic bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Crepe bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Plaster roll','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Wound dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Burn dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Absorbent dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Medical tape','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Disposable syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Insulin syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Safety syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Hypodermic needle','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV cannula','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Butterfly needle','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Spinal needle','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Dental needle','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Sharps container','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Needle holder','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV giving set','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Blood transfusion set','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV extension set','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Three-way stopcock','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV connector','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Infusion pump set','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Pressure infusion bag','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV stand','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Blood collection set','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Blood pressure monitor','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Pulse oximeter','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Thermometer','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Stethoscope','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Nebulizer','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Fetal doppler','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — ECG machine','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Patient monitor','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Otoscope','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Hospital bed','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Examination couch','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Bedside locker','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Overbed table','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Wheelchair','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Patient stretcher','medical-supplies','medical-supplies--expanded-product-families')
on conflict (n) do update set m = excluded.m, s = excluded.s;
