-- 0065 part 1 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Maize grain','agriculture-produce','agriculture-produce--cereals-and-grains'),
('Sorghum grain','agriculture-produce','agriculture-produce--cereals-and-grains'),
('Rice paddy','agriculture-produce','agriculture-produce--cereals-and-grains'),
('Milled rice','agriculture-produce','agriculture-produce--cereals-and-grains'),
('Brown rice','agriculture-produce','agriculture-produce--cereals-and-grains'),
('Parboiled rice','agriculture-produce','agriculture-produce--cereals-and-grains'),
('Dry beans','agriculture-produce','agriculture-produce--pulses'),
('Kidney beans','agriculture-produce','agriculture-produce--pulses'),
('Soybeans','agriculture-produce','agriculture-produce--pulses'),
('Green grams','agriculture-produce','agriculture-produce--pulses'),
('Lentils','agriculture-produce','agriculture-produce--pulses'),
('Bambara nuts','agriculture-produce','agriculture-produce--pulses'),
('Sesame seed','agriculture-produce','agriculture-produce--oilseeds'),
('Cassava flour','agriculture-produce','agriculture-produce--roots-and-tubers'),
('Sweet potatoes','agriculture-produce','agriculture-produce--roots-and-tubers'),
('Irish potatoes','agriculture-produce','agriculture-produce--roots-and-tubers'),
('Yams','agriculture-produce','agriculture-produce--roots-and-tubers'),
('Cocoyam','agriculture-produce','agriculture-produce--roots-and-tubers'),
('Potato starch','agriculture-produce','agriculture-produce--roots-and-tubers'),
('Tomatoes','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Cabbage','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Carrots','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Onions','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Garlic','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Green pepper','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Chilli','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Eggplant','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Okra','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Cucumber','agriculture-produce','agriculture-produce--fresh-vegetables'),
('Spinach','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Kale','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Amaranth','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Lettuce','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Swiss chard','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Broccoli','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Cauliflower','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Spring onions','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Leeks','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Celery','agriculture-produce','agriculture-produce--leafy-vegetables'),
('Bananas','agriculture-produce','agriculture-produce--fresh-fruits'),
('Matoke','agriculture-produce','agriculture-produce--fresh-fruits'),
('Avocados','agriculture-produce','agriculture-produce--fresh-fruits'),
('Mangoes','agriculture-produce','agriculture-produce--fresh-fruits'),
('Pineapples','agriculture-produce','agriculture-produce--fresh-fruits'),
('Papaya','agriculture-produce','agriculture-produce--fresh-fruits'),
('Passion fruit','agriculture-produce','agriculture-produce--fresh-fruits'),
('Oranges','agriculture-produce','agriculture-produce--fresh-fruits'),
('Tangerines','agriculture-produce','agriculture-produce--fresh-fruits'),
('Lemons','agriculture-produce','agriculture-produce--fresh-fruits'),
('Watermelon','agriculture-produce','agriculture-produce--tropical-and-specialty-fruits'),
('Guava','agriculture-produce','agriculture-produce--tropical-and-specialty-fruits'),
('Jackfruit','agriculture-produce','agriculture-produce--tropical-and-specialty-fruits'),
('Dragon fruit','agriculture-produce','agriculture-produce--tropical-and-specialty-fruits'),
('Tree tomato','agriculture-produce','agriculture-produce--tropical-and-specialty-fruits'),
('Roasted coffee beans','agriculture-produce','agriculture-produce--coffee-and-cocoa'),
('Cocoa beans','agriculture-produce','agriculture-produce--coffee-and-cocoa'),
('Fermented cocoa beans','agriculture-produce','agriculture-produce--coffee-and-cocoa'),
('Vanilla beans','agriculture-produce','agriculture-produce--tea-and-plantation-crops'),
('Dried mango','agriculture-produce','agriculture-produce--dried-produce'),
('Dried pineapple','agriculture-produce','agriculture-produce--dried-produce'),
('Dried banana','agriculture-produce','agriculture-produce--dried-produce'),
('Banana chips','agriculture-produce','agriculture-produce--dried-produce'),
('Dried papaya','agriculture-produce','agriculture-produce--dried-produce'),
('Dried jackfruit','agriculture-produce','agriculture-produce--dried-produce'),
('Dried tomatoes','agriculture-produce','agriculture-produce--dried-produce'),
('Dried chilli','agriculture-produce','agriculture-produce--dried-produce'),
('Black pepper','agriculture-produce','agriculture-produce--spices-and-herbs'),
('Ginger','agriculture-produce','agriculture-produce--spices-and-herbs'),
('Fruit tree seedlings','agriculture-produce','agriculture-produce--horticulture'),
('Banana suckers','agriculture-produce','agriculture-produce--horticulture'),
('Installation system — Maize grain','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Sorghum grain','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Rice paddy','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Milled rice','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Brown rice','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Parboiled rice','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dry beans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Kidney beans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Soybeans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Green grams','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Lentils','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Bambara nuts','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Sesame seed','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Cassava flour','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Sweet potatoes','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Irish potatoes','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Yams','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Cocoyam','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Potato starch','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Tomatoes','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Cabbage','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Carrots','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Onions','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Garlic','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Green pepper','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Chilli','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Eggplant','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Okra','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Cucumber','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Spinach','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Kale','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Amaranth','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Lettuce','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Swiss chard','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Broccoli','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Cauliflower','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Spring onions','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Leeks','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Celery','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Bananas','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Matoke','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Avocados','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Mangoes','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Pineapples','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Papaya','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Passion fruit','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Oranges','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Tangerines','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Lemons','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Watermelon','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Guava','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Jackfruit','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dragon fruit','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Tree tomato','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Roasted coffee beans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Cocoa beans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Fermented cocoa beans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Vanilla beans','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried mango','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried pineapple','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried banana','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Banana chips','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried papaya','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried jackfruit','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried tomatoes','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Dried chilli','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Black pepper','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Ginger','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Fruit tree seedlings','agriculture-produce','agriculture-produce--expanded-product-families'),
('Installation system — Banana suckers','agriculture-produce','agriculture-produce--expanded-product-families'),
('Hybrid maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Open-pollinated maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Drought-tolerant maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Early-maturing maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Quality-protein maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('White maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Yellow maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Sweet corn seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Popcorn seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Fodder maize seed','agro-inputs-seeds','agro-inputs-seeds--maize-seeds'),
('Rice seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Upland rice seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Lowland rice seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Wheat seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Sorghum seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Finger millet seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Pearl millet seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Barley seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Oat seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Rye seed','agro-inputs-seeds','agro-inputs-seeds--cereal-seeds'),
('Bean seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Soybean seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Green gram seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Cowpea seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Pigeon pea seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Chickpea seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Lentil seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Field pea seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Bambara seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Groundnut seed','agro-inputs-seeds','agro-inputs-seeds--legume-seeds'),
('Tomato seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Cabbage seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Pepper seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Chilli seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Onion seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Carrot seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Kale seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Spinach seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Cucumber seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Watermelon seed','agro-inputs-seeds','agro-inputs-seeds--vegetable-seeds'),
('Sunflower seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Sesame seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Canola seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Rapeseed seed','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Castor seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Cotton seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Flax seed','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Mustard seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Safflower seed','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Niger seed for planting','agro-inputs-seeds','agro-inputs-seeds--oilseed-seeds'),
('Seed potato','agro-inputs-seeds','agro-inputs-seeds--planting-materials'),
('Coffee seedlings','agro-inputs-seeds','agro-inputs-seeds--planting-materials'),
('Cocoa seedlings','agro-inputs-seeds','agro-inputs-seeds--planting-materials'),
('Tea seedlings','agro-inputs-seeds','agro-inputs-seeds--planting-materials'),
('Avocado seedlings','agro-inputs-seeds','agro-inputs-seeds--planting-materials'),
('Mango seedlings','agro-inputs-seeds','agro-inputs-seeds--planting-materials'),
('Urea','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('DAP','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('TSP','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('SSP','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('CAN','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('MOP','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('SOP','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('NPK fertilizer','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('MAP fertilizer','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('Water-soluble fertilizer','agro-inputs-seeds','agro-inputs-seeds--fertilizers'),
('Zinc sulphate','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Boron fertilizer','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Iron chelate','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Manganese sulphate','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Copper micronutrient','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Molybdenum fertilizer','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Calcium-boron','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Magnesium fertilizer','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Humic acid','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Fulvic acid','agro-inputs-seeds','agro-inputs-seeds--micronutrients'),
('Organic pellet fertilizer','agro-inputs-seeds','agro-inputs-seeds--organic-inputs'),
('Biofertilizer','agro-inputs-seeds','agro-inputs-seeds--organic-inputs'),
('2,4-D herbicide','agro-inputs-seeds','agro-inputs-seeds--crop-protection'),
('Copper fungicide','agro-inputs-seeds','agro-inputs-seeds--crop-protection'),
('Biofungicide','agro-inputs-seeds','agro-inputs-seeds--ipm-products'),
('Plant growth promoter','agro-inputs-seeds','agro-inputs-seeds--growth-regulators'),
('Seed priming agent','agro-inputs-seeds','agro-inputs-seeds--growth-regulators'),
('Seedling tray','agro-inputs-seeds','agro-inputs-seeds--greenhouse-inputs'),
('Rhodes grass seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Brachiaria seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Guinea grass seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Setaria seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Lucerne seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Desmodium seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Lablab seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Forage sorghum seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Clover seed','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Pasture seed mix','agro-inputs-seeds','agro-inputs-seeds--pasture-inputs'),
('Installation system — Hybrid maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Open-pollinated maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Drought-tolerant maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Early-maturing maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Quality-protein maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — White maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Yellow maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Sweet corn seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Popcorn seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Fodder maize seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Rice seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Upland rice seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Lowland rice seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Wheat seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Sorghum seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Finger millet seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Pearl millet seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Barley seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Oat seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Rye seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Bean seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Soybean seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Green gram seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Cowpea seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Pigeon pea seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Chickpea seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Lentil seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Field pea seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Bambara seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Groundnut seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Tomato seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Cabbage seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Pepper seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Chilli seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Onion seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Carrot seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Kale seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Spinach seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Cucumber seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Watermelon seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Sunflower seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Sesame seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Canola seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Rapeseed seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Castor seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Cotton seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Flax seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Mustard seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Safflower seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Niger seed for planting','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Seed potato','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Coffee seedlings','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Cocoa seedlings','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Tea seedlings','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Avocado seedlings','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Mango seedlings','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Urea','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — DAP','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — TSP','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — SSP','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — CAN','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — MOP','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — SOP','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — NPK fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — MAP fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Water-soluble fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Zinc sulphate','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Boron fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Iron chelate','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Manganese sulphate','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Copper micronutrient','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Molybdenum fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Calcium-boron','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Magnesium fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Humic acid','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Fulvic acid','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Organic pellet fertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Biofertilizer','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — 2,4-D herbicide','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Copper fungicide','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Biofungicide','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Plant growth promoter','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Seed priming agent','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Seedling tray','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Rhodes grass seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Brachiaria seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Guinea grass seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Setaria seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Lucerne seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Desmodium seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Lablab seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Forage sorghum seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Clover seed','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Installation system — Pasture seed mix','agro-inputs-seeds','agro-inputs-seeds--expanded-product-families'),
('Maize flour','food-beverage','food-beverage--staples'),
('Wheat flour','food-beverage','food-beverage--staples'),
('Rice','food-beverage','food-beverage--staples'),
('Beans','food-beverage','food-beverage--staples'),
('Tomato paste','food-beverage','food-beverage--cooking-ingredients'),
('Soybean oil','food-beverage','food-beverage--edible-oils'),
('Groundnut oil','food-beverage','food-beverage--edible-oils'),
('Sesame oil','food-beverage','food-beverage--edible-oils'),
('Goat meat','food-beverage','food-beverage--meat'),
('Mutton','food-beverage','food-beverage--meat'),
('Pork','food-beverage','food-beverage--meat'),
('Chicken','food-beverage','food-beverage--meat'),
('Chicken breast','food-beverage','food-beverage--meat'),
('Chicken thighs','food-beverage','food-beverage--meat'),
('Sausages','food-beverage','food-beverage--meat'),
('Processed meat','food-beverage','food-beverage--meat'),
('Dried fish','food-beverage','food-beverage--fish'),
('Fresh tomatoes','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh onions','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh potatoes','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh cabbage','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh carrots','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh bananas','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh mangoes','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh pineapples','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh avocados','food-beverage','food-beverage--fruits-and-vegetables'),
('Fresh oranges','food-beverage','food-beverage--fruits-and-vegetables'),
('Fruit juice','food-beverage','food-beverage--beverages'),
('Coffee','food-beverage','food-beverage--beverages'),
('Cocoa drink','food-beverage','food-beverage--beverages'),
('Potato crisps','food-beverage','food-beverage--snacks'),
('Frozen chicken','food-beverage','food-beverage--frozen-foods'),
('Frozen beef','food-beverage','food-beverage--frozen-foods'),
('Frozen vegetables','food-beverage','food-beverage--frozen-foods'),
('Canned beans','food-beverage','food-beverage--canned-foods'),
('Canned tomatoes','food-beverage','food-beverage--canned-foods'),
('Canned fruit','food-beverage','food-beverage--canned-foods'),
('Canned vegetables','food-beverage','food-beverage--canned-foods'),
('Canned meat','food-beverage','food-beverage--canned-foods'),
('Chilli sauce','food-beverage','food-beverage--condiments'),
('Peanut butter','food-beverage','food-beverage--specialty-foods'),
('Dried fruit mix','food-beverage','food-beverage--specialty-foods'),
('Gluten-free flour','food-beverage','food-beverage--specialty-foods'),
('Installation system — Maize flour','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Wheat flour','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Rice','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Beans','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Tomato paste','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Soybean oil','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Groundnut oil','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Sesame oil','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Goat meat','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Mutton','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Pork','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Chicken','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Chicken breast','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Chicken thighs','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Sausages','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Processed meat','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Dried fish','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh tomatoes','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh onions','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh potatoes','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh cabbage','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh carrots','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh bananas','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh mangoes','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh pineapples','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh avocados','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fresh oranges','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Fruit juice','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Coffee','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Cocoa drink','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Potato crisps','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Frozen chicken','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Frozen beef','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Frozen vegetables','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Canned beans','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Canned tomatoes','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Canned fruit','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Canned vegetables','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Canned meat','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Chilli sauce','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Peanut butter','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Dried fruit mix','food-beverage','food-beverage--expanded-product-families'),
('Installation system — Gluten-free flour','food-beverage','food-beverage--expanded-product-families'),
('Replacement component — Maize flour','food-beverage','food-beverage--expanded-product-families'),
('Replacement component — Wheat flour','food-beverage','food-beverage--expanded-product-families'),
('Replacement component — Rice','food-beverage','food-beverage--expanded-product-families'),
('Replacement component — Beans','food-beverage','food-beverage--expanded-product-families'),
('Broiler starter','livestock-feeds','livestock-feeds--poultry-feed'),
('Broiler grower','livestock-feeds','livestock-feeds--poultry-feed'),
('Broiler finisher','livestock-feeds','livestock-feeds--poultry-feed'),
('Layer mash','livestock-feeds','livestock-feeds--poultry-feed'),
('Layer pellets','livestock-feeds','livestock-feeds--poultry-feed'),
('Chick mash','livestock-feeds','livestock-feeds--poultry-feed'),
('Poultry concentrate','livestock-feeds','livestock-feeds--poultry-feed'),
('Poultry premix','livestock-feeds','livestock-feeds--poultry-feed'),
('Poultry grit','livestock-feeds','livestock-feeds--poultry-feed'),
('Quail feed','livestock-feeds','livestock-feeds--poultry-feed'),
('Dairy meal','livestock-feeds','livestock-feeds--cattle-feed'),
('Calf starter','livestock-feeds','livestock-feeds--cattle-feed'),
('Calf grower','livestock-feeds','livestock-feeds--cattle-feed'),
('Cattle concentrate','livestock-feeds','livestock-feeds--cattle-feed'),
('Beef finisher','livestock-feeds','livestock-feeds--cattle-feed'),
('Mineral lick','livestock-feeds','livestock-feeds--cattle-feed'),
('Protein supplement','livestock-feeds','livestock-feeds--cattle-feed'),
('Molasses feed','livestock-feeds','livestock-feeds--cattle-feed'),
('Dairy premix','livestock-feeds','livestock-feeds--cattle-feed'),
('Pig starter','livestock-feeds','livestock-feeds--pig-feed'),
('Pig grower','livestock-feeds','livestock-feeds--pig-feed'),
('Pig finisher','livestock-feeds','livestock-feeds--pig-feed'),
('Sow feed','livestock-feeds','livestock-feeds--pig-feed'),
('Pig concentrate','livestock-feeds','livestock-feeds--pig-feed'),
('Pig premix','livestock-feeds','livestock-feeds--pig-feed'),
('Piglet creep feed','livestock-feeds','livestock-feeds--pig-feed'),
('Pig protein supplement','livestock-feeds','livestock-feeds--pig-feed'),
('Pig mineral supplement','livestock-feeds','livestock-feeds--pig-feed'),
('Pig feed additive','livestock-feeds','livestock-feeds--pig-feed'),
('Goat concentrate','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Sheep concentrate','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Goat mineral lick','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Sheep mineral lick','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Small-ruminant pellets','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Lamb creep feed','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Hay pellets','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Forage pellets','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Mineral supplement','livestock-feeds','livestock-feeds--goat-and-sheep-feed'),
('Fodder pellets','livestock-feeds','livestock-feeds--fodder'),
('Vitamin premix','livestock-feeds','livestock-feeds--supplements'),
('Mineral premix','livestock-feeds','livestock-feeds--supplements'),
('Calcium supplement','livestock-feeds','livestock-feeds--supplements'),
('Phosphorus supplement','livestock-feeds','livestock-feeds--supplements'),
('Probiotic supplement','livestock-feeds','livestock-feeds--supplements'),
('Amino acid supplement','livestock-feeds','livestock-feeds--supplements'),
('Trace mineral mix','livestock-feeds','livestock-feeds--supplements'),
('Feed binder','livestock-feeds','livestock-feeds--supplements'),
('Poultry drinker','livestock-feeds','livestock-feeds--poultry-equipment'),
('Poultry feeder','livestock-feeds','livestock-feeds--poultry-equipment'),
('Nipple drinker','livestock-feeds','livestock-feeds--poultry-equipment'),
('Poultry cage','livestock-feeds','livestock-feeds--poultry-equipment'),
('Chick guard','livestock-feeds','livestock-feeds--poultry-equipment'),
('Poultry crate','livestock-feeds','livestock-feeds--poultry-equipment'),
('Dairy pump','livestock-feeds','livestock-feeds--dairy-equipment'),
('Installation system — Broiler starter','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Broiler grower','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Broiler finisher','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Layer mash','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Layer pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Chick mash','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry grit','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Quail feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Dairy meal','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Calf starter','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Calf grower','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Cattle concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Beef finisher','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Mineral lick','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Protein supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Molasses feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Dairy premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig starter','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig grower','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig finisher','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Sow feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Piglet creep feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig protein supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig mineral supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Pig feed additive','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Goat concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Sheep concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Goat mineral lick','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Sheep mineral lick','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Small-ruminant pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Lamb creep feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Hay pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Forage pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Mineral supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Fodder pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Vitamin premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Mineral premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Calcium supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Phosphorus supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Probiotic supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Amino acid supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Trace mineral mix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Feed binder','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry drinker','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry feeder','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Nipple drinker','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry cage','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Chick guard','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Poultry crate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Installation system — Dairy pump','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Broiler starter','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Broiler grower','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Broiler finisher','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Layer mash','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Layer pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Chick mash','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry grit','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Quail feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Dairy meal','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Calf starter','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Calf grower','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Cattle concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Beef finisher','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Mineral lick','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Protein supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Molasses feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Dairy premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig starter','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig grower','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig finisher','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Sow feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Piglet creep feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig protein supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig mineral supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Pig feed additive','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Goat concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Sheep concentrate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Goat mineral lick','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Sheep mineral lick','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Small-ruminant pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Lamb creep feed','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Hay pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Forage pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Mineral supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Fodder pellets','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Vitamin premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Mineral premix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Calcium supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Phosphorus supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Probiotic supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Amino acid supplement','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Trace mineral mix','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Feed binder','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry drinker','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry feeder','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Nipple drinker','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry cage','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Chick guard','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Poultry crate','livestock-feeds','livestock-feeds--expanded-product-families'),
('Replacement component — Dairy pump','livestock-feeds','livestock-feeds--expanded-product-families'),
('Plumb bob','hardware-tools','hardware-tools--measuring'),
('Site marker paint','building-construction','building-construction--site-and-earthworks'),
('Ready-mix concrete','building-construction','building-construction--concrete'),
('Concrete repair mortar','building-construction','building-construction--concrete'),
('Non-shrink grout','cement-aggregates','cement-aggregates--mortars'),
('Concrete bonding agent','building-construction','building-construction--concrete'),
('Concrete curing compound','cement-aggregates','cement-aggregates--quality-inputs'),
('Concrete release agent','building-construction','building-construction--concrete'),
('Concrete accelerator','building-construction','building-construction--concrete'),
('Concrete retarder','building-construction','building-construction--concrete'),
('Concrete plasticizer','building-construction','building-construction--concrete'),
('Concrete waterproofing additive','building-construction','building-construction--concrete'),
('Clay brick','building-construction','building-construction--masonry'),
('Solid concrete block','building-construction','building-construction--masonry'),
('Hollow concrete block','building-construction','building-construction--masonry'),
('AAC block','building-construction','building-construction--masonry'),
('Interlocking block','building-construction','building-construction--masonry'),
('Masonry mortar','cement-aggregates','cement-aggregates--mortars'),
('Brick adhesive','building-construction','building-construction--masonry'),
('Masonry reinforcement','building-construction','building-construction--masonry'),
('TMT bar','steel-metal','steel-metal--reinforcement'),
('Binding wire','steel-metal','steel-metal--reinforcement'),
('BRC mesh','steel-metal','steel-metal--reinforcement'),
('Welded wire mesh','building-construction','building-construction--reinforcement'),
('Rebar coupler','steel-metal','steel-metal--reinforcement'),
('Rebar spacer','steel-metal','steel-metal--reinforcement'),
('Rebar chair','steel-metal','steel-metal--reinforcement'),
('Threaded rebar coupler','building-construction','building-construction--reinforcement'),
('Mechanical rebar splice','building-construction','building-construction--reinforcement'),
('Rebar cap','steel-metal','steel-metal--reinforcement'),
('Formwork timber','building-construction','building-construction--formwork'),
('Steel prop','building-construction','building-construction--formwork'),
('Formwork release oil','building-construction','building-construction--formwork'),
('Scaffold tube','building-construction','building-construction--scaffolding'),
('Scaffold coupler','building-construction','building-construction--scaffolding'),
('Frame scaffold','building-construction','building-construction--scaffolding'),
('Ringlock scaffold','building-construction','building-construction--scaffolding'),
('Cuplock scaffold','building-construction','building-construction--scaffolding'),
('Scaffold plank','building-construction','building-construction--scaffolding'),
('Scaffold ladder','hardware-tools','hardware-tools--ladders-and-access'),
('Scaffold stair','building-construction','building-construction--scaffolding'),
('Scaffold caster','building-construction','building-construction--scaffolding'),
('DPC','building-construction','building-construction--waterproofing'),
('DPM','building-construction','building-construction--waterproofing'),
('Bituminous membrane','building-construction','building-construction--waterproofing'),
('APP membrane','building-construction','building-construction--waterproofing'),
('PVC membrane','building-construction','building-construction--waterproofing'),
('Cementitious waterproofing','building-construction','building-construction--waterproofing'),
('Liquid membrane','roofing-ceilings','roofing-ceilings--roof-waterproofing'),
('Bitumen primer','building-construction','building-construction--waterproofing'),
('Waterproofing tape','building-construction','building-construction--waterproofing'),
('Epoxy resin','chemicals-industrial','chemicals-industrial--consumables'),
('Epoxy grout','cement-aggregates','cement-aggregates--mortars'),
('PU sealant','building-construction','building-construction--construction-chemicals'),
('Silicone sealant','building-construction','building-construction--construction-chemicals'),
('Acrylic sealant','building-construction','building-construction--construction-chemicals'),
('Construction adhesive','hardware-tools','hardware-tools--adhesives'),
('Concrete crack filler','building-construction','building-construction--construction-chemicals'),
('Anchoring adhesive','building-construction','building-construction--construction-chemicals'),
('Ceramic tile','building-construction','building-construction--flooring'),
('Porcelain tile','building-construction','building-construction--flooring'),
('Natural stone tile','building-construction','building-construction--flooring'),
('Terrazzo tile','building-construction','building-construction--flooring'),
('Cement tile','building-construction','building-construction--flooring'),
('Epoxy flooring','building-construction','building-construction--flooring'),
('Steel door','building-construction','building-construction--doors-and-windows'),
('Wooden door','building-construction','building-construction--doors-and-windows'),
('Flush door','building-construction','building-construction--doors-and-windows'),
('Fire door','building-construction','building-construction--doors-and-windows'),
('Garage door','building-construction','building-construction--doors-and-windows'),
('Aluminium door','building-construction','building-construction--doors-and-windows'),
('uPVC door','building-construction','building-construction--doors-and-windows'),
('Aluminium window','building-construction','building-construction--doors-and-windows'),
('uPVC window','building-construction','building-construction--doors-and-windows'),
('Steel window','building-construction','building-construction--doors-and-windows'),
('Gypsum board','roofing-ceilings','roofing-ceilings--ceiling-boards'),
('Cement board','roofing-ceilings','roofing-ceilings--ceiling-boards'),
('Fibre-cement board','roofing-ceilings','roofing-ceilings--ceiling-boards'),
('Acoustic board','building-construction','building-construction--interior-construction'),
('Ceiling channel','roofing-ceilings','roofing-ceilings--suspended-ceilings'),
('Ceiling hanger','roofing-ceilings','roofing-ceilings--suspended-ceilings'),
('Door lock','building-construction','building-construction--construction-hardware'),
('Door hinge','building-construction','building-construction--construction-hardware'),
('Door closer','building-construction','building-construction--construction-hardware'),
('Door handle','building-construction','building-construction--construction-hardware'),
('Nail','building-construction','building-construction--construction-hardware'),
('Wood screw','hardware-tools','hardware-tools--fasteners'),
('Concrete screw','hardware-tools','hardware-tools--anchors'),
('Expansion anchor','hardware-tools','hardware-tools--anchors'),
('Construction bolt','building-construction','building-construction--construction-hardware'),
('Concrete pipe','cement-aggregates','cement-aggregates--precast'),
('PVC drainage pipe','plumbing-sanitary','plumbing-sanitary--drainage'),
('Catch basin','building-construction','building-construction--drainage'),
('Drain channel','building-construction','building-construction--drainage'),
('Drainage geotextile','building-construction','building-construction--drainage'),
('Steel beam','building-construction','building-construction--structural-products'),
('Steel column','building-construction','building-construction--structural-products'),
('Steel truss','steel-metal','steel-metal--structural-sections'),
('Steel stair','building-construction','building-construction--structural-products'),
('Safety barrier','building-construction','building-construction--site-consumables'),
('Dust sheet','building-construction','building-construction--site-consumables'),
('Wheelbarrow','hardware-tools','hardware-tools--garden-tools'),
('Construction rope','building-construction','building-construction--site-consumables'),
('Warning tape','building-construction','building-construction--site-consumables'),
('Installation system — Plumb bob','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Site marker paint','building-construction','building-construction--expanded-product-families'),
('Installation system — Ready-mix concrete','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete repair mortar','building-construction','building-construction--expanded-product-families'),
('Installation system — Non-shrink grout','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete bonding agent','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete curing compound','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Concrete release agent','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete accelerator','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete retarder','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete plasticizer','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete waterproofing additive','building-construction','building-construction--expanded-product-families'),
('Installation system — Clay brick','building-construction','building-construction--expanded-product-families'),
('Installation system — Solid concrete block','building-construction','building-construction--expanded-product-families'),
('Installation system — Hollow concrete block','building-construction','building-construction--expanded-product-families'),
('Installation system — AAC block','building-construction','building-construction--expanded-product-families'),
('Installation system — Interlocking block','building-construction','building-construction--expanded-product-families'),
('Installation system — Masonry mortar','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — Brick adhesive','building-construction','building-construction--expanded-product-families'),
('Installation system — Masonry reinforcement','building-construction','building-construction--expanded-product-families'),
('Installation system — TMT bar','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Binding wire','steel-metal','steel-metal--expanded-product-families'),
('Installation system — BRC mesh','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Welded wire mesh','building-construction','building-construction--expanded-product-families'),
('Installation system — Rebar coupler','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Rebar spacer','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Rebar chair','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Threaded rebar coupler','building-construction','building-construction--expanded-product-families'),
('Installation system — Mechanical rebar splice','building-construction','building-construction--expanded-product-families'),
('Installation system — Rebar cap','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Formwork timber','building-construction','building-construction--expanded-product-families'),
('Installation system — Steel prop','building-construction','building-construction--expanded-product-families'),
('Installation system — Formwork release oil','building-construction','building-construction--expanded-product-families'),
('Installation system — Scaffold tube','building-construction','building-construction--expanded-product-families'),
('Installation system — Scaffold coupler','building-construction','building-construction--expanded-product-families'),
('Installation system — Frame scaffold','building-construction','building-construction--expanded-product-families'),
('Installation system — Ringlock scaffold','building-construction','building-construction--expanded-product-families'),
('Installation system — Cuplock scaffold','building-construction','building-construction--expanded-product-families'),
('Installation system — Scaffold plank','building-construction','building-construction--expanded-product-families'),
('Installation system — Scaffold ladder','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Scaffold stair','building-construction','building-construction--expanded-product-families'),
('Installation system — Scaffold caster','building-construction','building-construction--expanded-product-families'),
('Installation system — DPC','building-construction','building-construction--expanded-product-families'),
('Installation system — DPM','building-construction','building-construction--expanded-product-families'),
('Installation system — Bituminous membrane','building-construction','building-construction--expanded-product-families'),
('Installation system — APP membrane','building-construction','building-construction--expanded-product-families'),
('Installation system — PVC membrane','building-construction','building-construction--expanded-product-families'),
('Installation system — Cementitious waterproofing','building-construction','building-construction--expanded-product-families'),
('Installation system — Liquid membrane','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Bitumen primer','building-construction','building-construction--expanded-product-families'),
('Installation system — Waterproofing tape','building-construction','building-construction--expanded-product-families'),
('Installation system — Epoxy resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Epoxy grout','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — PU sealant','building-construction','building-construction--expanded-product-families'),
('Installation system — Silicone sealant','building-construction','building-construction--expanded-product-families'),
('Installation system — Acrylic sealant','building-construction','building-construction--expanded-product-families'),
('Installation system — Construction adhesive','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Concrete crack filler','building-construction','building-construction--expanded-product-families'),
('Installation system — Anchoring adhesive','building-construction','building-construction--expanded-product-families'),
('Installation system — Ceramic tile','building-construction','building-construction--expanded-product-families'),
('Installation system — Porcelain tile','building-construction','building-construction--expanded-product-families'),
('Installation system — Natural stone tile','building-construction','building-construction--expanded-product-families'),
('Installation system — Terrazzo tile','building-construction','building-construction--expanded-product-families'),
('Installation system — Cement tile','building-construction','building-construction--expanded-product-families'),
('Installation system — Epoxy flooring','building-construction','building-construction--expanded-product-families'),
('Installation system — Steel door','building-construction','building-construction--expanded-product-families'),
('Installation system — Wooden door','building-construction','building-construction--expanded-product-families'),
('Installation system — Flush door','building-construction','building-construction--expanded-product-families'),
('Installation system — Fire door','building-construction','building-construction--expanded-product-families'),
('Installation system — Garage door','building-construction','building-construction--expanded-product-families'),
('Installation system — Aluminium door','building-construction','building-construction--expanded-product-families'),
('Installation system — uPVC door','building-construction','building-construction--expanded-product-families'),
('Installation system — Aluminium window','building-construction','building-construction--expanded-product-families'),
('Installation system — uPVC window','building-construction','building-construction--expanded-product-families'),
('Installation system — Steel window','building-construction','building-construction--expanded-product-families'),
('Installation system — Gypsum board','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Cement board','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Fibre-cement board','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Acoustic board','building-construction','building-construction--expanded-product-families'),
('Installation system — Ceiling channel','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Ceiling hanger','roofing-ceilings','roofing-ceilings--expanded-product-families'),
('Installation system — Door lock','building-construction','building-construction--expanded-product-families'),
('Installation system — Door hinge','building-construction','building-construction--expanded-product-families'),
('Installation system — Door closer','building-construction','building-construction--expanded-product-families'),
('Installation system — Door handle','building-construction','building-construction--expanded-product-families'),
('Installation system — Nail','building-construction','building-construction--expanded-product-families'),
('Installation system — Wood screw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Concrete screw','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Expansion anchor','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Construction bolt','building-construction','building-construction--expanded-product-families'),
('Installation system — Concrete pipe','cement-aggregates','cement-aggregates--expanded-product-families'),
('Installation system — PVC drainage pipe','plumbing-sanitary','plumbing-sanitary--expanded-product-families'),
('Installation system — Catch basin','building-construction','building-construction--expanded-product-families'),
('Installation system — Drain channel','building-construction','building-construction--expanded-product-families'),
('Installation system — Drainage geotextile','building-construction','building-construction--expanded-product-families'),
('Installation system — Steel beam','building-construction','building-construction--expanded-product-families'),
('Installation system — Steel column','building-construction','building-construction--expanded-product-families'),
('Installation system — Steel truss','steel-metal','steel-metal--expanded-product-families'),
('Installation system — Steel stair','building-construction','building-construction--expanded-product-families'),
('Installation system — Safety barrier','building-construction','building-construction--expanded-product-families'),
('Installation system — Dust sheet','building-construction','building-construction--expanded-product-families'),
('Installation system — Wheelbarrow','hardware-tools','hardware-tools--expanded-product-families'),
('Installation system — Construction rope','building-construction','building-construction--expanded-product-families'),
('Installation system — Warning tape','building-construction','building-construction--expanded-product-families'),
('OPC cement','cement-aggregates','cement-aggregates--cement-types'),
('PPC cement','cement-aggregates','cement-aggregates--cement-types'),
('White cement','cement-aggregates','cement-aggregates--cement-types'),
('Masonry cement','cement-aggregates','cement-aggregates--cement-types'),
('Rapid-hardening cement','cement-aggregates','cement-aggregates--cement-types'),
('High-strength cement','cement-aggregates','cement-aggregates--cement-types'),
('Sulphate-resistant cement','cement-aggregates','cement-aggregates--cement-types'),
('Low-heat cement','cement-aggregates','cement-aggregates--cement-types'),
('Hydraulic cement','cement-aggregates','cement-aggregates--cement-types'),
('Limestone cement','cement-aggregates','cement-aggregates--cement-types'),
('C15 concrete','cement-aggregates','cement-aggregates--concrete-mixes'),
('C20 concrete','cement-aggregates','cement-aggregates--concrete-mixes')
on conflict (n) do update set m = excluded.m, s = excluded.s;
