-- 0065 part 7 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Replacement component — Iron removal filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Activated carbon filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Sand filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Multimedia filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Cartridge filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Bag filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Disc filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Screen filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Membrane filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Ceramic filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Microfilter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — RO membrane','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Membrane housing','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — High-pressure pump','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — RO pressure vessel','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Antiscalant dosing pump','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — RO control panel','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — RO cleaning system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Activated carbon','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Ion exchange resin','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Water treatment plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — RO plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Ultrafiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Nanofiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — UV water purifier','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Chlorination system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Water softener','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Iron removal filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Activated carbon filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Sand filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Multimedia filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Cartridge filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Bag filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Disc filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Screen filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Membrane filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Ceramic filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Microfilter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — RO membrane','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Membrane housing','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — High-pressure pump','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — RO pressure vessel','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Antiscalant dosing pump','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — RO control panel','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — RO cleaning system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Activated carbon','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Ion exchange resin','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Water treatment plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — RO plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Ultrafiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Nanofiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — UV water purifier','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Chlorination system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Water softener','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Iron removal filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Activated carbon filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Sand filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Multimedia filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Cartridge filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Bag filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Disc filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Testing equipment — Screen filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Copy paper','office-and-business-supplies','office-and-business-supplies--components'),
('Printer toner','office-and-business-supplies','office-and-business-supplies--components'),
('Printer ink','office-and-business-supplies','office-and-business-supplies--components'),
('Staples','office-and-business-supplies','office-and-business-supplies--components'),
('Paper clips','office-and-business-supplies','office-and-business-supplies--components'),
('Binder clips','office-and-business-supplies','office-and-business-supplies--components'),
('Rubber bands','office-and-business-supplies','office-and-business-supplies--components'),
('Sticky notes','office-and-business-supplies','office-and-business-supplies--components'),
('Envelopes','office-and-business-supplies','office-and-business-supplies--components'),
('Notepads','office-and-business-supplies','office-and-business-supplies--components'),
('Storage folder','office-and-business-supplies','office-and-business-supplies--systems'),
('Pen holder','office-and-business-supplies','office-and-business-supplies--accessories'),
('Stapler','office-and-business-supplies','office-and-business-supplies--accessories'),
('Staple remover','office-and-business-supplies','office-and-business-supplies--accessories'),
('Hole punch','office-and-business-supplies','office-and-business-supplies--accessories'),
('Tape dispenser','office-and-business-supplies','office-and-business-supplies--accessories'),
('Letter opener','office-and-business-supplies','office-and-business-supplies--accessories'),
('Desk calendar','office-and-business-supplies','office-and-business-supplies--accessories'),
('Presentation board','office-and-business-supplies','office-and-business-supplies--service'),
('Display stand','office-and-business-supplies','office-and-business-supplies--service'),
('Reception counter','office-and-business-supplies','office-and-business-supplies--replacement-parts'),
('Key cabinet','office-and-business-supplies','office-and-business-supplies--replacement-parts'),
('Fireproof cabinet','office-and-business-supplies','office-and-business-supplies--replacement-parts'),
('Laptop lock','office-and-business-supplies','office-and-business-supplies--replacement-parts'),
('Installation system — Copy paper','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Printer toner','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Printer ink','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Staples','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Paper clips','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Binder clips','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Rubber bands','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Sticky notes','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Envelopes','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Notepads','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Storage folder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Pen holder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Stapler','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Staple remover','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Hole punch','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Tape dispenser','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Letter opener','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Desk calendar','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Presentation board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Display stand','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Reception counter','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Key cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Fireproof cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Laptop lock','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Copy paper','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Printer toner','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Printer ink','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Staples','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Paper clips','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Binder clips','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Rubber bands','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Sticky notes','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Envelopes','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Notepads','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Storage folder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Pen holder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Stapler','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Staple remover','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Hole punch','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Tape dispenser','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Letter opener','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Desk calendar','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Presentation board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Display stand','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Reception counter','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Key cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Fireproof cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Laptop lock','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Copy paper','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Printer toner','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Printer ink','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Staples','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Paper clips','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Binder clips','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Rubber bands','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Sticky notes','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Envelopes','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Notepads','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Storage folder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Pen holder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Stapler','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Staple remover','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Hole punch','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Tape dispenser','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Letter opener','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Desk calendar','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Presentation board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Display stand','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Reception counter','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Key cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Fireproof cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Laptop lock','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Office desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Executive desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Workstation','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Office chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Visitor chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Conference table','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Reception desk','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Filing cabinet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Bookcase','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Meeting chair','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Binding machine','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Laminator','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Label printer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Thin client','ict-and-telecom-equipment','ict-and-telecom-equipment--vehicles-core'),
('Server','ict-and-telecom-equipment','ict-and-telecom-equipment--vehicles-core'),
('Rack server','ict-and-telecom-equipment','ict-and-telecom-equipment--vehicles-core'),
('Tower server','ict-and-telecom-equipment','ict-and-telecom-equipment--vehicles-core'),
('LED monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--equipment'),
('4K monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--equipment'),
('Conference display','ict-and-telecom-equipment','ict-and-telecom-equipment--equipment'),
('Router','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Firewall','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Network controller','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Network bridge','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Media converter','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Network gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--components'),
('Fibre cable','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('Patch panel','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('Keystone jack','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('Faceplate','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('Cable manager','ict-and-telecom-equipment','ict-and-telecom-equipment--systems'),
('Single-mode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('Multimode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('Fibre patch cord','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('Fibre pigtail','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('ODF','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('Fibre splice closure','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('Fibre termination box','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('SFP module','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('Fibre splitter','ict-and-telecom-equipment','ict-and-telecom-equipment--accessories'),
('VoIP gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('IP phone','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('PBX','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('Paging system','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('Telephone exchange','ict-and-telecom-equipment','ict-and-telecom-equipment--service'),
('Server rack','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Rack cabinet','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Rack PDU','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Server rail','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('KVM switch','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Server console','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Rack fan','ict-and-telecom-equipment','ict-and-telecom-equipment--replacement-parts'),
('Installation system — Thin client','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Rack server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Tower server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — LED monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — 4K monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Conference display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Firewall','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Network controller','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Network bridge','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Media converter','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Network gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Fibre cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Patch panel','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Keystone jack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Faceplate','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Cable manager','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Single-mode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Multimode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Fibre patch cord','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Fibre pigtail','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — ODF','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Fibre splice closure','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Fibre termination box','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — SFP module','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Fibre splitter','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — VoIP gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — IP phone','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — PBX','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Paging system','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Telephone exchange','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Server rack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Rack cabinet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Rack PDU','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Server rail','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — KVM switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Server console','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Installation system — Rack fan','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Thin client','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Rack server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Tower server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — LED monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — 4K monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Conference display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Firewall','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Network controller','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Network bridge','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Media converter','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Network gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — CAT5e cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — CAT6 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — CAT6A cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — CAT7 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Fibre cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Patch panel','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Keystone jack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Faceplate','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Cable manager','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Single-mode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Multimode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Fibre patch cord','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Fibre pigtail','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — ODF','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Fibre splice closure','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Fibre termination box','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — SFP module','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Fibre splitter','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — VoIP gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — IP phone','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — PBX','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Paging system','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Telephone exchange','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Server rack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Rack cabinet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Rack PDU','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Server rail','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Cable tray','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — KVM switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Server console','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Replacement component — Rack fan','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Thin client','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Rack server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Tower server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — LED monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — 4K monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Conference display','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Router','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Firewall','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Network controller','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Network bridge','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Media converter','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Network gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — CAT5e cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — CAT6 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — CAT6A cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — CAT7 cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Fibre cable','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Patch panel','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Keystone jack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Faceplate','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Cable manager','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Single-mode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Multimode fibre','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Fibre patch cord','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Fibre pigtail','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — ODF','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Fibre splice closure','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Fibre termination box','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — SFP module','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Fibre splitter','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — VoIP gateway','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — IP phone','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — PBX','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Paging system','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Telephone exchange','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Server rack','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Rack cabinet','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Rack PDU','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Server rail','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Cable tray','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — KVM switch','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Server console','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Service equipment — Rack fan','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Thin client','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Rack server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — Tower server','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Testing equipment — LED monitor','ict-and-telecom-equipment','ict-and-telecom-equipment--expanded-product-families'),
('Commercial cooker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Gas range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Electric range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Commercial oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Convection oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Deck oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Deep fryer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Salamander','hospitality-and-catering-supplies','hospitality-and-catering-supplies--vehicles-core'),
('Upright refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Chest freezer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Display chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Undercounter refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Bottle cooler','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Ice maker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Blast chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Cold display case','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Freezer room','hospitality-and-catering-supplies','hospitality-and-catering-supplies--equipment'),
('Planetary mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--components'),
('Spiral mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--components'),
('Food processor','hospitality-and-catering-supplies','hospitality-and-catering-supplies--components'),
('Vegetable cutter','hospitality-and-catering-supplies','hospitality-and-catering-supplies--components'),
('Blender','hospitality-and-catering-supplies','hospitality-and-catering-supplies--components'),
('Juicer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--components'),
('Chafing dish','hospitality-and-catering-supplies','hospitality-and-catering-supplies--systems'),
('Bain-marie','hospitality-and-catering-supplies','hospitality-and-catering-supplies--systems'),
('Display warmer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--systems'),
('Mug','hospitality-and-catering-supplies','hospitality-and-catering-supplies--accessories'),
('Cutlery set','hospitality-and-catering-supplies','hospitality-and-catering-supplies--accessories'),
('Serving spoon','hospitality-and-catering-supplies','hospitality-and-catering-supplies--accessories'),
('Serving fork','hospitality-and-catering-supplies','hospitality-and-catering-supplies--accessories'),
('Luggage rack','hospitality-and-catering-supplies','hospitality-and-catering-supplies--service'),
('Restaurant table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--replacement-parts'),
('Banquet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--replacement-parts'),
('Buffet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--replacement-parts'),
('Outdoor table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--replacement-parts'),
('Installation system — Commercial cooker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Gas range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Electric range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Commercial oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Convection oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Deck oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Deep fryer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Salamander','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Upright refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Chest freezer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Display chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Undercounter refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Bottle cooler','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Ice maker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Blast chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Cold display case','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Freezer room','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Planetary mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Spiral mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Food processor','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Vegetable cutter','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Blender','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Juicer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Chafing dish','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Bain-marie','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Display warmer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Mug','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Cutlery set','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Serving spoon','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Serving fork','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Luggage rack','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Restaurant table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Banquet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Buffet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Installation system — Outdoor table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Commercial cooker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Gas range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Electric range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Commercial oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Convection oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Deck oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Deep fryer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Salamander','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Upright refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Chest freezer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Display chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Undercounter refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Bottle cooler','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Ice maker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Blast chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Cold display case','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Freezer room','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Planetary mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Spiral mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Food processor','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Vegetable cutter','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Blender','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Juicer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Chafing dish','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Bain-marie','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Display warmer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Mug','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Cutlery set','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Serving spoon','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Serving fork','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Luggage rack','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Restaurant table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Banquet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Buffet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Replacement component — Outdoor table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Commercial cooker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Gas range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Electric range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Commercial oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Convection oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Deck oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Deep fryer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Salamander','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Upright refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Chest freezer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Display chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Undercounter refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Bottle cooler','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Ice maker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Blast chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Cold display case','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Freezer room','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Planetary mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Spiral mixer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Food processor','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Vegetable cutter','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Blender','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Juicer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Chafing dish','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Bain-marie','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Display warmer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Mug','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Cutlery set','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Serving spoon','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Serving fork','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Luggage rack','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Restaurant table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Banquet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Buffet table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Service equipment — Outdoor table','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Commercial cooker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Gas range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Electric range','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Commercial oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Convection oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Deck oven','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Deep fryer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Salamander','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Upright refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Chest freezer','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Display chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Undercounter refrigerator','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Bottle cooler','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Ice maker','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Blast chiller','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Cold display case','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('Testing equipment — Freezer room','hospitality-and-catering-supplies','hospitality-and-catering-supplies--expanded-product-families'),
('IP camera','security-and-surveillance','security-and-surveillance--core'),
('Dome camera','security-and-surveillance','security-and-surveillance--core'),
('Bullet camera','security-and-surveillance','security-and-surveillance--core'),
('PTZ camera','security-and-surveillance','security-and-surveillance--core'),
('Turret camera','security-and-surveillance','security-and-surveillance--core'),
('Fisheye camera','security-and-surveillance','security-and-surveillance--core'),
('Thermal camera','security-and-surveillance','security-and-surveillance--core'),
('ANPR camera','security-and-surveillance','security-and-surveillance--core'),
('Outdoor camera','security-and-surveillance','security-and-surveillance--core'),
('Long-range camera','security-and-surveillance','security-and-surveillance--core'),
('NVR','security-and-surveillance','security-and-surveillance--equipment'),
('DVR','security-and-surveillance','security-and-surveillance--equipment'),
('Hybrid recorder','security-and-surveillance','security-and-surveillance--equipment'),
('CCTV hard drive','security-and-surveillance','security-and-surveillance--equipment'),
('Video encoder','security-and-surveillance','security-and-surveillance--equipment'),
('Video decoder','security-and-surveillance','security-and-surveillance--equipment'),
('Recording appliance','security-and-surveillance','security-and-surveillance--equipment'),
('Backup recorder','security-and-surveillance','security-and-surveillance--equipment'),
('Network recorder','security-and-surveillance','security-and-surveillance--equipment'),
('Access controller','security-and-surveillance','security-and-surveillance--consumables'),
('Fingerprint reader','security-and-surveillance','security-and-surveillance--consumables'),
('Face recognition terminal','security-and-surveillance','security-and-surveillance--consumables'),
('Card reader','security-and-surveillance','security-and-surveillance--consumables'),
('RFID reader','security-and-surveillance','security-and-surveillance--consumables'),
('Keypad reader','security-and-surveillance','security-and-surveillance--consumables'),
('Turnstile','security-and-surveillance','security-and-surveillance--consumables'),
('Speed gate','security-and-surveillance','security-and-surveillance--consumables'),
('Barrier gate','security-and-surveillance','security-and-surveillance--consumables'),
('Access software','security-and-surveillance','security-and-surveillance--consumables'),
('Magnetic lock','security-and-surveillance','security-and-surveillance--components'),
('Electric strike','security-and-surveillance','security-and-surveillance--components'),
('Electric bolt','security-and-surveillance','security-and-surveillance--components'),
('Smart lock','security-and-surveillance','security-and-surveillance--components'),
('Cabinet lock','furniture-and-interior-products','furniture-and-interior-products--accessories'),
('Hotel lock','security-and-surveillance','security-and-surveillance--components'),
('Gate lock','security-and-surveillance','security-and-surveillance--components'),
('Padlock','security-and-surveillance','security-and-surveillance--components'),
('Mortise lock','security-and-surveillance','security-and-surveillance--components'),
('Rim lock','security-and-surveillance','security-and-surveillance--components'),
('Alarm panel','security-and-surveillance','security-and-surveillance--installation'),
('Motion detector','security-and-surveillance','security-and-surveillance--installation'),
('Door contact','security-and-surveillance','security-and-surveillance--installation'),
('Glass-break detector','security-and-surveillance','security-and-surveillance--installation'),
('PIR sensor','security-and-surveillance','security-and-surveillance--installation'),
('Microwave sensor','security-and-surveillance','security-and-surveillance--installation'),
('Siren','security-and-surveillance','security-and-surveillance--installation'),
('Strobe light','security-and-surveillance','security-and-surveillance--installation'),
('Panic button','security-and-surveillance','security-and-surveillance--installation'),
('Wireless alarm sensor','security-and-surveillance','security-and-surveillance--installation'),
('Electric fence energizer','security-and-surveillance','security-and-surveillance--protection'),
('Electric fence wire','security-and-surveillance','security-and-surveillance--protection'),
('Fence sensor','security-and-surveillance','security-and-surveillance--protection'),
('Beam detector','security-and-surveillance','security-and-surveillance--protection'),
('Perimeter cable','security-and-surveillance','security-and-surveillance--protection'),
('Vibration sensor','security-and-surveillance','security-and-surveillance--protection'),
('Gate sensor','security-and-surveillance','security-and-surveillance--protection'),
('Barrier sensor','security-and-surveillance','security-and-surveillance--protection'),
('Fence alarm','security-and-surveillance','security-and-surveillance--protection'),
('Security bollard','security-and-surveillance','security-and-surveillance--protection'),
('Audio intercom','security-and-surveillance','security-and-surveillance--maintenance'),
('Video intercom','security-and-surveillance','security-and-surveillance--maintenance'),
('Door phone','security-and-surveillance','security-and-surveillance--maintenance'),
('IP intercom','security-and-surveillance','security-and-surveillance--maintenance'),
('Master station','security-and-surveillance','security-and-surveillance--maintenance'),
('Slave station','security-and-surveillance','security-and-surveillance--maintenance'),
('Video doorbell','security-and-surveillance','security-and-surveillance--maintenance'),
('Gate intercom','security-and-surveillance','security-and-surveillance--maintenance'),
('Paging intercom','security-and-surveillance','security-and-surveillance--maintenance'),
('Intercom handset','security-and-surveillance','security-and-surveillance--maintenance'),
('Installation system — IP camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Dome camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Bullet camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — PTZ camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Turret camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Fisheye camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Thermal camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — ANPR camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Outdoor camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Long-range camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — NVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — DVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Hybrid recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — CCTV hard drive','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Video encoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Video decoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Recording appliance','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Backup recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Network recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Access controller','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Fingerprint reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Face recognition terminal','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Card reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — RFID reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Keypad reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Turnstile','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Speed gate','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Barrier gate','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Access software','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Magnetic lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Electric strike','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Electric bolt','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Smart lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Cabinet lock','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Installation system — Hotel lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Gate lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Padlock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Mortise lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Rim lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Alarm panel','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Motion detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Door contact','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Glass-break detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — PIR sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Microwave sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Siren','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Strobe light','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Panic button','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Wireless alarm sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Electric fence energizer','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Electric fence wire','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Fence sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Beam detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Perimeter cable','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Vibration sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Gate sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Barrier sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Fence alarm','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Security bollard','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Audio intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Video intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Door phone','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — IP intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Master station','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Slave station','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Video doorbell','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Gate intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Paging intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Installation system — Intercom handset','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — IP camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Dome camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Bullet camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — PTZ camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Turret camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Fisheye camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Thermal camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — ANPR camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Outdoor camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Long-range camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — NVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — DVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Hybrid recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — CCTV hard drive','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Video encoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Video decoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Recording appliance','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Backup recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Network recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Access controller','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Fingerprint reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Face recognition terminal','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Card reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — RFID reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Keypad reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Turnstile','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Speed gate','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Barrier gate','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Access software','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Magnetic lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Electric strike','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Electric bolt','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Smart lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Cabinet lock','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Replacement component — Hotel lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Gate lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Padlock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Mortise lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Rim lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Alarm panel','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Motion detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Door contact','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Glass-break detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — PIR sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Microwave sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Siren','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Strobe light','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Panic button','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Wireless alarm sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Electric fence energizer','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Electric fence wire','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Fence sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Beam detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Perimeter cable','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Vibration sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Gate sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Barrier sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Fence alarm','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Security bollard','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Audio intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Video intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Door phone','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — IP intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Master station','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Slave station','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Video doorbell','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Gate intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Paging intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Replacement component — Intercom handset','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — IP camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Dome camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Bullet camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — PTZ camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Turret camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Fisheye camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Thermal camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — ANPR camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Outdoor camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Long-range camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — NVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — DVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Hybrid recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — CCTV hard drive','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Video encoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Video decoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Recording appliance','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Backup recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Network recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Access controller','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Fingerprint reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Face recognition terminal','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Card reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — RFID reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Keypad reader','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Turnstile','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Speed gate','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Barrier gate','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Access software','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Magnetic lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Electric strike','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Electric bolt','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Smart lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Cabinet lock','furniture-and-interior-products','furniture-and-interior-products--expanded-product-families'),
('Service equipment — Hotel lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Gate lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Padlock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Mortise lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Rim lock','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Alarm panel','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Motion detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Door contact','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Glass-break detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — PIR sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Microwave sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Siren','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Strobe light','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Panic button','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Wireless alarm sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Electric fence energizer','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Electric fence wire','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Fence sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Beam detector','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Perimeter cable','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Vibration sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Gate sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Barrier sensor','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Fence alarm','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Security bollard','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Audio intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Video intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Door phone','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — IP intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Master station','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Slave station','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Video doorbell','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Gate intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Paging intercom','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Service equipment — Intercom handset','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — IP camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Dome camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Bullet camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — PTZ camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Turret camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Fisheye camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Thermal camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — ANPR camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Outdoor camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Long-range camera','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — NVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — DVR','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Hybrid recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — CCTV hard drive','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Video encoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Video decoder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Recording appliance','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Backup recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Testing equipment — Network recorder','security-and-surveillance','security-and-surveillance--expanded-product-families'),
('Analytical balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Top-pan balance','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('pH meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Conductivity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Turbidity meter','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core'),
('Spectrophotometer','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--vehicles-core')
on conflict (n) do update set m = excluded.m, s = excluded.s;
