-- 0065 part 4 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Alkali-resistant primer','paints-finishes','paints-finishes--components'),
('Bonding primer','paints-finishes','paints-finishes--components'),
('Wood primer','paints-finishes','paints-finishes--components'),
('Epoxy primer','paints-finishes','paints-finishes--components'),
('Zinc-rich primer','paints-finishes','paints-finishes--components'),
('Decorative glaze','paints-finishes','paints-finishes--equipment'),
('Metallic paint','paints-finishes','paints-finishes--equipment'),
('Chalk paint','paints-finishes','paints-finishes--equipment'),
('Furniture paint','paints-finishes','paints-finishes--equipment'),
('Trim paint','paints-finishes','paints-finishes--equipment'),
('Anti-rust paint','paints-finishes','paints-finishes--consumables'),
('Epoxy metal coating','paints-finishes','paints-finishes--consumables'),
('Zinc coating','paints-finishes','paints-finishes--consumables'),
('Aluminium paint','paints-finishes','paints-finishes--installation'),
('Heat-resistant paint','paints-finishes','paints-finishes--installation'),
('Marine coating','paints-finishes','paints-finishes--installation'),
('Machinery coating','paints-finishes','paints-finishes--installation'),
('Floor coating','paints-finishes','paints-finishes--installation'),
('Road marking paint','paints-finishes','paints-finishes--installation'),
('Traffic paint','paints-finishes','paints-finishes--installation'),
('Parking paint','paints-finishes','paints-finishes--installation'),
('Reflective road coating','paints-finishes','paints-finishes--installation'),
('Skim coat','paints-finishes','paints-finishes--maintenance'),
('Wall putty','paints-finishes','paints-finishes--maintenance'),
('Concrete filler','paints-finishes','paints-finishes--maintenance'),
('Paint thinner','paints-finishes','paints-finishes--maintenance'),
('Epoxy thinner','paints-finishes','paints-finishes--control'),
('Installation system — Weatherproof paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Masonry paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Acrylic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Textured paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Silicate paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Lime paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Washable paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Anti-mould paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Wall primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Acrylic primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Alkali-resistant primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Bonding primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Wood primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Epoxy primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Zinc-rich primer','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Decorative glaze','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Metallic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Chalk paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Furniture paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Trim paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Anti-rust paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Epoxy metal coating','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Zinc coating','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Aluminium paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Heat-resistant paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Marine coating','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Machinery coating','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Floor coating','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Road marking paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Traffic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Parking paint','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Reflective road coating','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Skim coat','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Wall putty','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Concrete filler','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Paint thinner','paints-finishes','paints-finishes--expanded-product-families'),
('Installation system — Epoxy thinner','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Weatherproof paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Masonry paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Acrylic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Textured paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Silicate paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Lime paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Washable paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Anti-mould paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Wall primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Acrylic primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Alkali-resistant primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Bonding primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Wood primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Metal primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Epoxy primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Zinc-rich primer','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Decorative glaze','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Metallic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Chalk paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Furniture paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Trim paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Anti-rust paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Epoxy metal coating','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Zinc coating','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Aluminium paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Heat-resistant paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Marine coating','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Machinery coating','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Floor coating','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Road marking paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Traffic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Parking paint','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Reflective road coating','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Skim coat','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Wall putty','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Concrete filler','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Paint thinner','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Epoxy thinner','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Paint brush','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Paint roller','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Paint tray','paints-finishes','paints-finishes--expanded-product-families'),
('Replacement component — Paint mixer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Weatherproof paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Masonry paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Acrylic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Textured paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Silicate paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Lime paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Washable paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Anti-mould paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Wall primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Acrylic primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Alkali-resistant primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Bonding primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Wood primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Metal primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Epoxy primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Zinc-rich primer','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Decorative glaze','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Metallic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Chalk paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Furniture paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Trim paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Anti-rust paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Epoxy metal coating','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Zinc coating','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Aluminium paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Heat-resistant paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Marine coating','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Machinery coating','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Floor coating','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Road marking paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Traffic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Parking paint','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Reflective road coating','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Skim coat','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Wall putty','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Concrete filler','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Paint thinner','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Epoxy thinner','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Paint brush','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Paint roller','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Paint tray','paints-finishes','paints-finishes--expanded-product-families'),
('Service equipment — Paint mixer','paints-finishes','paints-finishes--expanded-product-families'),
('Testing equipment — Weatherproof paint','paints-finishes','paints-finishes--expanded-product-families'),
('Testing equipment — Masonry paint','paints-finishes','paints-finishes--expanded-product-families'),
('Testing equipment — Acrylic paint','paints-finishes','paints-finishes--expanded-product-families'),
('Testing equipment — Textured paint','paints-finishes','paints-finishes--expanded-product-families'),
('Testing equipment — Silicate paint','paints-finishes','paints-finishes--expanded-product-families'),
('Testing equipment — Lime paint','paints-finishes','paints-finishes--expanded-product-families'),
('Caustic soda','chemicals-industrial','chemicals-industrial--core-products'),
('Soda ash','chemicals-industrial','chemicals-industrial--core-products'),
('Hydrochloric acid','chemicals-industrial','chemicals-industrial--core-products'),
('Sulphuric acid','chemicals-industrial','chemicals-industrial--core-products'),
('Nitric acid','chemicals-industrial','chemicals-industrial--core-products'),
('Phosphoric acid','chemicals-industrial','chemicals-industrial--core-products'),
('Hydrogen peroxide','chemicals-industrial','chemicals-industrial--core-products'),
('Sodium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--components'),
('Citric acid','chemicals-industrial','chemicals-industrial--core-products'),
('Acetic acid','chemicals-industrial','chemicals-industrial--core-products'),
('Ferric chloride','water-treatment-and-waste-management','water-treatment-and-waste-management--components'),
('Chlorine','water-treatment-and-waste-management','water-treatment-and-waste-management--components'),
('Calcium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--components'),
('Water-treatment polymer','chemicals-industrial','chemicals-industrial--components'),
('Ion-exchange resin','chemicals-industrial','chemicals-industrial--components'),
('Sanitizer chemical','chemicals-industrial','chemicals-industrial--equipment'),
('Boiler cleaner','cleaning-hygiene','cleaning-hygiene--equipment'),
('Solvent cleaner','cleaning-hygiene','cleaning-hygiene--equipment'),
('Polyester resin','chemicals-industrial','chemicals-industrial--consumables'),
('Vinyl ester resin','chemicals-industrial','chemicals-industrial--consumables'),
('PU adhesive','chemicals-industrial','chemicals-industrial--consumables'),
('PVA adhesive','chemicals-industrial','chemicals-industrial--consumables'),
('Anaerobic adhesive','chemicals-industrial','chemicals-industrial--consumables'),
('Oxygen gas','chemicals-industrial','chemicals-industrial--maintenance'),
('Carbon dioxide gas','chemicals-industrial','chemicals-industrial--maintenance'),
('Acetylene gas','chemicals-industrial','chemicals-industrial--maintenance'),
('HDPE resin','chemicals-industrial','chemicals-industrial--control'),
('LDPE resin','chemicals-industrial','chemicals-industrial--control'),
('PP resin','chemicals-industrial','chemicals-industrial--protection'),
('PVC resin','chemicals-industrial','chemicals-industrial--protection'),
('PET resin','chemicals-industrial','chemicals-industrial--protection'),
('ABS resin','chemicals-industrial','chemicals-industrial--protection'),
('Nylon resin','chemicals-industrial','chemicals-industrial--protection'),
('Polycarbonate resin','chemicals-industrial','chemicals-industrial--protection'),
('Installation system — Caustic soda','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Soda ash','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Hydrochloric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Sulphuric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Nitric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Phosphoric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Hydrogen peroxide','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Sodium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Citric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Acetic acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Ferric chloride','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Chlorine','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Calcium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Water-treatment polymer','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Ion-exchange resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Sanitizer chemical','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Boiler cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Solvent cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Installation system — Polyester resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Vinyl ester resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — PU adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — PVA adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Anaerobic adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Oxygen gas','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Carbon dioxide gas','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Acetylene gas','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — HDPE resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — LDPE resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — PP resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — PVC resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — PET resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — ABS resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Nylon resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Installation system — Polycarbonate resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Caustic soda','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Soda ash','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Hydrochloric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Sulphuric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Nitric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Phosphoric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Hydrogen peroxide','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Sodium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Citric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Acetic acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Ferric chloride','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Chlorine','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Calcium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Water-treatment polymer','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Ion-exchange resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Sanitizer chemical','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Boiler cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Solvent cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Replacement component — Epoxy resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Polyester resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Vinyl ester resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — PU adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Hot-melt adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — PVA adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Contact adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Cyanoacrylate adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Anaerobic adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Oxygen gas','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Carbon dioxide gas','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Acetylene gas','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — HDPE resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — LDPE resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — PP resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — PVC resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — PET resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — ABS resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Nylon resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Replacement component — Polycarbonate resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Caustic soda','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Soda ash','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Hydrochloric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Sulphuric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Nitric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Phosphoric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Hydrogen peroxide','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Sodium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Citric acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Acetic acid','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Ferric chloride','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Chlorine','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Calcium hypochlorite','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Water-treatment polymer','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Ion-exchange resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Sanitizer chemical','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Boiler cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Solvent cleaner','cleaning-hygiene','cleaning-hygiene--expanded-product-families'),
('Service equipment — Epoxy resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Polyester resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Vinyl ester resin','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — PU adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Hot-melt adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — PVA adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Contact adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Cyanoacrylate adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Service equipment — Anaerobic adhesive','chemicals-industrial','chemicals-industrial--expanded-product-families'),
('Piston','auto-parts','auto-parts--core-products'),
('Piston ring','auto-parts','auto-parts--core-products'),
('Cylinder liner','auto-parts','auto-parts--core-products'),
('Connecting rod','auto-parts','auto-parts--core-products'),
('Crankshaft','auto-parts','auto-parts--core-products'),
('Camshaft','auto-parts','auto-parts--core-products'),
('Valve','auto-parts','auto-parts--core-products'),
('Valve spring','auto-parts','auto-parts--core-products'),
('Oil pump','auto-parts','auto-parts--core-products'),
('Oil filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Air filter','auto-parts','auto-parts--components'),
('Fuel filter','auto-parts','auto-parts--components'),
('Cabin filter','auto-parts','auto-parts--components'),
('Spark plug','auto-parts','auto-parts--components'),
('Glow plug','auto-parts','auto-parts--components'),
('Drive belt','auto-parts','auto-parts--components'),
('Timing belt','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Tensioner','auto-parts','auto-parts--components'),
('Engine gasket','auto-parts','auto-parts--components'),
('Radiator','auto-parts','auto-parts--equipment'),
('Radiator fan','auto-parts','auto-parts--equipment'),
('Thermostat','auto-parts','auto-parts--equipment'),
('Radiator hose','auto-parts','auto-parts--equipment'),
('Coolant reservoir','auto-parts','auto-parts--equipment'),
('Radiator cap','auto-parts','auto-parts--equipment'),
('Intercooler','auto-parts','auto-parts--equipment'),
('Expansion tank','auto-parts','auto-parts--equipment'),
('Starter motor','auto-parts','auto-parts--equipment'),
('Alternator','auto-parts','auto-parts--consumables'),
('Battery','auto-parts','auto-parts--consumables'),
('Ignition coil','auto-parts','auto-parts--consumables'),
('Starter solenoid','auto-parts','auto-parts--consumables'),
('Fuse box','auto-parts','auto-parts--consumables'),
('Automotive relay','auto-parts','auto-parts--consumables'),
('Wiring harness','auto-parts','auto-parts--consumables'),
('Shock absorber','auto-parts','auto-parts--consumables'),
('Coil spring','auto-parts','auto-parts--consumables'),
('Leaf spring','auto-parts','auto-parts--consumables'),
('Control arm','auto-parts','auto-parts--installation'),
('Ball joint','auto-parts','auto-parts--installation'),
('Tie rod end','auto-parts','auto-parts--installation'),
('Stabilizer link','auto-parts','auto-parts--installation'),
('Wheel hub','auto-parts','auto-parts--installation'),
('Wheel bearing','auto-parts','auto-parts--installation'),
('Suspension bushing','auto-parts','auto-parts--installation'),
('Steering rack','auto-parts','auto-parts--installation'),
('Power steering pump','auto-parts','auto-parts--installation'),
('Steering column','auto-parts','auto-parts--installation'),
('Tie rod','auto-parts','auto-parts--maintenance'),
('Drag link','auto-parts','auto-parts--maintenance'),
('Pitman arm','auto-parts','auto-parts--maintenance'),
('Idler arm','auto-parts','auto-parts--maintenance'),
('Steering knuckle','auto-parts','auto-parts--maintenance'),
('Brake pad','auto-parts','auto-parts--maintenance'),
('Brake shoe','auto-parts','auto-parts--maintenance'),
('Brake disc','auto-parts','auto-parts--maintenance'),
('Brake drum','auto-parts','auto-parts--maintenance'),
('Brake caliper','auto-parts','auto-parts--maintenance'),
('Master cylinder','auto-parts','auto-parts--control'),
('Wheel cylinder','auto-parts','auto-parts--control'),
('Brake hose','auto-parts','auto-parts--control'),
('Brake booster','auto-parts','auto-parts--control'),
('ABS sensor','auto-parts','auto-parts--control'),
('Clutch plate','auto-parts','auto-parts--control'),
('Clutch cover','auto-parts','auto-parts--control'),
('Clutch bearing','auto-parts','auto-parts--control'),
('Flywheel','auto-parts','auto-parts--control'),
('Gearbox','other-industrial-supplies','other-industrial-supplies--power-transmission'),
('Gear shaft','auto-parts','auto-parts--protection'),
('Synchro ring','auto-parts','auto-parts--protection'),
('CV joint','auto-parts','auto-parts--protection'),
('Drive shaft','auto-parts','auto-parts--protection'),
('Differential','auto-parts','auto-parts--protection'),
('Bumper','auto-parts','auto-parts--protection'),
('Bonnet','auto-parts','auto-parts--protection'),
('Fender','auto-parts','auto-parts--protection'),
('Door shell','auto-parts','auto-parts--protection'),
('Tailgate','auto-parts','auto-parts--protection'),
('Grille','auto-parts','auto-parts--processing'),
('Headlamp','auto-parts','auto-parts--processing'),
('Tail lamp','auto-parts','auto-parts--processing'),
('Mirror','auto-parts','auto-parts--processing'),
('Windscreen','auto-parts','auto-parts--processing'),
('Installation system — Piston','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Piston ring','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Cylinder liner','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Connecting rod','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Crankshaft','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Camshaft','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Valve','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Valve spring','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Oil pump','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Oil filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Air filter','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Fuel filter','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Cabin filter','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Spark plug','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Glow plug','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Drive belt','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Timing belt','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Tensioner','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Engine gasket','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Radiator','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Radiator fan','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Thermostat','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Radiator hose','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Coolant reservoir','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Radiator cap','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Intercooler','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Expansion tank','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Starter motor','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Alternator','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Battery','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Ignition coil','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Starter solenoid','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Fuse box','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Automotive relay','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Wiring harness','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Shock absorber','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Coil spring','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Leaf spring','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Control arm','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Ball joint','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Tie rod end','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Stabilizer link','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Wheel hub','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Wheel bearing','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Suspension bushing','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Steering rack','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Power steering pump','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Steering column','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Tie rod','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Drag link','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Pitman arm','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Idler arm','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Steering knuckle','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake pad','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake shoe','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake disc','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake drum','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake caliper','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Master cylinder','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Wheel cylinder','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake hose','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Brake booster','auto-parts','auto-parts--expanded-product-families'),
('Installation system — ABS sensor','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Clutch plate','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Clutch cover','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Clutch bearing','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Flywheel','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Gearbox','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Installation system — Gear shaft','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Synchro ring','auto-parts','auto-parts--expanded-product-families'),
('Installation system — CV joint','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Drive shaft','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Differential','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Bumper','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Bonnet','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Fender','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Door shell','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Tailgate','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Grille','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Headlamp','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Tail lamp','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Mirror','auto-parts','auto-parts--expanded-product-families'),
('Installation system — Windscreen','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Piston','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Piston ring','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Cylinder liner','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Connecting rod','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Crankshaft','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Camshaft','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Valve','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Valve spring','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Oil pump','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Water pump','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Oil filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Air filter','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Fuel filter','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Cabin filter','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Spark plug','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Glow plug','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Drive belt','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Timing belt','other-industrial-supplies','other-industrial-supplies--expanded-product-families'),
('Replacement component — Tensioner','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Engine gasket','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Radiator','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Radiator fan','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Thermostat','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Radiator hose','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Coolant reservoir','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Radiator cap','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Intercooler','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Expansion tank','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Starter motor','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Alternator','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Battery','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Ignition coil','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Starter solenoid','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Fuse box','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Automotive relay','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Wiring harness','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Shock absorber','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Coil spring','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Leaf spring','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Control arm','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Ball joint','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Tie rod end','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Stabilizer link','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Wheel hub','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Wheel bearing','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Suspension bushing','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Steering rack','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Power steering pump','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Steering column','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Tie rod','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Drag link','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Pitman arm','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Idler arm','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Steering knuckle','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake pad','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake shoe','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake disc','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake drum','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake caliper','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Master cylinder','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Wheel cylinder','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake hose','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Brake booster','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — ABS sensor','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Clutch plate','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Clutch cover','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Clutch bearing','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Flywheel','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Gearbox','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Gear shaft','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Synchro ring','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — CV joint','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Drive shaft','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Differential','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Bumper','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Bonnet','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Fender','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Door shell','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Tailgate','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Grille','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Headlamp','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Tail lamp','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Mirror','auto-parts','auto-parts--expanded-product-families'),
('Replacement component — Windscreen','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Piston','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Piston ring','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Cylinder liner','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Connecting rod','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Crankshaft','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Camshaft','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Valve','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Valve spring','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Oil pump','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Water pump','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Oil filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Service equipment — Air filter','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Fuel filter','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Cabin filter','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Spark plug','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Glow plug','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Drive belt','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Timing belt','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Tensioner','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Engine gasket','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Radiator','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Radiator fan','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Thermostat','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Radiator hose','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Coolant reservoir','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Radiator cap','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Intercooler','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Expansion tank','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Starter motor','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Alternator','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Battery','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Ignition coil','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Starter solenoid','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Fuse box','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Automotive relay','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Wiring harness','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Shock absorber','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Coil spring','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Leaf spring','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Control arm','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Ball joint','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Tie rod end','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Stabilizer link','auto-parts','auto-parts--expanded-product-families'),
('Service equipment — Wheel hub','auto-parts','auto-parts--expanded-product-families'),
('Sedan','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--vehicles-core'),
('SUV','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--vehicles-core'),
('Crossover','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--vehicles-core'),
('Pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--vehicles-core'),
('Double-cab pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--vehicles-core'),
('Passenger van','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--vehicles-core'),
('Car carrier','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--equipment'),
('Rescue vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--systems'),
('Workshop vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--systems'),
('Warehouse cart','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--accessories'),
('Tractor trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--service'),
('Farm utility vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--service'),
('Vehicle telematics unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--service'),
('Vehicle dash camera','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--replacement-parts'),
('Vehicle immobilizer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--replacement-parts'),
('Vehicle refrigeration unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--replacement-parts'),
('Car trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--control'),
('Cargo trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--control'),
('Installation system — Sedan','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — SUV','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Crossover','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Double-cab pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Passenger van','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Car carrier','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Rescue vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Workshop vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Warehouse cart','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Tractor trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Farm utility vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Vehicle telematics unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Vehicle dash camera','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Vehicle immobilizer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Vehicle refrigeration unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Car trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Installation system — Cargo trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Sedan','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — SUV','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Crossover','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Double-cab pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Passenger van','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Car carrier','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Rescue vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Workshop vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Warehouse cart','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Tractor trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Farm utility vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Vehicle telematics unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Vehicle dash camera','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Vehicle immobilizer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Vehicle refrigeration unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Car trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Replacement component — Cargo trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Sedan','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — SUV','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Crossover','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Double-cab pickup','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Passenger van','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Car carrier','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Rescue vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Workshop vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Warehouse cart','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Tractor trailer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Farm utility vehicle','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Vehicle telematics unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Vehicle dash camera','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Vehicle immobilizer','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Service equipment — Vehicle refrigeration unit','automotive-vehicles-and-commercial-equipment','automotive-vehicles-and-commercial-equipment--expanded-product-families'),
('Crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--vehicles-core'),
('Jaw crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--vehicles-core'),
('Cone crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--vehicles-core'),
('Hammer mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--replacement-parts'),
('Ball mill','machinery-and-industrial-equipment','machinery-and-industrial-equipment--vehicles-core'),
('Conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--vehicles-core'),
('Centrifugal pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Positive displacement pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Diaphragm pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Gear pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Screw pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Piston pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Vacuum pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Chemical pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Slurry pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Metering pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--equipment'),
('Air compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Screw compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Piston compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Scroll compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Centrifugal compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Refrigeration compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('High-pressure compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Portable compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Booster compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Compressor dryer','machinery-and-industrial-equipment','machinery-and-industrial-equipment--components'),
('Filter press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--systems'),
('Filling machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--accessories'),
('Sealing machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--accessories'),
('Carton sealer','packaging-machinery','packaging-machinery--service'),
('Belt conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--service'),
('Chain conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--service'),
('Roller conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--service'),
('Milling machine','construction-machinery-and-equipment','construction-machinery-and-equipment--systems'),
('Drill press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--replacement-parts'),
('Surface grinder','machinery-and-industrial-equipment','machinery-and-industrial-equipment--replacement-parts'),
('Installation system — Crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Jaw crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Cone crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Hammer mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Installation system — Ball mill','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Centrifugal pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Positive displacement pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Diaphragm pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Gear pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Screw pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Piston pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Vacuum pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Chemical pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Slurry pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Metering pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Air compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Screw compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Piston compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Scroll compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Centrifugal compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Refrigeration compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — High-pressure compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Portable compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Booster compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Compressor dryer','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Filter press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Filling machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Sealing machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Carton sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Installation system — Belt conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Chain conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Roller conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Milling machine','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Installation system — Drill press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Installation system — Surface grinder','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Jaw crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Cone crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Hammer mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Replacement component — Ball mill','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Centrifugal pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Positive displacement pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Diaphragm pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Gear pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Screw pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Piston pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Vacuum pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Chemical pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Slurry pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Metering pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Air compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Screw compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Piston compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Scroll compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Centrifugal compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Refrigeration compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — High-pressure compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Portable compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Booster compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Compressor dryer','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Filter press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Filling machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Sealing machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Carton sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Replacement component — Belt conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Screw conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Chain conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Roller conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Milling machine','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Replacement component — Drill press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Replacement component — Surface grinder','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Jaw crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Cone crusher','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Hammer mill','agriculture-machinery-and-equipment','agriculture-machinery-and-equipment--expanded-product-families'),
('Service equipment — Ball mill','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Centrifugal pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Positive displacement pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Diaphragm pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Gear pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Screw pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Piston pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Vacuum pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Chemical pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Slurry pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Metering pump','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Air compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Screw compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Piston compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Scroll compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Centrifugal compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Refrigeration compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — High-pressure compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Portable compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Booster compressor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Compressor dryer','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Filter press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Filling machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Sealing machine','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Carton sealer','packaging-machinery','packaging-machinery--expanded-product-families'),
('Service equipment — Belt conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Screw conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Chain conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Roller conveyor','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Milling machine','construction-machinery-and-equipment','construction-machinery-and-equipment--expanded-product-families'),
('Service equipment — Drill press','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Service equipment — Surface grinder','machinery-and-industrial-equipment','machinery-and-industrial-equipment--expanded-product-families'),
('Backhoe loader','construction-machinery-and-equipment','construction-machinery-and-equipment--vehicles-core'),
('Motor grader','construction-machinery-and-equipment','construction-machinery-and-equipment--vehicles-core'),
('Concrete pump','construction-machinery-and-equipment','construction-machinery-and-equipment--components')
on conflict (n) do update set m = excluded.m, s = excluded.s;
