-- 0065 part 6 of 8 · run the parts in order, then 0065_finish.
-- Loads a slice of the product-to-category map into a staging table.
create table if not exists public.import_catmap (n text primary key, m text, s text);
insert into public.import_catmap (n, m, s) values
('Replacement component — Hospital trolley','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Instrument trolley','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — IV pole','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Sample container','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Urine container','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Blood tube','medical-supplies','medical-supplies--expanded-product-families'),
('Replacement component — Microscope slide','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Cover slip','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Test tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Replacement component — Centrifuge tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Surgical mask','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — N95 respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Examination gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Surgical gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Gown','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Apron','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Face shield','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Surgical cap','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Shoe covers','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Protective goggles','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Gauze','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Cotton wool','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Adhesive bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Elastic bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Crepe bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Plaster roll','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Wound dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Burn dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Absorbent dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Medical tape','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Disposable syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Insulin syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Safety syringe','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Hypodermic needle','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV cannula','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Butterfly needle','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Spinal needle','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Dental needle','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Sharps container','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Needle holder','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV giving set','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Blood transfusion set','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV extension set','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Three-way stopcock','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV connector','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Infusion pump set','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Pressure infusion bag','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV stand','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Blood collection set','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Blood pressure monitor','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Pulse oximeter','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Thermometer','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Stethoscope','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Nebulizer','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Fetal doppler','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — ECG machine','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Patient monitor','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Otoscope','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Hospital bed','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Examination couch','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Bedside locker','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Overbed table','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Wheelchair','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Patient stretcher','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Hospital trolley','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Instrument trolley','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — IV pole','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Sample container','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Urine container','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Blood tube','medical-supplies','medical-supplies--expanded-product-families'),
('Service equipment — Microscope slide','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Cover slip','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Test tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Service equipment — Centrifuge tube','laboratory-and-scientific-equipment','laboratory-and-scientific-equipment--expanded-product-families'),
('Testing equipment — Surgical mask','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — N95 respirator','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Examination gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Surgical gloves','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Gown','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Apron','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Face shield','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Surgical cap','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Shoe covers','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Protective goggles','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Gauze','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Cotton wool','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Adhesive bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Elastic bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Crepe bandage','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Plaster roll','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Wound dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Burn dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Absorbent dressing','medical-supplies','medical-supplies--expanded-product-families'),
('Testing equipment — Medical tape','medical-supplies','medical-supplies--expanded-product-families'),
('Ballpoint pen','stationery-printing','stationery-printing--core'),
('Gel pen','stationery-printing','stationery-printing--core'),
('Rollerball pen','stationery-printing','stationery-printing--core'),
('Pencil','stationery-printing','stationery-printing--core'),
('Mechanical pencil','stationery-printing','stationery-printing--core'),
('Marker','stationery-printing','stationery-printing--core'),
('Highlighter','stationery-printing','stationery-printing--core'),
('Permanent marker','stationery-printing','stationery-printing--core'),
('Whiteboard marker','stationery-printing','stationery-printing--core'),
('Correction pen','stationery-printing','stationery-printing--core'),
('A4 copy paper','stationery-printing','stationery-printing--equipment'),
('A3 copy paper','stationery-printing','stationery-printing--equipment'),
('Letter paper','stationery-printing','stationery-printing--equipment'),
('Carbonless paper','stationery-printing','stationery-printing--equipment'),
('Kraft paper','stationery-printing','stationery-printing--equipment'),
('Art paper','stationery-printing','stationery-printing--equipment'),
('Gloss paper','stationery-printing','stationery-printing--equipment'),
('Card stock','stationery-printing','stationery-printing--equipment'),
('Receipt paper','stationery-printing','stationery-printing--equipment'),
('Thermal paper','stationery-printing','stationery-printing--equipment'),
('Exercise book','stationery-printing','stationery-printing--consumables'),
('Hardcover notebook','stationery-printing','stationery-printing--consumables'),
('Spiral notebook','stationery-printing','stationery-printing--consumables'),
('Memo pad','stationery-printing','stationery-printing--consumables'),
('Meeting notebook','stationery-printing','stationery-printing--consumables'),
('Ledger book','stationery-printing','stationery-printing--consumables'),
('Journal','stationery-printing','stationery-printing--consumables'),
('Sketchbook','stationery-printing','stationery-printing--consumables'),
('Logbook','stationery-printing','stationery-printing--consumables'),
('Laboratory notebook','stationery-printing','stationery-printing--consumables'),
('File folder','stationery-printing','stationery-printing--components'),
('Lever arch file','office-and-business-supplies','office-and-business-supplies--systems'),
('Box file','office-and-business-supplies','office-and-business-supplies--systems'),
('Ring binder','office-and-business-supplies','office-and-business-supplies--systems'),
('Document wallet','office-and-business-supplies','office-and-business-supplies--systems'),
('Expanding file','office-and-business-supplies','office-and-business-supplies--systems'),
('Archive box','office-and-business-supplies','office-and-business-supplies--systems'),
('File divider','office-and-business-supplies','office-and-business-supplies--systems'),
('Document tray','office-and-business-supplies','office-and-business-supplies--systems'),
('Magazine holder','office-and-business-supplies','office-and-business-supplies--systems'),
('Toner cartridge','stationery-printing','stationery-printing--installation'),
('Ink cartridge','stationery-printing','stationery-printing--installation'),
('Printing ink','stationery-printing','stationery-printing--installation'),
('Screen printing ink','stationery-printing','stationery-printing--installation'),
('Offset ink','stationery-printing','stationery-printing--installation'),
('Sublimation ink','stationery-printing','stationery-printing--installation'),
('Binding machine','office-and-business-supplies','office-and-business-supplies--equipment'),
('Laminator','office-and-business-supplies','office-and-business-supplies--equipment'),
('Paper cutter','office-and-business-supplies','office-and-business-supplies--accessories'),
('Label printer','office-and-business-supplies','office-and-business-supplies--equipment'),
('Whiteboard','office-and-business-supplies','office-and-business-supplies--service'),
('Flip chart','stationery-printing','stationery-printing--maintenance'),
('Notice board','office-and-business-supplies','office-and-business-supplies--service'),
('Presentation folder','stationery-printing','stationery-printing--maintenance'),
('Clipboard','office-and-business-supplies','office-and-business-supplies--accessories'),
('Display board','stationery-printing','stationery-printing--maintenance'),
('Pin board','office-and-business-supplies','office-and-business-supplies--service'),
('Desk organizer','office-and-business-supplies','office-and-business-supplies--accessories'),
('Installation system — Ballpoint pen','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Gel pen','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Rollerball pen','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Mechanical pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Marker','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Highlighter','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Permanent marker','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Whiteboard marker','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Correction pen','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — A4 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — A3 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Letter paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Carbonless paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Kraft paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Art paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Gloss paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Card stock','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Receipt paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Thermal paper','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Exercise book','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Hardcover notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Spiral notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Memo pad','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Meeting notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Ledger book','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Journal','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Sketchbook','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Logbook','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Laboratory notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — File folder','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Lever arch file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Box file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Ring binder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Document wallet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Expanding file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Archive box','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — File divider','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Document tray','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Magazine holder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Toner cartridge','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Ink cartridge','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Printing ink','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Screen printing ink','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Offset ink','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Sublimation ink','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Binding machine','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Laminator','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Paper cutter','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Label printer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Whiteboard','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Flip chart','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Notice board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Presentation folder','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Clipboard','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Display board','stationery-printing','stationery-printing--expanded-product-families'),
('Installation system — Pin board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Installation system — Desk organizer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Ballpoint pen','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Gel pen','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Rollerball pen','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Mechanical pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Marker','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Highlighter','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Permanent marker','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Whiteboard marker','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Correction pen','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — A4 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — A3 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Letter paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Carbonless paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Kraft paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Art paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Gloss paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Card stock','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Receipt paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Thermal paper','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Exercise book','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Hardcover notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Spiral notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Memo pad','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Meeting notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Ledger book','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Journal','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Sketchbook','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Logbook','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Laboratory notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — File folder','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Lever arch file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Box file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Ring binder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Document wallet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Expanding file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Archive box','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — File divider','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Document tray','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Magazine holder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Toner cartridge','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Ink cartridge','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Printing ink','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Screen printing ink','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Offset ink','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Sublimation ink','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Binding machine','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Laminator','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Paper cutter','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Label printer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Whiteboard','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Flip chart','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Notice board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Presentation folder','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Clipboard','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Display board','stationery-printing','stationery-printing--expanded-product-families'),
('Replacement component — Pin board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Replacement component — Desk organizer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Ballpoint pen','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Gel pen','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Rollerball pen','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Mechanical pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Marker','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Highlighter','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Permanent marker','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Whiteboard marker','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Correction pen','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — A4 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — A3 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Letter paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Carbonless paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Kraft paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Art paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Gloss paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Card stock','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Receipt paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Thermal paper','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Exercise book','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Hardcover notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Spiral notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Memo pad','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Meeting notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Ledger book','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Journal','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Sketchbook','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Logbook','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Laboratory notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — File folder','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Lever arch file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Box file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Ring binder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Document wallet','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Expanding file','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Archive box','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — File divider','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Document tray','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Magazine holder','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Toner cartridge','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Ink cartridge','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Printing ink','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Screen printing ink','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Offset ink','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Sublimation ink','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Binding machine','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Laminator','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Paper cutter','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Label printer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Whiteboard','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Flip chart','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Notice board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Presentation folder','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Clipboard','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Display board','stationery-printing','stationery-printing--expanded-product-families'),
('Service equipment — Pin board','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Service equipment — Desk organizer','office-and-business-supplies','office-and-business-supplies--expanded-product-families'),
('Testing equipment — Ballpoint pen','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Gel pen','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Rollerball pen','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Mechanical pencil','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Marker','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Highlighter','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Permanent marker','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Whiteboard marker','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Correction pen','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — A4 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — A3 copy paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Letter paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Carbonless paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Kraft paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Art paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Gloss paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Card stock','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Receipt paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Thermal paper','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Exercise book','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Hardcover notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Spiral notebook','stationery-printing','stationery-printing--expanded-product-families'),
('Testing equipment — Memo pad','stationery-printing','stationery-printing--expanded-product-families'),
('PP woven bag','packaging','packaging--core'),
('Paper bag','packaging','packaging--core'),
('Kraft bag','packaging','packaging--core'),
('Plastic pouch','packaging','packaging--core'),
('Stand-up pouch','packaging','packaging--core'),
('Zipper pouch','packaging','packaging--core'),
('Vacuum pouch','packaging','packaging--core'),
('Retort pouch','packaging','packaging--core'),
('Laminated pouch','packaging','packaging--core'),
('Plastic bottle','packaging','packaging--equipment'),
('Glass bottle','packaging','packaging--equipment'),
('Plastic jar','packaging','packaging--equipment'),
('Glass jar','packaging','packaging--equipment'),
('Plastic bucket','packaging','packaging--equipment'),
('Plastic container','packaging','packaging--equipment'),
('Corrugated carton','packaging','packaging--consumables'),
('Single-wall carton','packaging','packaging--consumables'),
('Double-wall carton','packaging','packaging--consumables'),
('Printed carton','packaging','packaging--consumables'),
('Die-cut carton','packaging','packaging--consumables'),
('Export carton','packaging','packaging--consumables'),
('Pizza box','packaging','packaging--consumables'),
('Pharmaceutical carton','packaging','packaging--consumables'),
('Retail carton','packaging','packaging--consumables'),
('Display carton','packaging','packaging--consumables'),
('PET bottle','packaging','packaging--components'),
('HDPE bottle','packaging','packaging--components'),
('Bottle cap','packaging','packaging--components'),
('LDPE film','packaging','packaging--components'),
('HDPE film','packaging','packaging--installation'),
('PP film','packaging','packaging--installation'),
('BOPP film','packaging','packaging--installation'),
('Shrink film','packaging','packaging--installation'),
('Stretch film','packaging','packaging--installation'),
('Cling film','packaging','packaging--installation'),
('Barrier film','packaging','packaging--installation'),
('Laminating film','packaging','packaging--installation'),
('Agricultural film','packaging','packaging--installation'),
('Stretch wrap','packaging','packaging--protection'),
('Shrink wrap','packaging','packaging--protection'),
('Pallet wrap','packaging','packaging--protection'),
('Shrink sleeve','packaging','packaging--maintenance'),
('Installation system — PP woven bag','packaging','packaging--expanded-product-families'),
('Installation system — Paper bag','packaging','packaging--expanded-product-families'),
('Installation system — Kraft bag','packaging','packaging--expanded-product-families'),
('Installation system — Plastic pouch','packaging','packaging--expanded-product-families'),
('Installation system — Stand-up pouch','packaging','packaging--expanded-product-families'),
('Installation system — Zipper pouch','packaging','packaging--expanded-product-families'),
('Installation system — Vacuum pouch','packaging','packaging--expanded-product-families'),
('Installation system — Retort pouch','packaging','packaging--expanded-product-families'),
('Installation system — Laminated pouch','packaging','packaging--expanded-product-families'),
('Installation system — Plastic bottle','packaging','packaging--expanded-product-families'),
('Installation system — Glass bottle','packaging','packaging--expanded-product-families'),
('Installation system — Plastic jar','packaging','packaging--expanded-product-families'),
('Installation system — Glass jar','packaging','packaging--expanded-product-families'),
('Installation system — Plastic bucket','packaging','packaging--expanded-product-families'),
('Installation system — Plastic container','packaging','packaging--expanded-product-families'),
('Installation system — Corrugated carton','packaging','packaging--expanded-product-families'),
('Installation system — Single-wall carton','packaging','packaging--expanded-product-families'),
('Installation system — Double-wall carton','packaging','packaging--expanded-product-families'),
('Installation system — Printed carton','packaging','packaging--expanded-product-families'),
('Installation system — Die-cut carton','packaging','packaging--expanded-product-families'),
('Installation system — Export carton','packaging','packaging--expanded-product-families'),
('Installation system — Pizza box','packaging','packaging--expanded-product-families'),
('Installation system — Pharmaceutical carton','packaging','packaging--expanded-product-families'),
('Installation system — Retail carton','packaging','packaging--expanded-product-families'),
('Installation system — Display carton','packaging','packaging--expanded-product-families'),
('Installation system — PET bottle','packaging','packaging--expanded-product-families'),
('Installation system — HDPE bottle','packaging','packaging--expanded-product-families'),
('Installation system — Bottle cap','packaging','packaging--expanded-product-families'),
('Installation system — LDPE film','packaging','packaging--expanded-product-families'),
('Installation system — HDPE film','packaging','packaging--expanded-product-families'),
('Installation system — PP film','packaging','packaging--expanded-product-families'),
('Installation system — BOPP film','packaging','packaging--expanded-product-families'),
('Installation system — Shrink film','packaging','packaging--expanded-product-families'),
('Installation system — Stretch film','packaging','packaging--expanded-product-families'),
('Installation system — Cling film','packaging','packaging--expanded-product-families'),
('Installation system — Barrier film','packaging','packaging--expanded-product-families'),
('Installation system — Laminating film','packaging','packaging--expanded-product-families'),
('Installation system — Agricultural film','packaging','packaging--expanded-product-families'),
('Installation system — Stretch wrap','packaging','packaging--expanded-product-families'),
('Installation system — Shrink wrap','packaging','packaging--expanded-product-families'),
('Installation system — Pallet wrap','packaging','packaging--expanded-product-families'),
('Installation system — Shrink sleeve','packaging','packaging--expanded-product-families'),
('Replacement component — PP woven bag','packaging','packaging--expanded-product-families'),
('Replacement component — Paper bag','packaging','packaging--expanded-product-families'),
('Replacement component — Kraft bag','packaging','packaging--expanded-product-families'),
('Replacement component — Plastic pouch','packaging','packaging--expanded-product-families'),
('Replacement component — Stand-up pouch','packaging','packaging--expanded-product-families'),
('Replacement component — Zipper pouch','packaging','packaging--expanded-product-families'),
('Replacement component — Vacuum pouch','packaging','packaging--expanded-product-families'),
('Replacement component — Retort pouch','packaging','packaging--expanded-product-families'),
('Replacement component — Laminated pouch','packaging','packaging--expanded-product-families'),
('Replacement component — Plastic bottle','packaging','packaging--expanded-product-families'),
('Replacement component — Glass bottle','packaging','packaging--expanded-product-families'),
('Replacement component — Plastic jar','packaging','packaging--expanded-product-families'),
('Replacement component — Glass jar','packaging','packaging--expanded-product-families'),
('Replacement component — Plastic bucket','packaging','packaging--expanded-product-families'),
('Replacement component — Plastic container','packaging','packaging--expanded-product-families'),
('Replacement component — Corrugated carton','packaging','packaging--expanded-product-families'),
('Replacement component — Single-wall carton','packaging','packaging--expanded-product-families'),
('Replacement component — Double-wall carton','packaging','packaging--expanded-product-families'),
('Replacement component — Printed carton','packaging','packaging--expanded-product-families'),
('Replacement component — Die-cut carton','packaging','packaging--expanded-product-families'),
('Replacement component — Export carton','packaging','packaging--expanded-product-families'),
('Replacement component — Pizza box','packaging','packaging--expanded-product-families'),
('Replacement component — Pharmaceutical carton','packaging','packaging--expanded-product-families'),
('Replacement component — Retail carton','packaging','packaging--expanded-product-families'),
('Replacement component — Display carton','packaging','packaging--expanded-product-families'),
('Replacement component — PET bottle','packaging','packaging--expanded-product-families'),
('Replacement component — HDPE bottle','packaging','packaging--expanded-product-families'),
('Replacement component — Bottle cap','packaging','packaging--expanded-product-families'),
('Replacement component — LDPE film','packaging','packaging--expanded-product-families'),
('Replacement component — HDPE film','packaging','packaging--expanded-product-families'),
('Replacement component — PP film','packaging','packaging--expanded-product-families'),
('Replacement component — BOPP film','packaging','packaging--expanded-product-families'),
('Replacement component — Shrink film','packaging','packaging--expanded-product-families'),
('Replacement component — Stretch film','packaging','packaging--expanded-product-families'),
('Replacement component — Cling film','packaging','packaging--expanded-product-families'),
('Replacement component — Barrier film','packaging','packaging--expanded-product-families'),
('Replacement component — Laminating film','packaging','packaging--expanded-product-families'),
('Replacement component — Agricultural film','packaging','packaging--expanded-product-families'),
('Replacement component — Stretch wrap','packaging','packaging--expanded-product-families'),
('Replacement component — Shrink wrap','packaging','packaging--expanded-product-families'),
('Replacement component — Pallet wrap','packaging','packaging--expanded-product-families'),
('Replacement component — Shrink sleeve','packaging','packaging--expanded-product-families'),
('Service equipment — PP woven bag','packaging','packaging--expanded-product-families'),
('Service equipment — Paper bag','packaging','packaging--expanded-product-families'),
('Service equipment — Kraft bag','packaging','packaging--expanded-product-families'),
('Service equipment — Plastic pouch','packaging','packaging--expanded-product-families'),
('Service equipment — Stand-up pouch','packaging','packaging--expanded-product-families'),
('Service equipment — Zipper pouch','packaging','packaging--expanded-product-families'),
('Service equipment — Vacuum pouch','packaging','packaging--expanded-product-families'),
('Service equipment — Retort pouch','packaging','packaging--expanded-product-families'),
('Service equipment — Laminated pouch','packaging','packaging--expanded-product-families'),
('Service equipment — Plastic bottle','packaging','packaging--expanded-product-families'),
('Service equipment — Glass bottle','packaging','packaging--expanded-product-families'),
('Service equipment — Plastic jar','packaging','packaging--expanded-product-families'),
('Service equipment — Glass jar','packaging','packaging--expanded-product-families'),
('Service equipment — Plastic bucket','packaging','packaging--expanded-product-families'),
('Service equipment — Plastic container','packaging','packaging--expanded-product-families'),
('Service equipment — Corrugated carton','packaging','packaging--expanded-product-families'),
('Service equipment — Single-wall carton','packaging','packaging--expanded-product-families'),
('Service equipment — Double-wall carton','packaging','packaging--expanded-product-families'),
('Service equipment — Printed carton','packaging','packaging--expanded-product-families'),
('Service equipment — Die-cut carton','packaging','packaging--expanded-product-families'),
('Service equipment — Export carton','packaging','packaging--expanded-product-families'),
('Service equipment — Pizza box','packaging','packaging--expanded-product-families'),
('Service equipment — Pharmaceutical carton','packaging','packaging--expanded-product-families'),
('Service equipment — Retail carton','packaging','packaging--expanded-product-families'),
('Service equipment — Display carton','packaging','packaging--expanded-product-families'),
('Service equipment — PET bottle','packaging','packaging--expanded-product-families'),
('Service equipment — HDPE bottle','packaging','packaging--expanded-product-families'),
('Service equipment — Bottle cap','packaging','packaging--expanded-product-families'),
('Service equipment — LDPE film','packaging','packaging--expanded-product-families'),
('Service equipment — HDPE film','packaging','packaging--expanded-product-families'),
('Service equipment — PP film','packaging','packaging--expanded-product-families'),
('Service equipment — BOPP film','packaging','packaging--expanded-product-families'),
('Service equipment — Shrink film','packaging','packaging--expanded-product-families'),
('Service equipment — Stretch film','packaging','packaging--expanded-product-families'),
('Service equipment — Cling film','packaging','packaging--expanded-product-families'),
('Service equipment — Barrier film','packaging','packaging--expanded-product-families'),
('Service equipment — Laminating film','packaging','packaging--expanded-product-families'),
('Service equipment — Agricultural film','packaging','packaging--expanded-product-families'),
('Service equipment — Stretch wrap','packaging','packaging--expanded-product-families'),
('Service equipment — Shrink wrap','packaging','packaging--expanded-product-families'),
('Service equipment — Pallet wrap','packaging','packaging--expanded-product-families'),
('Service equipment — Shrink sleeve','packaging','packaging--expanded-product-families'),
('Testing equipment — PP woven bag','packaging','packaging--expanded-product-families'),
('Testing equipment — Paper bag','packaging','packaging--expanded-product-families'),
('Testing equipment — Kraft bag','packaging','packaging--expanded-product-families'),
('Testing equipment — Plastic pouch','packaging','packaging--expanded-product-families'),
('Testing equipment — Stand-up pouch','packaging','packaging--expanded-product-families'),
('Testing equipment — Zipper pouch','packaging','packaging--expanded-product-families'),
('Testing equipment — Vacuum pouch','packaging','packaging--expanded-product-families'),
('Testing equipment — Retort pouch','packaging','packaging--expanded-product-families'),
('Testing equipment — Laminated pouch','packaging','packaging--expanded-product-families'),
('Testing equipment — Plastic bottle','packaging','packaging--expanded-product-families'),
('Testing equipment — Glass bottle','packaging','packaging--expanded-product-families'),
('Testing equipment — Plastic jar','packaging','packaging--expanded-product-families'),
('Testing equipment — Glass jar','packaging','packaging--expanded-product-families'),
('Testing equipment — Plastic bucket','packaging','packaging--expanded-product-families'),
('Testing equipment — Plastic container','packaging','packaging--expanded-product-families'),
('Testing equipment — Corrugated carton','packaging','packaging--expanded-product-families'),
('Testing equipment — Single-wall carton','packaging','packaging--expanded-product-families'),
('Testing equipment — Double-wall carton','packaging','packaging--expanded-product-families'),
('Testing equipment — Printed carton','packaging','packaging--expanded-product-families'),
('Safety helmet','safety-ppe','safety-ppe--core'),
('Bump cap','safety-ppe','safety-ppe--core'),
('Welding helmet','safety-ppe','safety-ppe--core'),
('Helmet visor','safety-ppe','safety-ppe--core'),
('Helmet chin strap','safety-ppe','safety-ppe--core'),
('Helmet lamp','safety-ppe','safety-ppe--core'),
('Helmet ear-muff attachment','safety-ppe','safety-ppe--core'),
('Helmet rain cover','safety-ppe','safety-ppe--core'),
('Helmet sweatband','safety-ppe','safety-ppe--core'),
('Chemical goggles','safety-ppe','safety-ppe--equipment'),
('Welding goggles','safety-ppe','safety-ppe--equipment'),
('Grinding shield','safety-ppe','safety-ppe--equipment'),
('Splash goggles','safety-ppe','safety-ppe--equipment'),
('Dust mask','safety-ppe','safety-ppe--consumables'),
('Half-face respirator','safety-ppe','safety-ppe--consumables'),
('Full-face respirator','safety-ppe','safety-ppe--consumables'),
('Respirator cartridge','safety-ppe','safety-ppe--consumables'),
('Gas filter','safety-ppe','safety-ppe--consumables'),
('Particulate filter','safety-ppe','safety-ppe--components'),
('Welding respirator','safety-ppe','safety-ppe--components'),
('Escape respirator','safety-ppe','safety-ppe--components'),
('Coveralls','safety-ppe','safety-ppe--components'),
('High-visibility vest','safety-ppe','safety-ppe--components'),
('High-visibility jacket','safety-ppe','safety-ppe--components'),
('Welding jacket','safety-ppe','safety-ppe--components'),
('Thermal workwear','safety-ppe','safety-ppe--installation'),
('Nitrile gloves','safety-ppe','safety-ppe--installation'),
('Latex gloves','safety-ppe','safety-ppe--installation'),
('Cut-resistant gloves','safety-ppe','safety-ppe--installation'),
('Heat-resistant gloves','safety-ppe','safety-ppe--installation'),
('Chemical gloves','safety-ppe','safety-ppe--installation'),
('Welding gloves','safety-ppe','safety-ppe--installation'),
('Leather gloves','safety-ppe','safety-ppe--installation'),
('Impact gloves','safety-ppe','safety-ppe--installation'),
('Electrical gloves','safety-ppe','safety-ppe--protection'),
('Safety boots','safety-ppe','safety-ppe--protection'),
('Steel-toe boots','safety-ppe','safety-ppe--protection'),
('Composite-toe boots','safety-ppe','safety-ppe--protection'),
('Chemical boots','safety-ppe','safety-ppe--protection'),
('Electrical safety boots','safety-ppe','safety-ppe--protection'),
('Wellington boots','safety-ppe','safety-ppe--protection'),
('Anti-slip shoes','safety-ppe','safety-ppe--protection'),
('Welding boots','safety-ppe','safety-ppe--protection'),
('Metatarsal boots','safety-ppe','safety-ppe--protection'),
('Safety harness','safety-ppe','safety-ppe--maintenance'),
('Rope grab','safety-ppe','safety-ppe--maintenance'),
('Harness storage bag','safety-ppe','safety-ppe--maintenance'),
('Installation system — Safety helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Bump cap','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Welding helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Helmet visor','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Helmet chin strap','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Helmet lamp','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Helmet ear-muff attachment','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Helmet rain cover','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Helmet sweatband','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Chemical goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Welding goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Grinding shield','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Splash goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Dust mask','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Half-face respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Full-face respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Respirator cartridge','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Gas filter','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Particulate filter','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Welding respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Escape respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Coveralls','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — High-visibility vest','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — High-visibility jacket','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Welding jacket','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Thermal workwear','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Nitrile gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Latex gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Cut-resistant gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Heat-resistant gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Chemical gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Welding gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Leather gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Impact gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Electrical gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Safety boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Steel-toe boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Composite-toe boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Chemical boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Electrical safety boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Wellington boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Anti-slip shoes','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Welding boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Metatarsal boots','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Safety harness','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Rope grab','safety-ppe','safety-ppe--expanded-product-families'),
('Installation system — Harness storage bag','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Safety helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Bump cap','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Welding helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Helmet visor','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Helmet chin strap','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Helmet lamp','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Helmet ear-muff attachment','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Helmet rain cover','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Helmet sweatband','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Chemical goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Welding goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Grinding shield','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Splash goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Dust mask','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Half-face respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Full-face respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Respirator cartridge','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Gas filter','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Particulate filter','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Welding respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Escape respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Coveralls','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — High-visibility vest','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — High-visibility jacket','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Welding jacket','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Thermal workwear','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Nitrile gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Latex gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Cut-resistant gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Heat-resistant gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Chemical gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Welding gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Leather gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Impact gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Electrical gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Safety boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Steel-toe boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Composite-toe boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Chemical boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Electrical safety boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Wellington boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Anti-slip shoes','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Welding boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Metatarsal boots','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Safety harness','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Rope grab','safety-ppe','safety-ppe--expanded-product-families'),
('Replacement component — Harness storage bag','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Safety helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Bump cap','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Welding helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Helmet visor','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Helmet chin strap','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Helmet lamp','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Helmet ear-muff attachment','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Helmet rain cover','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Helmet sweatband','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Chemical goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Welding goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Grinding shield','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Splash goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Dust mask','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Half-face respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Full-face respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Respirator cartridge','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Gas filter','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Particulate filter','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Welding respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Escape respirator','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Coveralls','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — High-visibility vest','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — High-visibility jacket','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Welding jacket','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Thermal workwear','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Nitrile gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Latex gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Cut-resistant gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Heat-resistant gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Chemical gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Welding gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Leather gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Impact gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Electrical gloves','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Safety boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Steel-toe boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Composite-toe boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Chemical boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Electrical safety boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Wellington boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Anti-slip shoes','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Welding boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Metatarsal boots','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Safety harness','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Rope grab','safety-ppe','safety-ppe--expanded-product-families'),
('Service equipment — Harness storage bag','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Safety helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Bump cap','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Welding helmet','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Helmet visor','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Helmet chin strap','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Helmet lamp','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Helmet ear-muff attachment','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Helmet rain cover','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Helmet sweatband','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Chemical goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Welding goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Grinding shield','safety-ppe','safety-ppe--expanded-product-families'),
('Testing equipment — Splash goggles','safety-ppe','safety-ppe--expanded-product-families'),
('Water treatment plant','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('RO plant','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Ultrafiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Nanofiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('UV water purifier','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Chlorination system','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Water softener','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Iron removal filter','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Activated carbon filter','water-treatment-and-waste-management','water-treatment-and-waste-management--core'),
('Sand filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Multimedia filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Cartridge filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Bag filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Disc filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Screen filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Membrane filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Ceramic filter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('Microfilter','water-treatment-and-waste-management','water-treatment-and-waste-management--equipment'),
('RO membrane','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('Membrane housing','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('High-pressure pump','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('RO pressure vessel','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('Antiscalant dosing pump','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('RO control panel','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('RO cleaning system','water-treatment-and-waste-management','water-treatment-and-waste-management--consumables'),
('Activated carbon','water-treatment-and-waste-management','water-treatment-and-waste-management--components'),
('Ion exchange resin','water-treatment-and-waste-management','water-treatment-and-waste-management--installation'),
('Installation system — Water treatment plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — RO plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Ultrafiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Nanofiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — UV water purifier','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Chlorination system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Water softener','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Iron removal filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Activated carbon filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Sand filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Multimedia filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Cartridge filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Bag filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Disc filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Screen filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Membrane filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Ceramic filter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Microfilter','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — RO membrane','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Membrane housing','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — High-pressure pump','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — RO pressure vessel','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Antiscalant dosing pump','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — RO control panel','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — RO cleaning system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Activated carbon','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Installation system — Ion exchange resin','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Water treatment plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — RO plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Ultrafiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Nanofiltration plant','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — UV water purifier','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Chlorination system','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families'),
('Replacement component — Water softener','water-treatment-and-waste-management','water-treatment-and-waste-management--expanded-product-families')
on conflict (n) do update set m = excluded.m, s = excluded.s;
